// <AUTO-GENERATED TOC> DO NOT EDIT MANUALLY
// Table of Contents
//
// 1. Fixture SHA Storage (line 15)
// 2. File Parsing Helper (line 48)
// 3. Public API (line 101)
//
// </AUTO-GENERATED TOC>
// test_fixture_shas.cpp - Runtime loading of fixture SHA values
// Reads SHA values from generated files to avoid hardcoding in tests
#include "test_harness.h"
#include <cstdio>
#include <cstring>

// ============================================================================
// Fixture SHA Storage
// ============================================================================

struct FixtureSHAs {
    bool loaded;

    // Commit SHAs (from known_shas.txt)
    char commit1[41];
    char commit2[41];
    char commit3[41];
    char commit4[41];
    char commit5[41];
    char feature_commit[41];
    char merge_commit[41];

    // Blob SHAs (from blob_shas.txt)
    char blob_feature[41];
    char blob_file1[41];
    char blob_file2[41];
    char blob_script[41];
    char blob_subdir_file3[41];
    char blob_file1_initial[41];

    // Tree SHAs (from tree_shas.txt)
    char tree_initial[41];
    char tree_modify[41];
    char tree_head[41];
    char tree_subdir[41];
};

static FixtureSHAs g_fixture_shas = {};

// ============================================================================
// File Parsing Helper
// ============================================================================

// Parse a line like "KEY=value" and store value if key matches
static bool parse_sha_line(const char* line, const char* key, char* out_value) {
    size_t key_len = strlen(key);
    if (strncmp(line, key, key_len) == 0 && line[key_len] == '=') {
        const char* value = line + key_len + 1;
        // Copy up to 40 chars (SHA hex) and null terminate
        size_t i = 0;
        while (value[i] && value[i] != '\r' && value[i] != '\n' && i < 40) {
            out_value[i] = value[i];
            i++;
        }
        out_value[i] = '\0';
        return true;
    }
    return false;
}

// Load SHAs from a key=value file
static bool load_sha_file(const wchar_t* repo_path, const char* filename,
                          const char** keys, char** values, size_t count) {
    wchar_t full_path[512];
    wchar_t filename_wide[64];
    MultiByteToWideChar(CP_UTF8, 0, filename, -1, filename_wide, 64);

    wcscpy_s(full_path, repo_path);
    wcscat_s(full_path, L"\\");
    wcscat_s(full_path, filename_wide);

    FILE* f = nullptr;
    if (_wfopen_s(&f, full_path, L"r") != 0 || !f) {
        return false;
    }

    char line[256];
    while (fgets(line, sizeof(line), f)) {
        // Skip comments
        if (line[0] == '#') continue;

        for (size_t i = 0; i < count; i++) {
            if (parse_sha_line(line, keys[i], values[i])) {
                break;
            }
        }
    }

    fclose(f);
    return true;
}

// ============================================================================
// Public API
// ============================================================================

// Load all fixture SHAs from files (call once at test startup)
bool fixture_shas_load(const wchar_t* repo_path) {
    if (g_fixture_shas.loaded) {
        return true;  // Already loaded
    }

    // Load commit SHAs
    const char* commit_keys[] = {
        "COMMIT1", "COMMIT2", "COMMIT3", "COMMIT4", "COMMIT5",
        "FEATURE_COMMIT", "MERGE_COMMIT"
    };
    char* commit_values[] = {
        g_fixture_shas.commit1, g_fixture_shas.commit2, g_fixture_shas.commit3,
        g_fixture_shas.commit4, g_fixture_shas.commit5,
        g_fixture_shas.feature_commit, g_fixture_shas.merge_commit
    };
    if (!load_sha_file(repo_path, "known_shas.txt", commit_keys, commit_values, 7)) {
        return false;
    }

    // Load blob SHAs
    const char* blob_keys[] = {
        "BLOB_FEATURE", "BLOB_FILE1", "BLOB_FILE2", "BLOB_SCRIPT",
        "BLOB_SUBDIR_FILE3", "BLOB_FILE1_INITIAL"
    };
    char* blob_values[] = {
        g_fixture_shas.blob_feature, g_fixture_shas.blob_file1,
        g_fixture_shas.blob_file2, g_fixture_shas.blob_script,
        g_fixture_shas.blob_subdir_file3, g_fixture_shas.blob_file1_initial
    };
    if (!load_sha_file(repo_path, "blob_shas.txt", blob_keys, blob_values, 6)) {
        return false;
    }

    // Load tree SHAs
    const char* tree_keys[] = {
        "TREE_INITIAL", "TREE_MODIFY", "TREE_HEAD", "TREE_SUBDIR"
    };
    char* tree_values[] = {
        g_fixture_shas.tree_initial, g_fixture_shas.tree_modify,
        g_fixture_shas.tree_head, g_fixture_shas.tree_subdir
    };
    if (!load_sha_file(repo_path, "tree_shas.txt", tree_keys, tree_values, 4)) {
        return false;
    }

    g_fixture_shas.loaded = true;
    return true;
}

// Reset loaded state (for testing)
void fixture_shas_reset() {
    memset(&g_fixture_shas, 0, sizeof(g_fixture_shas));
}

// Accessor functions - return empty string if not loaded
const char* fixture_sha_commit1() { return g_fixture_shas.commit1; }
const char* fixture_sha_commit2() { return g_fixture_shas.commit2; }
const char* fixture_sha_commit3() { return g_fixture_shas.commit3; }
const char* fixture_sha_commit4() { return g_fixture_shas.commit4; }
const char* fixture_sha_commit5() { return g_fixture_shas.commit5; }
const char* fixture_sha_feature_commit() { return g_fixture_shas.feature_commit; }
const char* fixture_sha_merge_commit() { return g_fixture_shas.merge_commit; }

const char* fixture_sha_blob_feature() { return g_fixture_shas.blob_feature; }
const char* fixture_sha_blob_file1() { return g_fixture_shas.blob_file1; }
const char* fixture_sha_blob_file2() { return g_fixture_shas.blob_file2; }
const char* fixture_sha_blob_script() { return g_fixture_shas.blob_script; }
const char* fixture_sha_blob_subdir_file3() { return g_fixture_shas.blob_subdir_file3; }
const char* fixture_sha_blob_file1_initial() { return g_fixture_shas.blob_file1_initial; }

const char* fixture_sha_tree_initial() { return g_fixture_shas.tree_initial; }
const char* fixture_sha_tree_modify() { return g_fixture_shas.tree_modify; }
const char* fixture_sha_tree_head() { return g_fixture_shas.tree_head; }
const char* fixture_sha_tree_subdir() { return g_fixture_shas.tree_subdir; }

// Check if SHAs are loaded
bool fixture_shas_loaded() { return g_fixture_shas.loaded; }
