// <AUTO-GENERATED TOC> DO NOT EDIT MANUALLY
// Table of Contents
//
// 1. Cherry-Pick Tests (line 61)
// 2. Revert Tests (line 252)
//
// </AUTO-GENERATED TOC>
// test_cherry_pick.cpp - Cherry-pick and revert operations tests
// Tests for git_cherry_pick() and git_revert()
#include "test_harness.h"

// Path to fixture repository (source for copies)
static const wchar_t* CHERRY_TEST_FIXTURE_PATH = L"test\\fixtures\\test_repo";

// Path to current temp test repo (empty if none active)
static wchar_t g_cherry_test_repo[512] = {};

// Forward declarations from test_write.cpp
extern bool delete_directory_recursive(const wchar_t* path);
extern bool copy_directory_recursive(const wchar_t* src, const wchar_t* dst);

// Create fresh temp copy of fixture repo
static bool create_cherry_test_repo() {
    if (g_cherry_test_repo[0] != L'\0') {
        delete_directory_recursive(g_cherry_test_repo);
        g_cherry_test_repo[0] = L'\0';
    }

    wchar_t temp_base[512];
    DWORD len = GetTempPathW(512, temp_base);
    if (len == 0 || len >= 512) {
        return false;
    }

    wchar_t temp_path[512];
    wcscpy_s(temp_path, temp_base);
    wcscat_s(temp_path, L"GitSmarter_cherry_test_");

    LARGE_INTEGER counter;
    QueryPerformanceCounter(&counter);
    wchar_t suffix[32];
    swprintf_s(suffix, L"%llx", counter.QuadPart);
    wcscat_s(temp_path, suffix);

    if (!copy_directory_recursive(CHERRY_TEST_FIXTURE_PATH, temp_path)) {
        delete_directory_recursive(temp_path);
        return false;
    }

    wcscpy_s(g_cherry_test_repo, temp_path);
    return true;
}

static void cleanup_cherry_test_repo() {
    if (g_cherry_test_repo[0] != L'\0') {
        delete_directory_recursive(g_cherry_test_repo);
        g_cherry_test_repo[0] = L'\0';
    }
}

// ============================================================================
// Cherry-Pick Tests
// ============================================================================

TEST(cherry_pick_simple) {
    if (!create_cherry_test_repo()) {
        TEST_SKIP("Could not create temp test repo");
    }

    GitRepository repo = {};
    if (!git_repo_open(&repo, g_cherry_test_repo)) {
        cleanup_cherry_test_repo();
        TEST_SKIP("Could not open temp repo");
    }

    // Get parent commit (we'll reset to grandparent, then cherry-pick parent)
    GitCommit head = {};
    TEST_ASSERT_TRUE(git_read_commit(&repo, repo.head_sha, &head));

    if (head.parent_sha[0] == '\0') {
        git_repo_close(&repo);
        cleanup_cherry_test_repo();
        TEST_SKIP("HEAD has no parent");
    }

    GitCommit parent = {};
    TEST_ASSERT_TRUE(git_read_commit(&repo, head.parent_sha, &parent));

    if (parent.parent_sha[0] == '\0') {
        git_repo_close(&repo);
        cleanup_cherry_test_repo();
        TEST_SKIP("Need at least 3 commits for cherry-pick test");
    }

    // Save the commit we want to cherry-pick (HEAD)
    char commit_to_pick[41];
    strcpy_s(commit_to_pick, repo.head_sha);

    // Reset to grandparent (HEAD~2)
    char error[256] = {};
    TEST_ASSERT_TRUE(git_reset(&repo, parent.parent_sha, ResetMode::Hard, error, sizeof(error)));
    TEST_ASSERT_TRUE(git_read_head(&repo));

    char before_pick_head[41];
    strcpy_s(before_pick_head, repo.head_sha);

    // Cherry-pick the original HEAD commit
    bool result = git_cherry_pick(&repo, commit_to_pick, error, sizeof(error));
    TEST_ASSERT_TRUE(result);

    // HEAD should have advanced (new commit created)
    TEST_ASSERT_TRUE(git_read_head(&repo));
    TEST_ASSERT_STRNE(repo.head_sha, before_pick_head);

    // New commit's parent should be our before_pick_head
    GitCommit new_commit = {};
    TEST_ASSERT_TRUE(git_read_commit(&repo, repo.head_sha, &new_commit));
    TEST_ASSERT_STREQ(new_commit.parent_sha, before_pick_head);

    git_repo_close(&repo);
    cleanup_cherry_test_repo();
}

TEST(cherry_pick_root_commit_fails) {
    if (!create_cherry_test_repo()) {
        TEST_SKIP("Could not create temp test repo");
    }

    GitRepository repo = {};
    if (!git_repo_open(&repo, g_cherry_test_repo)) {
        cleanup_cherry_test_repo();
        TEST_SKIP("Could not open temp repo");
    }

    // Find root commit (walk back until no parent)
    char current[41];
    strcpy_s(current, repo.head_sha);

    GitCommit commit = {};
    while (true) {
        TEST_ASSERT_TRUE(git_read_commit(&repo, current, &commit));
        if (commit.parent_sha[0] == '\0') {
            break; // Found root
        }
        strcpy_s(current, commit.parent_sha);
    }

    // Trying to cherry-pick root commit should fail
    char error[256] = {};
    bool result = git_cherry_pick(&repo, current, error, sizeof(error));
    TEST_ASSERT_FALSE(result);
    TEST_ASSERT_TRUE(strlen(error) > 0);
    TEST_ASSERT_TRUE(strstr(error, "parent") != nullptr || strstr(error, "root") != nullptr);

    git_repo_close(&repo);
    cleanup_cherry_test_repo();
}

TEST(cherry_pick_merge_commit_fails) {
    if (!create_cherry_test_repo()) {
        TEST_SKIP("Could not create temp test repo");
    }

    GitRepository repo = {};
    if (!git_repo_open(&repo, g_cherry_test_repo)) {
        cleanup_cherry_test_repo();
        TEST_SKIP("Could not open temp repo");
    }

    // Check if HEAD is a merge commit (has parent2_sha)
    GitCommit head = {};
    TEST_ASSERT_TRUE(git_read_commit(&repo, repo.head_sha, &head));

    // If we don't have a merge commit in the fixture, skip
    // We'd need to create one or find one in history
    bool found_merge = false;
    char merge_sha[41] = {};

    char current[41];
    strcpy_s(current, repo.head_sha);
    for (int i = 0; i < 20; i++) { // Check last 20 commits
        GitCommit c = {};
        if (!git_read_commit(&repo, current, &c)) break;

        if (c.parent2_sha[0] != '\0') {
            found_merge = true;
            strcpy_s(merge_sha, current);
            break;
        }

        if (c.parent_sha[0] == '\0') break;
        strcpy_s(current, c.parent_sha);
    }

    if (!found_merge) {
        git_repo_close(&repo);
        cleanup_cherry_test_repo();
        TEST_SKIP("No merge commit found in fixture");
    }

    // Trying to cherry-pick merge commit should fail
    char error[256] = {};
    bool result = git_cherry_pick(&repo, merge_sha, error, sizeof(error));
    TEST_ASSERT_FALSE(result);
    TEST_ASSERT_TRUE(strstr(error, "merge") != nullptr);

    git_repo_close(&repo);
    cleanup_cherry_test_repo();
}

TEST(cherry_pick_invalid_commit) {
    if (!create_cherry_test_repo()) {
        TEST_SKIP("Could not create temp test repo");
    }

    GitRepository repo = {};
    if (!git_repo_open(&repo, g_cherry_test_repo)) {
        cleanup_cherry_test_repo();
        TEST_SKIP("Could not open temp repo");
    }

    char error[256] = {};
    bool result = git_cherry_pick(&repo, "0000000000000000000000000000000000000000", error, sizeof(error));
    TEST_ASSERT_FALSE(result);
    TEST_ASSERT_TRUE(strlen(error) > 0);

    git_repo_close(&repo);
    cleanup_cherry_test_repo();
}

TEST(cherry_pick_null_inputs) {
    if (!create_cherry_test_repo()) {
        TEST_SKIP("Could not create temp test repo");
    }

    GitRepository repo = {};
    if (!git_repo_open(&repo, g_cherry_test_repo)) {
        cleanup_cherry_test_repo();
        TEST_SKIP("Could not open temp repo");
    }

    char error[256] = {};

    TEST_ASSERT_FALSE(git_cherry_pick(nullptr, repo.head_sha, error, sizeof(error)));
    TEST_ASSERT_FALSE(git_cherry_pick(&repo, nullptr, error, sizeof(error)));
    TEST_ASSERT_FALSE(git_cherry_pick(&repo, "", error, sizeof(error)));

    git_repo_close(&repo);
    cleanup_cherry_test_repo();
}

// ============================================================================
// Revert Tests
// ============================================================================

TEST(revert_simple) {
    if (!create_cherry_test_repo()) {
        TEST_SKIP("Could not create temp test repo");
    }

    GitRepository repo = {};
    if (!git_repo_open(&repo, g_cherry_test_repo)) {
        cleanup_cherry_test_repo();
        TEST_SKIP("Could not open temp repo");
    }

    GitCommit head = {};
    TEST_ASSERT_TRUE(git_read_commit(&repo, repo.head_sha, &head));

    if (head.parent_sha[0] == '\0') {
        git_repo_close(&repo);
        cleanup_cherry_test_repo();
        TEST_SKIP("HEAD has no parent");
    }

    char original_head[41];
    strcpy_s(original_head, repo.head_sha);

    // Revert HEAD
    char error[256] = {};
    bool result = git_revert(&repo, original_head, error, sizeof(error));
    TEST_ASSERT_TRUE(result);

    // HEAD should have advanced (revert commit created)
    TEST_ASSERT_TRUE(git_read_head(&repo));
    TEST_ASSERT_STRNE(repo.head_sha, original_head);

    // New commit's parent should be original HEAD
    GitCommit revert_commit = {};
    TEST_ASSERT_TRUE(git_read_commit(&repo, repo.head_sha, &revert_commit));
    TEST_ASSERT_STREQ(revert_commit.parent_sha, original_head);

    // Message should mention "Revert"
    TEST_ASSERT_TRUE(strstr(revert_commit.message, "Revert") != nullptr);

    git_repo_close(&repo);
    cleanup_cherry_test_repo();
}

TEST(revert_creates_commit) {
    if (!create_cherry_test_repo()) {
        TEST_SKIP("Could not create temp test repo");
    }

    GitRepository repo = {};
    if (!git_repo_open(&repo, g_cherry_test_repo)) {
        cleanup_cherry_test_repo();
        TEST_SKIP("Could not open temp repo");
    }

    GitCommit head = {};
    TEST_ASSERT_TRUE(git_read_commit(&repo, repo.head_sha, &head));

    if (head.parent_sha[0] == '\0') {
        git_repo_close(&repo);
        cleanup_cherry_test_repo();
        TEST_SKIP("HEAD has no parent");
    }

    // Count commits before
    int commits_before = 0;
    char current[41];
    strcpy_s(current, repo.head_sha);
    while (true) {
        GitCommit c = {};
        if (!git_read_commit(&repo, current, &c)) break;
        commits_before++;
        if (c.parent_sha[0] == '\0') break;
        strcpy_s(current, c.parent_sha);
    }

    // Revert HEAD
    char error[256] = {};
    TEST_ASSERT_TRUE(git_revert(&repo, repo.head_sha, error, sizeof(error)));
    TEST_ASSERT_TRUE(git_read_head(&repo));

    // Count commits after
    int commits_after = 0;
    strcpy_s(current, repo.head_sha);
    while (true) {
        GitCommit c = {};
        if (!git_read_commit(&repo, current, &c)) break;
        commits_after++;
        if (c.parent_sha[0] == '\0') break;
        strcpy_s(current, c.parent_sha);
    }

    // Should have one more commit
    TEST_ASSERT_EQ(commits_after, commits_before + 1);

    git_repo_close(&repo);
    cleanup_cherry_test_repo();
}

TEST(revert_merge_commit_fails) {
    if (!create_cherry_test_repo()) {
        TEST_SKIP("Could not create temp test repo");
    }

    GitRepository repo = {};
    if (!git_repo_open(&repo, g_cherry_test_repo)) {
        cleanup_cherry_test_repo();
        TEST_SKIP("Could not open temp repo");
    }

    // Find a merge commit in history
    bool found_merge = false;
    char merge_sha[41] = {};

    char current[41];
    strcpy_s(current, repo.head_sha);
    for (int i = 0; i < 20; i++) {
        GitCommit c = {};
        if (!git_read_commit(&repo, current, &c)) break;

        if (c.parent2_sha[0] != '\0') {
            found_merge = true;
            strcpy_s(merge_sha, current);
            break;
        }

        if (c.parent_sha[0] == '\0') break;
        strcpy_s(current, c.parent_sha);
    }

    if (!found_merge) {
        git_repo_close(&repo);
        cleanup_cherry_test_repo();
        TEST_SKIP("No merge commit found in fixture");
    }

    char error[256] = {};
    bool result = git_revert(&repo, merge_sha, error, sizeof(error));
    TEST_ASSERT_FALSE(result);
    TEST_ASSERT_TRUE(strstr(error, "merge") != nullptr);

    git_repo_close(&repo);
    cleanup_cherry_test_repo();
}

TEST(revert_root_commit_fails) {
    if (!create_cherry_test_repo()) {
        TEST_SKIP("Could not create temp test repo");
    }

    GitRepository repo = {};
    if (!git_repo_open(&repo, g_cherry_test_repo)) {
        cleanup_cherry_test_repo();
        TEST_SKIP("Could not open temp repo");
    }

    // Find root commit
    char current[41];
    strcpy_s(current, repo.head_sha);
    GitCommit commit = {};
    while (true) {
        TEST_ASSERT_TRUE(git_read_commit(&repo, current, &commit));
        if (commit.parent_sha[0] == '\0') break;
        strcpy_s(current, commit.parent_sha);
    }

    // Reverting root commit should fail (no parent to diff against)
    char error[256] = {};
    bool result = git_revert(&repo, current, error, sizeof(error));
    TEST_ASSERT_FALSE(result);
    TEST_ASSERT_TRUE(strlen(error) > 0);

    git_repo_close(&repo);
    cleanup_cherry_test_repo();
}

TEST(revert_invalid_commit) {
    if (!create_cherry_test_repo()) {
        TEST_SKIP("Could not create temp test repo");
    }

    GitRepository repo = {};
    if (!git_repo_open(&repo, g_cherry_test_repo)) {
        cleanup_cherry_test_repo();
        TEST_SKIP("Could not open temp repo");
    }

    char error[256] = {};
    bool result = git_revert(&repo, "0000000000000000000000000000000000000000", error, sizeof(error));
    TEST_ASSERT_FALSE(result);
    TEST_ASSERT_TRUE(strlen(error) > 0);

    git_repo_close(&repo);
    cleanup_cherry_test_repo();
}

TEST(revert_null_inputs) {
    if (!create_cherry_test_repo()) {
        TEST_SKIP("Could not create temp test repo");
    }

    GitRepository repo = {};
    if (!git_repo_open(&repo, g_cherry_test_repo)) {
        cleanup_cherry_test_repo();
        TEST_SKIP("Could not open temp repo");
    }

    char error[256] = {};

    TEST_ASSERT_FALSE(git_revert(nullptr, repo.head_sha, error, sizeof(error)));
    TEST_ASSERT_FALSE(git_revert(&repo, nullptr, error, sizeof(error)));
    TEST_ASSERT_FALSE(git_revert(&repo, "", error, sizeof(error)));

    git_repo_close(&repo);
    cleanup_cherry_test_repo();
}

// Cherry-picking a commit that adds a path already present with different content
// must report conflict (not silently overwrite).
TEST(cherry_pick_addition_conflict) {
    if (!create_cherry_test_repo()) {
        TEST_SKIP("Could not create temp test repo");
    }

    GitRepository repo = {};
    if (!git_repo_open(&repo, g_cherry_test_repo)) {
        cleanup_cherry_test_repo();
        TEST_SKIP("Could not open temp repo");
    }

    // Commit A: add unique path
    write_test_file(g_cherry_test_repo, "pick_add.txt", "from-picked-commit\n");
    TEST_ASSERT_TRUE(git_stage_file(&repo, "pick_add.txt"));
    TEST_ASSERT_TRUE(git_commit(&repo, "add pick_add.txt", false));
    char pick_sha[41];
    strcpy_s(pick_sha, repo.head_sha);

    // Reset hard to parent so pick_add is gone
    GitCommit pick_commit = {};
    TEST_ASSERT_TRUE(git_read_commit(&repo, pick_sha, &pick_commit));
    TEST_ASSERT_TRUE(pick_commit.parent_sha[0] != '\0');
    char error[256] = {};
    TEST_ASSERT_TRUE(git_reset(&repo, pick_commit.parent_sha, ResetMode::Hard, error, sizeof(error)));
    TEST_ASSERT_TRUE(git_read_head(&repo));

    // Create conflicting content at same path on a new commit
    write_test_file(g_cherry_test_repo, "pick_add.txt", "already-on-target\n");
    TEST_ASSERT_TRUE(git_stage_file(&repo, "pick_add.txt"));
    TEST_ASSERT_TRUE(git_commit(&repo, "conflicting add", false));

    // Cherry-pick the first add — target has different content for same path
    error[0] = '\0';
    bool ok = git_cherry_pick(&repo, pick_sha, error, sizeof(error));
    TEST_ASSERT_FALSE(ok);
    TEST_ASSERT_TRUE(strstr(error, "Conflict") != nullptr || strstr(error, "conflict") != nullptr);

    git_repo_close(&repo);
    cleanup_cherry_test_repo();
}
