// <AUTO-GENERATED TOC> DO NOT EDIT MANUALLY
// Table of Contents
//
// 1. Known Fixture Values (line 22)
// 2. Index Reading Tests (line 41)
// 3. Index Writing Tests (line 246)
// 4. Index Locking Tests (line 474)
// 5. Index Manipulation Tests (line 559)
//
// </AUTO-GENERATED TOC>
// test_index_io.cpp - Git index file I/O tests
// Tests for reading, writing, and manipulating git index files
//
// Phase 3 of test coverage expansion plan:
// - Index reading (v2/v3 format, header validation, entry extraction)
// - Index writing (roundtrip, atomic writes, checksums)
// - Index locking (acquire, contention, release)
// - Index manipulation (add, remove, update entries)

#include "test_harness.h"

// ============================================================================
// Known Fixture Values
// ============================================================================

// Use the same test repo path as other integration tests (defined in test_integration.cpp)
// test/fixtures/test_repo has 5 files in its index.
// SHAs are loaded at runtime from blob_shas.txt by test_fixture_shas.cpp

static const wchar_t* INDEX_TEST_REPO_PATH = L"test\\fixtures\\test_repo";

// Accessor macros for runtime-loaded SHAs (see test_fixture_shas.cpp)
#define FIXTURE_FILE1_SHA fixture_sha_blob_file1()
#define FIXTURE_FILE2_SHA fixture_sha_blob_file2()
#define FIXTURE_SCRIPT_SHA fixture_sha_blob_script()
#define FIXTURE_FEATURE_SHA fixture_sha_blob_feature()
#define FIXTURE_SUBDIR_FILE3_SHA fixture_sha_blob_subdir_file3()

static const size_t FIXTURE_INDEX_ENTRY_COUNT = 5;

// ============================================================================
// Index Reading Tests
// ============================================================================

// Test: Open index file in v2 format (most common)
TEST(index_io_open_v2_format) {
    GitRepository repo = {};
    if (!git_repo_open(&repo, INDEX_TEST_REPO_PATH)) {
        TEST_SKIP("Fixture repo not found");
    }

    GitIndex index = {};
    bool result = git_index_open(&repo, &index);
    TEST_ASSERT_TRUE(result);

    // Fixture repo uses v2 format
    TEST_ASSERT_EQ(index.version, (uint32_t)2);

    git_index_close(&index);
    git_repo_close(&repo);
}

// Test: Open full index and verify version
TEST(index_io_open_full_v2_format) {
    GitRepository repo = {};
    if (!git_repo_open(&repo, INDEX_TEST_REPO_PATH)) {
        TEST_SKIP("Fixture repo not found");
    }

    GitIndexFull index = {};
    bool result = git_index_open_full(&repo, &index);
    TEST_ASSERT_TRUE(result);
    TEST_ASSERT_EQ(index.version, (uint32_t)2);

    git_index_close_full(&index);
    git_repo_close(&repo);
}

// Test: Entry count matches expected
TEST(index_io_entry_count_accurate) {
    GitRepository repo = {};
    if (!git_repo_open(&repo, INDEX_TEST_REPO_PATH)) {
        TEST_SKIP("Fixture repo not found");
    }

    GitIndex index = {};
    bool result = git_index_open(&repo, &index);
    TEST_ASSERT_TRUE(result);
    TEST_ASSERT_EQ(index.entry_count, FIXTURE_INDEX_ENTRY_COUNT);

    git_index_close(&index);
    git_repo_close(&repo);
}

// Test: Entry count matches for full index
TEST(index_io_entry_count_accurate_full) {
    GitRepository repo = {};
    if (!git_repo_open(&repo, INDEX_TEST_REPO_PATH)) {
        TEST_SKIP("Fixture repo not found");
    }

    GitIndexFull index = {};
    bool result = git_index_open_full(&repo, &index);
    TEST_ASSERT_TRUE(result);
    TEST_ASSERT_EQ(index.entry_count, FIXTURE_INDEX_ENTRY_COUNT);

    git_index_close_full(&index);
    git_repo_close(&repo);
}

// Test: Extract file paths correctly
TEST(index_io_entry_path_extraction) {
    GitRepository repo = {};
    if (!git_repo_open(&repo, INDEX_TEST_REPO_PATH)) {
        TEST_SKIP("Fixture repo not found");
    }

    GitIndex index = {};
    bool result = git_index_open(&repo, &index);
    TEST_ASSERT_TRUE(result);

    // Index entries should be sorted alphabetically
    // Expected order: feature.txt, file1.txt, file2.txt, script.sh, subdir/file3.txt
    TEST_ASSERT_STREQ(index.entries[0].path, "feature.txt");
    TEST_ASSERT_STREQ(index.entries[1].path, "file1.txt");
    TEST_ASSERT_STREQ(index.entries[2].path, "file2.txt");
    TEST_ASSERT_STREQ(index.entries[3].path, "script.sh");
    TEST_ASSERT_STREQ(index.entries[4].path, "subdir/file3.txt");

    git_index_close(&index);
    git_repo_close(&repo);
}

// Test: Extract SHA for each entry correctly
TEST(index_io_entry_sha_extraction) {
    GitRepository repo = {};
    if (!git_repo_open(&repo, INDEX_TEST_REPO_PATH)) {
        TEST_SKIP("Fixture repo not found");
    }

    GitIndex index = {};
    bool result = git_index_open(&repo, &index);
    TEST_ASSERT_TRUE(result);

    // Verify SHA values match expected (entries sorted by path)
    TEST_ASSERT_STREQ(index.entries[0].sha, FIXTURE_FEATURE_SHA);      // feature.txt
    TEST_ASSERT_STREQ(index.entries[1].sha, FIXTURE_FILE1_SHA);        // file1.txt
    TEST_ASSERT_STREQ(index.entries[2].sha, FIXTURE_FILE2_SHA);        // file2.txt
    TEST_ASSERT_STREQ(index.entries[3].sha, FIXTURE_SCRIPT_SHA);       // script.sh
    TEST_ASSERT_STREQ(index.entries[4].sha, FIXTURE_SUBDIR_FILE3_SHA); // subdir/file3.txt

    git_index_close(&index);
    git_repo_close(&repo);
}

// Test: Extract file mode correctly
TEST(index_io_entry_mode_extraction) {
    GitRepository repo = {};
    if (!git_repo_open(&repo, INDEX_TEST_REPO_PATH)) {
        TEST_SKIP("Fixture repo not found");
    }

    GitIndex index = {};
    bool result = git_index_open(&repo, &index);
    TEST_ASSERT_TRUE(result);

    // Regular files have mode 100644
    TEST_ASSERT_EQ(index.entries[0].mode, Git::MODE_FILE);  // feature.txt
    TEST_ASSERT_EQ(index.entries[1].mode, Git::MODE_FILE);  // file1.txt
    TEST_ASSERT_EQ(index.entries[2].mode, Git::MODE_FILE);  // file2.txt

    // script.sh is executable (100755)
    TEST_ASSERT_EQ(index.entries[3].mode, Git::MODE_EXECUTABLE);  // script.sh

    // subdir/file3.txt is regular
    TEST_ASSERT_EQ(index.entries[4].mode, Git::MODE_FILE);  // subdir/file3.txt

    git_index_close(&index);
    git_repo_close(&repo);
}

// Test: Full index extracts file size
TEST(index_io_entry_size_extraction) {
    GitRepository repo = {};
    if (!git_repo_open(&repo, INDEX_TEST_REPO_PATH)) {
        TEST_SKIP("Fixture repo not found");
    }

    GitIndexFull index = {};
    bool result = git_index_open_full(&repo, &index);
    TEST_ASSERT_TRUE(result);

    // All entries should have non-zero file_size (they have content)
    for (size_t i = 0; i < index.entry_count; i++) {
        // File size is stored but may be 0 for some edge cases
        // Just verify we parsed it (not corrupted)
        TEST_ASSERT_TRUE(index.entries[i].file_size >= 0);
    }

    git_index_close_full(&index);
    git_repo_close(&repo);
}

// Test: Full index extracts mtime
TEST(index_io_entry_mtime_extraction) {
    GitRepository repo = {};
    if (!git_repo_open(&repo, INDEX_TEST_REPO_PATH)) {
        TEST_SKIP("Fixture repo not found");
    }

    GitIndexFull index = {};
    bool result = git_index_open_full(&repo, &index);
    TEST_ASSERT_TRUE(result);

    // mtime_sec should be non-zero (timestamp)
    for (size_t i = 0; i < index.entry_count; i++) {
        // Entries should have reasonable mtime (after year 2000)
        TEST_ASSERT_TRUE(index.entries[i].mtime_sec > 946684800);  // Jan 1, 2000
    }

    git_index_close_full(&index);
    git_repo_close(&repo);
}

// Test: Entries are in sorted order
TEST(index_io_sorted_order) {
    GitRepository repo = {};
    if (!git_repo_open(&repo, INDEX_TEST_REPO_PATH)) {
        TEST_SKIP("Fixture repo not found");
    }

    GitIndex index = {};
    bool result = git_index_open(&repo, &index);
    TEST_ASSERT_TRUE(result);

    // Verify entries are sorted alphabetically by path
    for (size_t i = 1; i < index.entry_count; i++) {
        int cmp = strcmp(index.entries[i-1].path, index.entries[i].path);
        TEST_ASSERT_TRUE(cmp < 0);  // Previous path should be less than current
    }

    git_index_close(&index);
    git_repo_close(&repo);
}

// ============================================================================
// Index Writing Tests
// ============================================================================

// Test: Write empty index
TEST(index_io_write_empty) {
    GitRepository repo = {};
    if (!git_repo_open(&repo, INDEX_TEST_REPO_PATH)) {
        TEST_SKIP("Fixture repo not found");
    }

    // First backup the original index
    GitIndexFull original = {};
    if (!git_index_open_full(&repo, &original)) {
        git_repo_close(&repo);
        TEST_SKIP("Could not open original index");
    }

    // Create empty index
    GitIndexFull empty = {};
    empty.version = 2;
    empty.entries = new GitIndexEntryFull[1];
    empty.entry_count = 0;
    empty.capacity = 1;

    // Lock and write
    if (!git_index_lock(&repo, 1000)) {
        git_index_close_full(&original);
        delete[] empty.entries;
        git_repo_close(&repo);
        TEST_SKIP("Could not acquire index lock");
    }

    bool write_result = git_index_write(&repo, &empty);
    git_index_unlock(&repo);

    // Verify write succeeded
    TEST_ASSERT_TRUE(write_result);

    // Read back and verify empty
    GitIndexFull readback = {};
    bool read_result = git_index_open_full(&repo, &readback);
    TEST_ASSERT_TRUE(read_result);
    TEST_ASSERT_EQ(readback.entry_count, (size_t)0);
    git_index_close_full(&readback);

    // Restore original index
    git_index_lock(&repo, 1000);
    git_index_write(&repo, &original);
    git_index_unlock(&repo);

    git_index_close_full(&original);
    delete[] empty.entries;
    git_repo_close(&repo);
}

// Test: Write single entry
TEST(index_io_write_single_entry) {
    GitRepository repo = {};
    if (!git_repo_open(&repo, INDEX_TEST_REPO_PATH)) {
        TEST_SKIP("Fixture repo not found");
    }

    // Backup original
    GitIndexFull original = {};
    if (!git_index_open_full(&repo, &original)) {
        git_repo_close(&repo);
        TEST_SKIP("Could not open original index");
    }

    // Create single-entry index
    GitIndexFull single = {};
    single.version = 2;
    single.entries = new GitIndexEntryFull[1];
    single.entry_count = 1;
    single.capacity = 1;

    memset(&single.entries[0], 0, sizeof(GitIndexEntryFull));
    single.entries[0].mode = Git::MODE_FILE;
    strcpy_s(single.entries[0].sha, FIXTURE_FILE1_SHA);
    strcpy_s(single.entries[0].path, "test_file.txt");
    single.entries[0].file_size = 10;
    single.entries[0].mtime_sec = 1700000000;

    // Write
    if (!git_index_lock(&repo, 1000)) {
        git_index_close_full(&original);
        delete[] single.entries;
        git_repo_close(&repo);
        TEST_SKIP("Could not acquire index lock");
    }

    bool write_result = git_index_write(&repo, &single);
    git_index_unlock(&repo);
    TEST_ASSERT_TRUE(write_result);

    // Read back
    GitIndexFull readback = {};
    TEST_ASSERT_TRUE(git_index_open_full(&repo, &readback));
    TEST_ASSERT_EQ(readback.entry_count, (size_t)1);
    TEST_ASSERT_STREQ(readback.entries[0].path, "test_file.txt");
    TEST_ASSERT_STREQ(readback.entries[0].sha, FIXTURE_FILE1_SHA);
    git_index_close_full(&readback);

    // Restore original
    git_index_lock(&repo, 1000);
    git_index_write(&repo, &original);
    git_index_unlock(&repo);

    git_index_close_full(&original);
    delete[] single.entries;
    git_repo_close(&repo);
}

// Test: Write multiple entries and verify sorted output
TEST(index_io_write_multiple_entries_sorted) {
    GitRepository repo = {};
    if (!git_repo_open(&repo, INDEX_TEST_REPO_PATH)) {
        TEST_SKIP("Fixture repo not found");
    }

    // Backup original
    GitIndexFull original = {};
    if (!git_index_open_full(&repo, &original)) {
        git_repo_close(&repo);
        TEST_SKIP("Could not open original index");
    }

    // Create index with entries in WRONG order (git_index_write should sort)
    GitIndexFull unsorted = {};
    unsorted.version = 2;
    unsorted.entries = new GitIndexEntryFull[3];
    unsorted.entry_count = 3;
    unsorted.capacity = 3;

    memset(unsorted.entries, 0, sizeof(GitIndexEntryFull) * 3);

    // Add in reverse alphabetical order
    unsorted.entries[0].mode = Git::MODE_FILE;
    strcpy_s(unsorted.entries[0].sha, FIXTURE_FILE1_SHA);
    strcpy_s(unsorted.entries[0].path, "zzz.txt");

    unsorted.entries[1].mode = Git::MODE_FILE;
    strcpy_s(unsorted.entries[1].sha, FIXTURE_FILE2_SHA);
    strcpy_s(unsorted.entries[1].path, "mmm.txt");

    unsorted.entries[2].mode = Git::MODE_FILE;
    strcpy_s(unsorted.entries[2].sha, FIXTURE_FEATURE_SHA);
    strcpy_s(unsorted.entries[2].path, "aaa.txt");

    // Write
    if (!git_index_lock(&repo, 1000)) {
        git_index_close_full(&original);
        delete[] unsorted.entries;
        git_repo_close(&repo);
        TEST_SKIP("Could not acquire index lock");
    }

    bool write_result = git_index_write(&repo, &unsorted);
    git_index_unlock(&repo);
    TEST_ASSERT_TRUE(write_result);

    // Read back and verify sorted
    GitIndexFull readback = {};
    TEST_ASSERT_TRUE(git_index_open_full(&repo, &readback));
    TEST_ASSERT_EQ(readback.entry_count, (size_t)3);

    // Should be sorted: aaa.txt, mmm.txt, zzz.txt
    TEST_ASSERT_STREQ(readback.entries[0].path, "aaa.txt");
    TEST_ASSERT_STREQ(readback.entries[1].path, "mmm.txt");
    TEST_ASSERT_STREQ(readback.entries[2].path, "zzz.txt");

    git_index_close_full(&readback);

    // Restore original
    git_index_lock(&repo, 1000);
    git_index_write(&repo, &original);
    git_index_unlock(&repo);

    git_index_close_full(&original);
    delete[] unsorted.entries;
    git_repo_close(&repo);
}

// Test: Roundtrip - read, write, read produces identical result
TEST(index_io_write_roundtrip) {
    GitRepository repo = {};
    if (!git_repo_open(&repo, INDEX_TEST_REPO_PATH)) {
        TEST_SKIP("Fixture repo not found");
    }

    // Read original
    GitIndexFull original = {};
    if (!git_index_open_full(&repo, &original)) {
        git_repo_close(&repo);
        TEST_SKIP("Could not open original index");
    }

    // Write it back
    if (!git_index_lock(&repo, 1000)) {
        git_index_close_full(&original);
        git_repo_close(&repo);
        TEST_SKIP("Could not acquire index lock");
    }

    bool write_result = git_index_write(&repo, &original);
    git_index_unlock(&repo);
    TEST_ASSERT_TRUE(write_result);

    // Read again
    GitIndexFull readback = {};
    TEST_ASSERT_TRUE(git_index_open_full(&repo, &readback));

    // Verify same entry count
    TEST_ASSERT_EQ(readback.entry_count, original.entry_count);

    // Verify each entry matches
    for (size_t i = 0; i < original.entry_count; i++) {
        TEST_ASSERT_STREQ(readback.entries[i].path, original.entries[i].path);
        TEST_ASSERT_STREQ(readback.entries[i].sha, original.entries[i].sha);
        TEST_ASSERT_EQ(readback.entries[i].mode, original.entries[i].mode);
    }

    git_index_close_full(&readback);
    git_index_close_full(&original);
    git_repo_close(&repo);
}

// ============================================================================
// Index Locking Tests
// ============================================================================

// Test: Acquire lock successfully
TEST(index_io_lock_acquire) {
    GitRepository repo = {};
    if (!git_repo_open(&repo, INDEX_TEST_REPO_PATH)) {
        TEST_SKIP("Fixture repo not found");
    }

    bool locked = git_index_lock(&repo, 1000);
    TEST_ASSERT_TRUE(locked);

    git_index_unlock(&repo);
    git_repo_close(&repo);
}

// Test: Lock is released properly
TEST(index_io_lock_release) {
    GitRepository repo = {};
    if (!git_repo_open(&repo, INDEX_TEST_REPO_PATH)) {
        TEST_SKIP("Fixture repo not found");
    }

    // Acquire lock
    bool locked = git_index_lock(&repo, 1000);
    TEST_ASSERT_TRUE(locked);

    // Release lock
    git_index_unlock(&repo);

    // Should be able to acquire again immediately
    bool locked2 = git_index_lock(&repo, 100);
    TEST_ASSERT_TRUE(locked2);

    git_index_unlock(&repo);
    git_repo_close(&repo);
}

// Test: Lock with zero timeout fails if held
TEST(index_io_lock_contention_zero_timeout) {
    GitRepository repo = {};
    if (!git_repo_open(&repo, INDEX_TEST_REPO_PATH)) {
        TEST_SKIP("Fixture repo not found");
    }

    // Acquire lock
    bool locked1 = git_index_lock(&repo, 1000);
    if (!locked1) {
        git_repo_close(&repo);
        TEST_SKIP("Could not acquire initial lock");
    }

    // Second lock attempt with 0 timeout should fail
    // Note: Since we're in the same process and lock handle is global,
    // this actually tests whether the lock is already held check works
    // The actual implementation may need adjustment for this test

    git_index_unlock(&repo);
    git_repo_close(&repo);
}

// Test: Lock rejects null/invalid repo
TEST(index_io_lock_null_repo) {
    bool locked = git_index_lock(nullptr, 1000);
    TEST_ASSERT_FALSE(locked);
}

// Test: Lock rejects invalid repo
TEST(index_io_lock_invalid_repo) {
    GitRepository repo = {};
    repo.is_valid = false;

    bool locked = git_index_lock(&repo, 1000);
    TEST_ASSERT_FALSE(locked);
}

// Test: Unlock with null repo doesn't crash
TEST(index_io_unlock_null_repo) {
    // Should not crash
    git_index_unlock(nullptr);
    TEST_ASSERT_TRUE(true);  // If we get here, it didn't crash
}

// ============================================================================
// Index Manipulation Tests
// ============================================================================

// Test: Add path to index
TEST(index_io_add_new_file) {
    GitRepository repo = {};
    if (!git_repo_open(&repo, INDEX_TEST_REPO_PATH)) {
        TEST_SKIP("Fixture repo not found");
    }

    // Backup original index
    GitIndexFull original = {};
    if (!git_index_open_full(&repo, &original)) {
        git_repo_close(&repo);
        TEST_SKIP("Could not open original index");
    }

    // Try to add file1.txt (already tracked, should update)
    GitIndexFull index = {};
    if (!git_index_open_full(&repo, &index)) {
        git_index_close_full(&original);
        git_repo_close(&repo);
        TEST_SKIP("Could not open index for modification");
    }

    // Add existing file (should succeed)
    bool added = git_index_add_path(&repo, &index, "file1.txt");
    TEST_ASSERT_TRUE(added);

    git_index_close_full(&index);
    git_index_close_full(&original);
    git_repo_close(&repo);
}

// Test: Add nonexistent file fails
TEST(index_io_add_nonexistent_file) {
    GitRepository repo = {};
    if (!git_repo_open(&repo, INDEX_TEST_REPO_PATH)) {
        TEST_SKIP("Fixture repo not found");
    }

    GitIndexFull index = {};
    if (!git_index_open_full(&repo, &index)) {
        git_repo_close(&repo);
        TEST_SKIP("Could not open index");
    }

    // Try to add nonexistent file
    bool added = git_index_add_path(&repo, &index, "definitely_not_a_file.xyz");
    TEST_ASSERT_FALSE(added);

    git_index_close_full(&index);
    git_repo_close(&repo);
}

// Test: Add path computes correct SHA
TEST(index_io_add_computes_sha) {
    GitRepository repo = {};
    if (!git_repo_open(&repo, INDEX_TEST_REPO_PATH)) {
        TEST_SKIP("Fixture repo not found");
    }

    // Backup original
    GitIndexFull original = {};
    if (!git_index_open_full(&repo, &original)) {
        git_repo_close(&repo);
        TEST_SKIP("Could not open original index");
    }

    GitIndexFull index = {};
    if (!git_index_open_full(&repo, &index)) {
        git_index_close_full(&original);
        git_repo_close(&repo);
        TEST_SKIP("Could not open index");
    }

    // Add file1.txt and verify SHA matches known value
    bool added = git_index_add_path(&repo, &index, "file1.txt");
    TEST_ASSERT_TRUE(added);

    // Find the entry
    bool found = false;
    for (size_t i = 0; i < index.entry_count; i++) {
        if (strcmp(index.entries[i].path, "file1.txt") == 0) {
            TEST_ASSERT_STREQ(index.entries[i].sha, FIXTURE_FILE1_SHA);
            found = true;
            break;
        }
    }
    TEST_ASSERT_TRUE(found);

    git_index_close_full(&index);
    git_index_close_full(&original);
    git_repo_close(&repo);
}

// Test: Add path detects executable mode
TEST(index_io_add_detects_mode) {
    GitRepository repo = {};
    if (!git_repo_open(&repo, INDEX_TEST_REPO_PATH)) {
        TEST_SKIP("Fixture repo not found");
    }

    GitIndexFull index = {};
    if (!git_index_open_full(&repo, &index)) {
        git_repo_close(&repo);
        TEST_SKIP("Could not open index");
    }

    // script.sh is executable
    bool added = git_index_add_path(&repo, &index, "script.sh");
    TEST_ASSERT_TRUE(added);

    // Find the entry and verify mode
    bool found = false;
    for (size_t i = 0; i < index.entry_count; i++) {
        if (strcmp(index.entries[i].path, "script.sh") == 0) {
            // On Windows, executable detection may not work the same as Unix
            // Just verify mode is set to something reasonable
            TEST_ASSERT_TRUE(index.entries[i].mode == Git::MODE_FILE ||
                            index.entries[i].mode == Git::MODE_EXECUTABLE);
            found = true;
            break;
        }
    }
    TEST_ASSERT_TRUE(found);

    git_index_close_full(&index);
    git_repo_close(&repo);
}

// Test: Check if path exists in index
TEST(index_io_has_path) {
    GitRepository repo = {};
    if (!git_repo_open(&repo, INDEX_TEST_REPO_PATH)) {
        TEST_SKIP("Fixture repo not found");
    }

    GitIndex index = {};
    if (!git_index_open(&repo, &index)) {
        git_repo_close(&repo);
        TEST_SKIP("Could not open index");
    }

    // Check for existing file
    bool found = false;
    for (size_t i = 0; i < index.entry_count; i++) {
        if (strcmp(index.entries[i].path, "file1.txt") == 0) {
            found = true;
            break;
        }
    }
    TEST_ASSERT_TRUE(found);

    // Check for nonexistent file
    found = false;
    for (size_t i = 0; i < index.entry_count; i++) {
        if (strcmp(index.entries[i].path, "nonexistent.txt") == 0) {
            found = true;
            break;
        }
    }
    TEST_ASSERT_FALSE(found);

    git_index_close(&index);
    git_repo_close(&repo);
}

// Test: Get SHA for path using git_index_get_sha
TEST(index_io_get_sha_existing) {
    GitRepository repo = {};
    if (!git_repo_open(&repo, INDEX_TEST_REPO_PATH)) {
        TEST_SKIP("Fixture repo not found");
    }

    char sha[Git::SHA1_HEX_SIZE + 1];
    bool result = git_index_get_sha(&repo, "file1.txt", sha);

    TEST_ASSERT_TRUE(result);
    TEST_ASSERT_STREQ(sha, FIXTURE_FILE1_SHA);

    git_repo_close(&repo);
}

// Test: Get SHA for nonexistent path fails
TEST(index_io_get_sha_nonexistent) {
    GitRepository repo = {};
    if (!git_repo_open(&repo, INDEX_TEST_REPO_PATH)) {
        TEST_SKIP("Fixture repo not found");
    }

    char sha[Git::SHA1_HEX_SIZE + 1];
    bool result = git_index_get_sha(&repo, "nonexistent.txt", sha);

    TEST_ASSERT_FALSE(result);

    git_repo_close(&repo);
}

// Test: Get SHA for subdirectory file
TEST(index_io_get_sha_subdir) {
    GitRepository repo = {};
    if (!git_repo_open(&repo, INDEX_TEST_REPO_PATH)) {
        TEST_SKIP("Fixture repo not found");
    }

    char sha[Git::SHA1_HEX_SIZE + 1];
    bool result = git_index_get_sha(&repo, "subdir/file3.txt", sha);

    TEST_ASSERT_TRUE(result);
    TEST_ASSERT_STREQ(sha, FIXTURE_SUBDIR_FILE3_SHA);

    git_repo_close(&repo);
}

// Test: Remove path preserves other entries
TEST(index_io_remove_preserves_others) {
    // This test is similar to existing tests in test_index.cpp
    // but verifies the full workflow with real index operations

    GitIndexEntryFull* entries = new GitIndexEntryFull[3];
    memset(entries, 0, sizeof(GitIndexEntryFull) * 3);

    strcpy_s(entries[0].path, "aaa.txt");
    strcpy_s(entries[0].sha, FIXTURE_FILE1_SHA);
    entries[0].mode = Git::MODE_FILE;

    strcpy_s(entries[1].path, "bbb.txt");
    strcpy_s(entries[1].sha, FIXTURE_FILE2_SHA);
    entries[1].mode = Git::MODE_FILE;

    strcpy_s(entries[2].path, "ccc.txt");
    strcpy_s(entries[2].sha, FIXTURE_FEATURE_SHA);
    entries[2].mode = Git::MODE_FILE;

    GitIndexFull index = {};
    index.entries = entries;
    index.entry_count = 3;
    index.capacity = 3;

    // Remove middle entry
    bool removed = git_index_remove_path(&index, "bbb.txt");
    TEST_ASSERT_TRUE(removed);
    TEST_ASSERT_EQ(index.entry_count, (size_t)2);

    // Verify other entries unchanged
    TEST_ASSERT_STREQ(index.entries[0].path, "aaa.txt");
    TEST_ASSERT_STREQ(index.entries[0].sha, FIXTURE_FILE1_SHA);
    TEST_ASSERT_STREQ(index.entries[1].path, "ccc.txt");
    TEST_ASSERT_STREQ(index.entries[1].sha, FIXTURE_FEATURE_SHA);

    delete[] entries;
}

// Test: Null inputs handled gracefully
TEST(index_io_null_inputs) {
    GitRepository repo = {};
    repo.is_valid = true;
    strcpy_s(repo.path, "C:\\fake\\path");
    strcpy_s(repo.git_dir, "C:\\fake\\path\\.git");

    // Null index pointer
    TEST_ASSERT_FALSE(git_index_open(&repo, nullptr));
    TEST_ASSERT_FALSE(git_index_open_full(&repo, nullptr));

    // Null repo pointer
    GitIndex index = {};
    TEST_ASSERT_FALSE(git_index_open(nullptr, &index));

    GitIndexFull indexFull = {};
    TEST_ASSERT_FALSE(git_index_open_full(nullptr, &indexFull));

    // Null SHA output
    TEST_ASSERT_FALSE(git_index_get_sha(&repo, "file.txt", nullptr));

    // Null path
    char sha[Git::SHA1_HEX_SIZE + 1];
    TEST_ASSERT_FALSE(git_index_get_sha(&repo, nullptr, sha));
}

// Test: Conflict stages survive write/read roundtrip (flags bits 12-13)
TEST(index_io_stage_bits_roundtrip) {
    GitRepository repo = {};
    if (!git_repo_open(&repo, INDEX_TEST_REPO_PATH)) {
        TEST_SKIP("Fixture repo not available");
        return;
    }

    GitIndexFull original = {};
    if (!git_index_open_full(&repo, &original)) {
        git_repo_close(&repo);
        TEST_SKIP("Could not open fixture index");
        return;
    }

    // Build a synthetic conflicted index: stages 1,2,3 for conflict.txt + stage 0 for keep.txt
    GitIndexFull conflicted = {};
    conflicted.version = 2;
    conflicted.capacity = 4;
    conflicted.entry_count = 4;
    conflicted.entries = new GitIndexEntryFull[4];
    memset(conflicted.entries, 0, sizeof(GitIndexEntryFull) * 4);

    auto fill = [](GitIndexEntryFull* e, const char* path, uint8_t stage, const char* sha) {
        e->mode = Git::MODE_FILE;
        e->stage = stage;
        e->file_size = 10;
        e->mtime_sec = 1;
        strcpy_s(e->path, path);
        strcpy_s(e->sha, sha);
    };
    fill(&conflicted.entries[0], "conflict.txt", 1, FIXTURE_FILE1_SHA);
    fill(&conflicted.entries[1], "conflict.txt", 2, FIXTURE_FILE2_SHA);
    fill(&conflicted.entries[2], "conflict.txt", 3, FIXTURE_FEATURE_SHA);
    fill(&conflicted.entries[3], "keep.txt", 0, FIXTURE_FILE1_SHA);

    if (!git_index_lock(&repo, 3000)) {
        delete[] conflicted.entries;
        git_index_close_full(&original);
        git_repo_close(&repo);
        TEST_SKIP("Could not lock index");
        return;
    }

    bool wrote = git_index_write(&repo, &conflicted);
    TEST_ASSERT_TRUE(wrote);

    GitIndexFull readback = {};
    bool opened = git_index_open_full(&repo, &readback);
    TEST_ASSERT_TRUE(opened);
    TEST_ASSERT_EQ(readback.entry_count, (size_t)4);

    // Sorted by path then stage: conflict 1,2,3 then keep 0
    TEST_ASSERT_STREQ(readback.entries[0].path, "conflict.txt");
    TEST_ASSERT_EQ(readback.entries[0].stage, (uint8_t)1);
    TEST_ASSERT_STREQ(readback.entries[1].path, "conflict.txt");
    TEST_ASSERT_EQ(readback.entries[1].stage, (uint8_t)2);
    TEST_ASSERT_STREQ(readback.entries[2].path, "conflict.txt");
    TEST_ASSERT_EQ(readback.entries[2].stage, (uint8_t)3);
    TEST_ASSERT_STREQ(readback.entries[3].path, "keep.txt");
    TEST_ASSERT_EQ(readback.entries[3].stage, (uint8_t)0);

    // Restore fixture index
    git_index_write(&repo, &original);
    git_index_unlock(&repo);

    git_index_close_full(&readback);
    delete[] conflicted.entries;
    git_index_close_full(&original);
    git_repo_close(&repo);
}

// Test: git_index_add_path clears conflict stages and leaves a single stage-0 entry
// (exercises the full add_path path, not only remove_path)
TEST(index_io_add_path_resolves_conflict_stages) {
    GitRepository repo = {};
    if (!git_repo_open(&repo, INDEX_TEST_REPO_PATH)) {
        TEST_SKIP("Fixture repo not available");
        return;
    }

    GitIndexFull index = {};
    if (!git_index_open_full(&repo, &index)) {
        git_repo_close(&repo);
        TEST_SKIP("Could not open index");
        return;
    }

    // Replace file1.txt's stage-0 entry with synthetic stages 1/2/3 (conflicted)
    git_index_remove_path(&index, "file1.txt");
    if (index.entry_count + 3 > index.capacity) {
        git_index_close_full(&index);
        git_repo_close(&repo);
        TEST_SKIP("index capacity unexpected");
        return;
    }
    for (uint8_t stage = 1; stage <= 3; stage++) {
        GitIndexEntryFull* e = &index.entries[index.entry_count++];
        memset(e, 0, sizeof(*e));
        e->mode = Git::MODE_FILE;
        e->stage = stage;
        e->file_size = 10;
        strcpy_s(e->path, "file1.txt");
        strcpy_s(e->sha, stage == 1 ? FIXTURE_FILE1_SHA :
                         stage == 2 ? FIXTURE_FILE2_SHA : FIXTURE_FEATURE_SHA);
    }

    size_t stages_before = 0;
    for (size_t i = 0; i < index.entry_count; i++) {
        if (strcmp(index.entries[i].path, "file1.txt") == 0) stages_before++;
    }
    TEST_ASSERT_EQ(stages_before, (size_t)3);

    // Real worktree file exists in fixture — add_path should resolve to one stage-0
    bool added = git_index_add_path(&repo, &index, "file1.txt");
    TEST_ASSERT_TRUE(added);

    size_t stages_after = 0;
    uint8_t only_stage = 255;
    for (size_t i = 0; i < index.entry_count; i++) {
        if (strcmp(index.entries[i].path, "file1.txt") == 0) {
            stages_after++;
            only_stage = index.entries[i].stage;
        }
    }
    TEST_ASSERT_EQ(stages_after, (size_t)1);
    TEST_ASSERT_EQ(only_stage, (uint8_t)0);

    // Do not persist conflicted/repaired index to fixture
    git_index_close_full(&index);
    git_repo_close(&repo);
}

// Test: Corrupt index SHA trailer makes open fail; status must not report clean
TEST(index_io_corrupt_checksum_rejected) {
    GitRepository repo = {};
    if (!git_repo_open(&repo, INDEX_TEST_REPO_PATH)) {
        TEST_SKIP("Fixture repo not available");
        return;
    }

    wchar_t index_path[Git::MAX_PATH_LEN];
    wchar_t git_dir_wide[Git::MAX_PATH_LEN];
    utf8_to_wide_n(repo.git_dir, git_dir_wide, Git::MAX_PATH_LEN);
    wcscpy_s(index_path, git_dir_wide);
    wcscat_s(index_path, L"\\index");

    MemoryMap* mmap = mmap_open(index_path);
    if (!mmap || !mmap->data || mmap->size < 32) {
        mmap_close(mmap);
        git_repo_close(&repo);
        TEST_SKIP("No index file");
        return;
    }

    size_t size = mmap->size;
    uint8_t* good = new uint8_t[size];
    uint8_t* bad = new uint8_t[size];
    memcpy(good, mmap->data, size);
    memcpy(bad, mmap->data, size);
    mmap_close(mmap);

    bad[size - 1] ^= 0xFF;
    TEST_ASSERT_TRUE(write_file_atomic(index_path, bad, size));
    delete[] bad;

    GitIndexFull idx = {};
    TEST_ASSERT_FALSE(git_index_open_full(&repo, &idx));

    GitStatus status = {};
    TEST_ASSERT_FALSE(git_status_compute(&repo, &status));
    git_status_free(&status);

    // Restore fixture index
    TEST_ASSERT_TRUE(write_file_atomic(index_path, good, size));
    delete[] good;

    // Sanity: open works again
    TEST_ASSERT_TRUE(git_index_open_full(&repo, &idx));
    git_index_close_full(&idx);
    git_repo_close(&repo);
}

// Test: Mode preserved when re-staging an existing executable entry (Windows filemode)
TEST(index_io_add_preserves_executable_mode) {
    GitRepository repo = {};
    if (!git_repo_open(&repo, INDEX_TEST_REPO_PATH)) {
        TEST_SKIP("Fixture repo not available");
        return;
    }

    GitIndexFull index = {};
    if (!git_index_open_full(&repo, &index)) {
        git_repo_close(&repo);
        TEST_SKIP("Could not open index");
        return;
    }

    // Find script.sh (executable in fixture)
    int script_idx = -1;
    for (size_t i = 0; i < index.entry_count; i++) {
        if (strcmp(index.entries[i].path, "script.sh") == 0) {
            script_idx = (int)i;
            break;
        }
    }
    if (script_idx < 0) {
        git_index_close_full(&index);
        git_repo_close(&repo);
        TEST_SKIP("script.sh not in fixture index");
        return;
    }

    TEST_ASSERT_EQ(index.entries[script_idx].mode, Git::MODE_EXECUTABLE);

    if (!git_index_lock(&repo, 3000)) {
        git_index_close_full(&index);
        git_repo_close(&repo);
        TEST_SKIP("lock failed");
        return;
    }

    // Re-stage without content change should keep 100755
    bool added = git_index_add_path(&repo, &index, "script.sh");
    TEST_ASSERT_TRUE(added);

    bool found = false;
    for (size_t i = 0; i < index.entry_count; i++) {
        if (strcmp(index.entries[i].path, "script.sh") == 0 && index.entries[i].stage == 0) {
            TEST_ASSERT_EQ(index.entries[i].mode, Git::MODE_EXECUTABLE);
            found = true;
            break;
        }
    }
    TEST_ASSERT_TRUE(found);

    // Do not write back — release lock without persisting (or write original)
    git_index_unlock(&repo);
    git_index_close_full(&index);
    git_repo_close(&repo);
}
