// <AUTO-GENERATED TOC> DO NOT EDIT MANUALLY
// Table of Contents
//
// 1. sha1_to_hex() Tests (line 16)
// 2. hex_to_sha() Tests (line 79)
// 3. Round-trip Tests (line 145)
// 4. Integration with sha1_compute (line 186)
// 5. Edge Cases (line 214)
//
// </AUTO-GENERATED TOC>
// test_hex.cpp - Unit tests for hex/SHA conversion functions
// Tests sha1_to_hex() and hex_to_sha()

#include "test_harness.h"

// ============================================================================
// sha1_to_hex() Tests
// ============================================================================

TEST(sha1_to_hex_all_zeros) {
    uint8_t sha[20] = {0};
    char hex[41];

    sha1_to_hex(sha, hex);

    TEST_ASSERT_STREQ(hex, "0000000000000000000000000000000000000000");
}

TEST(sha1_to_hex_all_ff) {
    uint8_t sha[20];
    memset(sha, 0xFF, 20);
    char hex[41];

    sha1_to_hex(sha, hex);

    TEST_ASSERT_STREQ(hex, "ffffffffffffffffffffffffffffffffffffffff");
}

TEST(sha1_to_hex_known_value) {
    // SHA-1("abc") = a9993e364706816aba3e25717850c26c9cd0d89d
    uint8_t sha[20] = {
        0xa9, 0x99, 0x3e, 0x36, 0x47, 0x06, 0x81, 0x6a,
        0xba, 0x3e, 0x25, 0x71, 0x78, 0x50, 0xc2, 0x6c,
        0x9c, 0xd0, 0xd8, 0x9d
    };
    char hex[41];

    sha1_to_hex(sha, hex);

    TEST_ASSERT_STREQ(hex, "a9993e364706816aba3e25717850c26c9cd0d89d");
}

TEST(sha1_to_hex_produces_lowercase) {
    uint8_t sha[20] = {
        0xAB, 0xCD, 0xEF, 0x01, 0x23, 0x45, 0x67, 0x89,
        0xAB, 0xCD, 0xEF, 0x01, 0x23, 0x45, 0x67, 0x89,
        0xAB, 0xCD, 0xEF, 0x01
    };
    char hex[41];

    sha1_to_hex(sha, hex);

    // Should produce lowercase hex
    TEST_ASSERT_STREQ(hex, "abcdef0123456789abcdef0123456789abcdef01");
}

TEST(sha1_to_hex_null_terminated) {
    uint8_t sha[20] = {0};
    char hex[42];  // Extra byte to detect overwrite
    hex[40] = 'X';
    hex[41] = 'Y';

    sha1_to_hex(sha, hex);

    TEST_ASSERT_EQ(hex[40], '\0');  // Should be null terminated
    TEST_ASSERT_EQ(hex[41], 'Y');   // Should not overwrite beyond null
}

// ============================================================================
// hex_to_sha() Tests
// ============================================================================

TEST(hex_to_sha_all_zeros) {
    const char* hex = "0000000000000000000000000000000000000000";
    uint8_t sha[20];
    uint8_t expected[20] = {0};

    hex_to_sha(hex, sha);

    TEST_ASSERT_MEMEQ(sha, expected, 20);
}

TEST(hex_to_sha_all_ff) {
    const char* hex = "ffffffffffffffffffffffffffffffffffffffff";
    uint8_t sha[20];
    uint8_t expected[20];
    memset(expected, 0xFF, 20);

    hex_to_sha(hex, sha);

    TEST_ASSERT_MEMEQ(sha, expected, 20);
}

TEST(hex_to_sha_known_value) {
    const char* hex = "a9993e364706816aba3e25717850c26c9cd0d89d";
    uint8_t sha[20];
    uint8_t expected[20] = {
        0xa9, 0x99, 0x3e, 0x36, 0x47, 0x06, 0x81, 0x6a,
        0xba, 0x3e, 0x25, 0x71, 0x78, 0x50, 0xc2, 0x6c,
        0x9c, 0xd0, 0xd8, 0x9d
    };

    hex_to_sha(hex, sha);

    TEST_ASSERT_MEMEQ(sha, expected, 20);
}

TEST(hex_to_sha_uppercase_input) {
    // hex_to_sha should handle uppercase input
    const char* hex_upper = "A9993E364706816ABA3E25717850C26C9CD0D89D";
    const char* hex_lower = "a9993e364706816aba3e25717850c26c9cd0d89d";
    uint8_t sha_upper[20], sha_lower[20];

    hex_to_sha(hex_upper, sha_upper);
    hex_to_sha(hex_lower, sha_lower);

    TEST_ASSERT_MEMEQ(sha_upper, sha_lower, 20);
}

TEST(hex_to_sha_mixed_case) {
    // Mixed case should also work
    const char* hex = "A9993e36470681aABa3E257178500C6c9cD0d89D";
    uint8_t sha[20];
    uint8_t expected[20] = {
        0xa9, 0x99, 0x3e, 0x36, 0x47, 0x06, 0x81, 0xaa,
        0xba, 0x3e, 0x25, 0x71, 0x78, 0x50, 0x0c, 0x6c,
        0x9c, 0xd0, 0xd8, 0x9d
    };

    hex_to_sha(hex, sha);

    TEST_ASSERT_MEMEQ(sha, expected, 20);
}

// ============================================================================
// Round-trip Tests
// ============================================================================

TEST(hex_round_trip_zeros) {
    const char* original = "0000000000000000000000000000000000000000";
    uint8_t sha[20];
    char hex[41];

    hex_to_sha(original, sha);
    sha1_to_hex(sha, hex);

    TEST_ASSERT_STREQ(hex, original);
}

TEST(hex_round_trip_random) {
    const char* original = "deadbeef0123456789abcdef0123456789abcdef";
    uint8_t sha[20];
    char hex[41];

    hex_to_sha(original, sha);
    sha1_to_hex(sha, hex);

    TEST_ASSERT_STREQ(hex, original);
}

TEST(sha_round_trip) {
    uint8_t original[20] = {
        0x12, 0x34, 0x56, 0x78, 0x9a, 0xbc, 0xde, 0xf0,
        0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88,
        0x99, 0xaa, 0xbb, 0xcc
    };
    char hex[41];
    uint8_t result[20];

    sha1_to_hex(original, hex);
    hex_to_sha(hex, result);

    TEST_ASSERT_MEMEQ(result, original, 20);
}

// ============================================================================
// Integration with sha1_compute
// ============================================================================

TEST(sha1_compute_to_hex) {
    const char* input = "hello";
    uint8_t sha[20];
    char hex[41];

    sha1_compute(input, 5, sha);
    sha1_to_hex(sha, hex);

    // SHA-1("hello") = aaf4c61ddcc5e8a2dabede0f3b482cd9aea9434d
    TEST_ASSERT_STREQ(hex, "aaf4c61ddcc5e8a2dabede0f3b482cd9aea9434d");
}

TEST(sha1_verify_from_hex) {
    // Given known SHA, verify content produces it
    const char* expected_hex = "aaf4c61ddcc5e8a2dabede0f3b482cd9aea9434d";
    uint8_t expected_sha[20];
    hex_to_sha(expected_hex, expected_sha);

    uint8_t computed_sha[20];
    sha1_compute("hello", 5, computed_sha);

    TEST_ASSERT_MEMEQ(computed_sha, expected_sha, 20);
}

// ============================================================================
// Edge Cases
// ============================================================================

TEST(hex_conversion_each_nibble) {
    // Test each hex character is correctly handled
    const char* hex = "0123456789abcdef0123456789abcdef01234567";
    uint8_t sha[20];
    char result[41];

    hex_to_sha(hex, sha);
    sha1_to_hex(sha, result);

    TEST_ASSERT_STREQ(result, hex);
}

TEST(hex_first_nibble_only) {
    // Test when high nibble is 0 (e.g., 0x0F should be "0f")
    uint8_t sha[20];
    for (int i = 0; i < 20; i++) {
        sha[i] = (uint8_t)(i % 16);  // 0x00 through 0x0f
    }
    char hex[41];

    sha1_to_hex(sha, hex);

    // First bytes should be "00", "01", "02", etc.
    TEST_ASSERT_EQ(hex[0], '0');
    TEST_ASSERT_EQ(hex[1], '0');
    TEST_ASSERT_EQ(hex[2], '0');
    TEST_ASSERT_EQ(hex[3], '1');
}
