// <AUTO-GENERATED TOC> DO NOT EDIT MANUALLY
// Table of Contents
//
// 1. Section 1: Reflog Reading Tests (5 tests) (line 18)
// 2. Section 2: Reflog Appending Tests (4 tests) (line 112)
// 3. Section 3: Reflog Rewriting Tests (3 tests) (line 242)
//
// </AUTO-GENERATED TOC>
// test_reflog.cpp - Reflog operations tests (Phase 5.5a)
// Tests for reflog reading, appending, and rewriting
// Read-only tests use fixture repo directly; write tests use temp repo pattern
#include "test_harness.h"

// Path to fixture repository for read-only tests
// TEST_REPO_PATH is defined in test_integration.cpp
// g_write_test_repo, create_write_test_repo(), cleanup_write_test_repo() from test_write.cpp

// ============================================================================
// Section 1: Reflog Reading Tests (5 tests)
// ============================================================================

TEST(reflog_read_head_entries) {
    GitRepository repo = {};
    if (!git_repo_open(&repo, TEST_REPO_PATH)) {
        TEST_SKIP("Fixture repo not found");
    }

    ReflogEntry entries[32];
    size_t count = test_reflog_read(&repo, "HEAD", entries, 32);

    // Fixture has multiple entries in HEAD reflog
    TEST_ASSERT_TRUE(count > 0);

    git_repo_close(&repo);
}

TEST(reflog_read_order_newest_first) {
    GitRepository repo = {};
    if (!git_repo_open(&repo, TEST_REPO_PATH)) {
        TEST_SKIP("Fixture repo not found");
    }

    ReflogEntry entries[32];
    size_t count = test_reflog_read(&repo, "HEAD", entries, 32);
    TEST_ASSERT_TRUE(count >= 2);

    // Entries should be in reverse chronological order (newest first)
    // This means entries[0].timestamp >= entries[1].timestamp
    TEST_ASSERT_TRUE(entries[0].timestamp >= entries[1].timestamp);

    git_repo_close(&repo);
}

TEST(reflog_read_parses_sha) {
    GitRepository repo = {};
    if (!git_repo_open(&repo, TEST_REPO_PATH)) {
        TEST_SKIP("Fixture repo not found");
    }

    ReflogEntry entries[32];
    size_t count = test_reflog_read(&repo, "HEAD", entries, 32);
    TEST_ASSERT_TRUE(count > 0);

    // Verify old_sha and new_sha are 40 hex characters
    TEST_ASSERT_EQ(strlen(entries[0].new_sha), 40);

    // Verify all characters are hex
    for (size_t i = 0; i < 40; i++) {
        char c = entries[0].new_sha[i];
        bool is_hex = (c >= '0' && c <= '9') || (c >= 'a' && c <= 'f');
        TEST_ASSERT_TRUE(is_hex);
    }

    git_repo_close(&repo);
}

TEST(reflog_read_parses_author) {
    GitRepository repo = {};
    if (!git_repo_open(&repo, TEST_REPO_PATH)) {
        TEST_SKIP("Fixture repo not found");
    }

    ReflogEntry entries[32];
    size_t count = test_reflog_read(&repo, "HEAD", entries, 32);
    TEST_ASSERT_TRUE(count > 0);

    // Verify name and email are non-empty
    TEST_ASSERT_TRUE(strlen(entries[0].name) > 0);
    TEST_ASSERT_TRUE(strlen(entries[0].email) > 0);

    // Verify email contains @ (basic validation)
    TEST_ASSERT_TRUE(strchr(entries[0].email, '@') != nullptr);

    git_repo_close(&repo);
}

TEST(reflog_read_nonexistent_returns_zero) {
    GitRepository repo = {};
    if (!git_repo_open(&repo, TEST_REPO_PATH)) {
        TEST_SKIP("Fixture repo not found");
    }

    ReflogEntry entries[32];
    size_t count = test_reflog_read(&repo, "refs/heads/nonexistent_branch_xyz", entries, 32);

    // Non-existent ref should return 0 entries
    TEST_ASSERT_EQ(count, 0);

    git_repo_close(&repo);
}

// ============================================================================
// Section 2: Reflog Appending Tests (4 tests)
// ============================================================================

TEST(reflog_append_basic) {
    if (!create_write_test_repo()) {
        TEST_SKIP("Could not create temp test repo");
    }

    GitRepository repo = {};
    if (!git_repo_open(&repo, g_write_test_repo)) {
        cleanup_write_test_repo();
        TEST_SKIP("Could not open temp repo");
    }

    // Read current HEAD reflog count
    ReflogEntry entries_before[32];
    size_t count_before = test_reflog_read(&repo, "HEAD", entries_before, 32);

    // Append new entry (use repo.head_sha as the old_sha)
    bool result = test_reflog_append(&repo, "HEAD",
        repo.head_sha, "0123456789abcdef0123456789abcdef01234567",
        "Test User", "test@example.com", "test: Test message");

    TEST_ASSERT_TRUE(result);

    // Verify entry count increased
    ReflogEntry entries_after[32];
    size_t count_after = test_reflog_read(&repo, "HEAD", entries_after, 32);
    TEST_ASSERT_EQ(count_after, count_before + 1);

    // Verify new entry is at index 0 (newest)
    TEST_ASSERT_STREQ(entries_after[0].message, "test: Test message");

    git_repo_close(&repo);
    cleanup_write_test_repo();
}

TEST(reflog_append_creates_file) {
    if (!create_write_test_repo()) {
        TEST_SKIP("Could not create temp test repo");
    }

    GitRepository repo = {};
    if (!git_repo_open(&repo, g_write_test_repo)) {
        cleanup_write_test_repo();
        TEST_SKIP("Could not open temp repo");
    }

    // Append to a new ref that doesn't exist yet
    bool result = test_reflog_append(&repo, "refs/heads/new_test_branch",
        nullptr, "0123456789abcdef0123456789abcdef01234567",
        "Test User", "test@example.com", "branch: Created new branch");

    TEST_ASSERT_TRUE(result);

    // Verify we can read it back
    ReflogEntry entries[32];
    size_t count = test_reflog_read(&repo, "refs/heads/new_test_branch", entries, 32);
    TEST_ASSERT_EQ(count, 1);
    TEST_ASSERT_STREQ(entries[0].message, "branch: Created new branch");

    git_repo_close(&repo);
    cleanup_write_test_repo();
}

TEST(reflog_append_uses_zeros_for_first) {
    if (!create_write_test_repo()) {
        TEST_SKIP("Could not create temp test repo");
    }

    GitRepository repo = {};
    if (!git_repo_open(&repo, g_write_test_repo)) {
        cleanup_write_test_repo();
        TEST_SKIP("Could not open temp repo");
    }

    // Append with nullptr old_sha (should use 40 zeros)
    bool result = test_reflog_append(&repo, "refs/heads/zeros_test",
        nullptr, "abcdef0123456789abcdef0123456789abcdef01",
        "Test User", "test@example.com", "initial: First entry");

    TEST_ASSERT_TRUE(result);

    // Verify old_sha is 40 zeros
    ReflogEntry entries[32];
    size_t count = test_reflog_read(&repo, "refs/heads/zeros_test", entries, 32);
    TEST_ASSERT_EQ(count, 1);
    TEST_ASSERT_STREQ(entries[0].old_sha, "0000000000000000000000000000000000000000");

    git_repo_close(&repo);
    cleanup_write_test_repo();
}

TEST(reflog_append_null_inputs) {
    if (!create_write_test_repo()) {
        TEST_SKIP("Could not create temp test repo");
    }

    GitRepository repo = {};
    if (!git_repo_open(&repo, g_write_test_repo)) {
        cleanup_write_test_repo();
        TEST_SKIP("Could not open temp repo");
    }

    // Null repo should return false
    bool result1 = test_reflog_append(nullptr, "HEAD",
        "0000000000000000000000000000000000000000",
        "0123456789abcdef0123456789abcdef01234567",
        "Test User", "test@example.com", "test");
    TEST_ASSERT_FALSE(result1);

    // Null ref_name should return false
    bool result2 = test_reflog_append(&repo, nullptr,
        "0000000000000000000000000000000000000000",
        "0123456789abcdef0123456789abcdef01234567",
        "Test User", "test@example.com", "test");
    TEST_ASSERT_FALSE(result2);

    // Null new_sha should return false
    bool result3 = test_reflog_append(&repo, "HEAD",
        "0000000000000000000000000000000000000000",
        nullptr,
        "Test User", "test@example.com", "test");
    TEST_ASSERT_FALSE(result3);

    git_repo_close(&repo);
    cleanup_write_test_repo();
}

// ============================================================================
// Section 3: Reflog Rewriting Tests (3 tests)
// ============================================================================

TEST(reflog_rewrite_removes_entry) {
    if (!create_write_test_repo()) {
        TEST_SKIP("Could not create temp test repo");
    }

    GitRepository repo = {};
    if (!git_repo_open(&repo, g_write_test_repo)) {
        cleanup_write_test_repo();
        TEST_SKIP("Could not open temp repo");
    }

    // First, add a few entries to have something to remove
    test_reflog_append(&repo, "refs/heads/rewrite_test",
        nullptr, "1111111111111111111111111111111111111111",
        "Test User", "test@example.com", "entry 1");
    test_reflog_append(&repo, "refs/heads/rewrite_test",
        "1111111111111111111111111111111111111111", "2222222222222222222222222222222222222222",
        "Test User", "test@example.com", "entry 2");
    test_reflog_append(&repo, "refs/heads/rewrite_test",
        "2222222222222222222222222222222222222222", "3333333333333333333333333333333333333333",
        "Test User", "test@example.com", "entry 3");

    // Verify we have 3 entries
    ReflogEntry entries_before[32];
    size_t count_before = test_reflog_read(&repo, "refs/heads/rewrite_test", entries_before, 32);
    TEST_ASSERT_EQ(count_before, 3);

    // Remove the middle entry (index 1, which is "entry 2" in newest-first order)
    bool result = test_reflog_rewrite(&repo, "refs/heads/rewrite_test", 1);
    TEST_ASSERT_TRUE(result);

    // Verify count decreased
    ReflogEntry entries_after[32];
    size_t count_after = test_reflog_read(&repo, "refs/heads/rewrite_test", entries_after, 32);
    TEST_ASSERT_EQ(count_after, 2);

    // Verify entry 3 is still at index 0 and entry 1 is at index 1
    TEST_ASSERT_STREQ(entries_after[0].message, "entry 3");
    TEST_ASSERT_STREQ(entries_after[1].message, "entry 1");

    git_repo_close(&repo);
    cleanup_write_test_repo();
}

TEST(reflog_rewrite_remove_only_deletes_file) {
    if (!create_write_test_repo()) {
        TEST_SKIP("Could not create temp test repo");
    }

    GitRepository repo = {};
    if (!git_repo_open(&repo, g_write_test_repo)) {
        cleanup_write_test_repo();
        TEST_SKIP("Could not open temp repo");
    }

    // Add exactly one entry
    test_reflog_append(&repo, "refs/heads/single_entry_test",
        nullptr, "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcd",
        "Test User", "test@example.com", "only entry");

    // Verify we have 1 entry
    ReflogEntry entries[32];
    size_t count = test_reflog_read(&repo, "refs/heads/single_entry_test", entries, 32);
    TEST_ASSERT_EQ(count, 1);

    // Remove the only entry
    bool result = test_reflog_rewrite(&repo, "refs/heads/single_entry_test", 0);
    TEST_ASSERT_TRUE(result);

    // Verify reflog is now empty (file should be deleted)
    count = test_reflog_read(&repo, "refs/heads/single_entry_test", entries, 32);
    TEST_ASSERT_EQ(count, 0);

    git_repo_close(&repo);
    cleanup_write_test_repo();
}

TEST(reflog_rewrite_invalid_index) {
    if (!create_write_test_repo()) {
        TEST_SKIP("Could not create temp test repo");
    }

    GitRepository repo = {};
    if (!git_repo_open(&repo, g_write_test_repo)) {
        cleanup_write_test_repo();
        TEST_SKIP("Could not open temp repo");
    }

    // Add 2 entries
    test_reflog_append(&repo, "refs/heads/index_test",
        nullptr, "1111111111111111111111111111111111111111",
        "Test User", "test@example.com", "entry 1");
    test_reflog_append(&repo, "refs/heads/index_test",
        "1111111111111111111111111111111111111111", "2222222222222222222222222222222222222222",
        "Test User", "test@example.com", "entry 2");

    // Try to remove index 5 (out of bounds)
    bool result = test_reflog_rewrite(&repo, "refs/heads/index_test", 5);
    TEST_ASSERT_FALSE(result);

    // Verify original entries are intact
    ReflogEntry entries[32];
    size_t count = test_reflog_read(&repo, "refs/heads/index_test", entries, 32);
    TEST_ASSERT_EQ(count, 2);

    git_repo_close(&repo);
    cleanup_write_test_repo();
}
