import sys
import pathlib
from typing import List, Tuple, Optional

TOC_START = '// <AUTO-GENERATED TOC> DO NOT EDIT MANUALLY'
TOC_END = '// </AUTO-GENERATED TOC>'

def extract_sections(lines: List[str]) -> List[Tuple[str, int]]:
    sections: List[Tuple[str, int]] = []
    i = 0
    while i < len(lines) - 2:
        l1 = lines[i]
        l2 = lines[i + 1]
        l3 = lines[i + 2]

        # Must be comment lines
        if not (l1.startswith('//') and l2.startswith('//') and l3.startswith('//')):
            i += 1
            continue

        c1 = l1[2:].strip()
        c2 = l2[2:].strip()
        c3 = l3[2:].strip()

        # Separators must be identical, all '=', at least 10 chars
        if (len(c1) >= 10 and
            c1 == c3 and
            c1 == '=' * len(c1) and
            c2):  # title non-empty
            
            title = c2
            # Section starts at the first separator line (1-based in the code part)
            rel_section_line = i + 1
            sections.append((title, rel_section_line))
            
            i += 3  # Skip the three header lines
            continue
        
        i += 1
    
    return sections

def generate_toc_lines(sections: List[Tuple[str, int]], toc_line_count: int) -> List[str]:
    toc_lines: List[str] = [
        TOC_START,
        "// Table of Contents",
        "//"
    ]
    
    for idx, (title, rel_line) in enumerate(sections, 1):
        actual_line = rel_line + toc_line_count
        toc_lines.append(f"// {idx}. {title} (line {actual_line})")
    
    toc_lines += ["//", TOC_END]
    return toc_lines

def process_file(file_path: pathlib.Path):
    content = file_path.read_text(encoding='utf-8', errors='replace')
    content_lines = content.splitlines()
    
    # Find existing TOC block (exact match on marker lines)
    toc_start_idx: Optional[int] = None
    toc_end_idx: Optional[int] = None
    for j in range(len(content_lines)):
        if content_lines[j] == TOC_START:
            toc_start_idx = j
            for k in range(j + 1, len(content_lines)):
                if content_lines[k] == TOC_END:
                    toc_end_idx = k
                    break
            if toc_end_idx is not None:
                break
    
    has_existing = toc_start_idx is not None and toc_end_idx is not None and toc_end_idx > toc_start_idx
    
    # Code lines = everything except the old TOC block (if present)
    if has_existing:
        code_lines = content_lines[:toc_start_idx] + content_lines[toc_end_idx + 1:]
    else:
        code_lines = content_lines
    
    # Extract sections from the code part only
    sections = extract_sections(code_lines)
    n = len(sections)
    
    if n == 0:
        if has_existing:
            new_lines = code_lines
            file_path.write_text("\n".join(new_lines) + "\n", encoding='utf-8')
            print(f"Removed empty TOC from {file_path}")
        else:
            print(f"No sections and no TOC in {file_path}")
        return
    
    # TOC has exactly 5 fixed lines + n entry lines
    toc_line_count = 5 + n
    toc_lines = generate_toc_lines(sections, toc_line_count)
    
    # New file: TOC at the very top + code part
    new_lines = toc_lines + code_lines
    new_content = "\n".join(new_lines) + "\n"
    
    if new_content != content:
        file_path.write_text(new_content, encoding='utf-8')
        print(f"Updated TOC in {file_path}")
    else:
        print(f"No changes needed in {file_path}")

def main():
    if len(sys.argv) < 2:
        print("Usage: python generate_toc.py <path1> [path2 ...] (files or directories)")
        sys.exit(1)
    
    for arg in sys.argv[1:]:
        path = pathlib.Path(arg)
        if path.is_dir():
            for file in path.rglob("*.cpp"):
                process_file(file)
            for file in path.rglob("*.h"):
                process_file(file)
            for file in path.rglob("*.cc"):  # optional: add more extensions if needed
                process_file(file)
        elif path.is_file():
            process_file(path)

if __name__ == "__main__":
    main()