// <AUTO-GENERATED TOC> DO NOT EDIT MANUALLY
// Table of Contents
//
// 1. Test Support (only compiled in test builds) (line 32)
// 2. Diff Function Test Wrappers (line 46)
// 3. Pack File Test Wrappers (line 95)
// 4. Reflog Test Wrappers (line 143)
//
// </AUTO-GENERATED TOC>
// git_test.cpp
//
// Git test wrappers and test support functions
//
// This module contains test wrappers for internal functions and test isolation helpers.
// Only compiled when GITSMARTER_TEST_BUILD is defined.
//
// Public API (test builds only):
// - test_reset_index_lock_state()
// - test_split_lines(), test_free_lines(), test_line_hash()
// - test_myers_char_diff(), test_compress_to_spans()
// - test_diff_compute_lines(), test_free_diff_lines()
// - test_read_be32(), test_read_be64()
// - test_parse_pack_index(), test_parse_pack_header()
// - test_pack_index_find(), test_pack_index_get_offset()
// - test_read_pack_varint_size(), test_read_pack_offset_delta()
// - test_apply_delta()
// - test_reflog_read(), test_reflog_append(), test_reflog_rewrite()

#include "app.h"
#include "ui_theme.h"

// ============================================================================
// Test Support (only compiled in test builds)
// ============================================================================

#ifdef GITSMARTER_TEST_BUILD
// Reset all index lock slots for test isolation
void test_reset_index_lock_state() {
    EnterCriticalSection(&g_lock_slots_cs);
    for (size_t i = 0; i < MAX_LOCK_SLOTS; i++) {
        if (g_lock_slots[i].handle != INVALID_HANDLE_VALUE) {
            CloseHandle(g_lock_slots[i].handle);
            g_lock_slots[i].handle = INVALID_HANDLE_VALUE;
        }
        g_lock_slots[i].git_dir[0] = '\0';
    }
    LeaveCriticalSection(&g_lock_slots_cs);
}

// ============================================================================
// Diff Function Test Wrappers
// ============================================================================

// Line tokenization wrapper
char** test_split_lines(const char* text, size_t text_len, size_t* out_count) {
    return split_lines(text, text_len, out_count);
}

void test_free_lines(char** lines, size_t count) {
    if (!lines) return;
    for (size_t i = 0; i < count; i++) free(lines[i]);
    free(lines);
}

// Line hashing wrapper
uint32_t test_line_hash(const char* line) {
    return line_hash(line);
}

// Character-level diff (Myers algorithm) wrapper
bool test_myers_char_diff(const wchar_t* old_str, int old_len,
                          const wchar_t* new_str, int new_len,
                          bool* changed_old, bool* changed_new) {
    return myers_char_diff(old_str, old_len, new_str, new_len, changed_old, changed_new);
}

// Span compression wrapper
int test_compress_to_spans(const bool* changed, int len, DiffSpan* out_spans, int max_spans) {
    return compress_to_spans(changed, len, out_spans, max_spans);
}

// Full line diff (patience algorithm) wrapper
DiffLine* test_diff_compute_lines(char** old_lines, size_t old_count,
                                  char** new_lines, size_t new_count,
                                  size_t* out_line_count, int* out_additions, int* out_deletions) {
    return diff_compute_lines(old_lines, old_count, new_lines, new_count,
                              out_line_count, out_additions, out_deletions);
}

void test_free_diff_lines(DiffLine* lines, size_t count) {
    if (!lines) return;
    for (size_t i = 0; i < count; i++) {
        free(lines[i].content);
        free(lines[i].intra_spans);
    }
    free(lines);
}

// ============================================================================
// Pack File Test Wrappers
// ============================================================================

// Big-endian helpers
uint32_t test_read_be32(const void* ptr) {
    return read_be32(ptr);
}

uint64_t test_read_be64(const void* ptr) {
    return read_be64(ptr);
}

// Pack index parsing
bool test_parse_pack_index(GitPackIndex* idx, MemoryMap* mmap) {
    return parse_pack_index(idx, mmap);
}

// Pack header parsing
bool test_parse_pack_header(GitPackFile* pack, MemoryMap* mmap) {
    return parse_pack_header(pack, mmap);
}

// Index lookup
int64_t test_pack_index_find(const GitPackIndex* idx, const uint8_t* sha) {
    return pack_index_find(idx, sha);
}

uint64_t test_pack_index_get_offset(const GitPackIndex* idx, uint32_t obj_idx) {
    return pack_index_get_offset(idx, obj_idx);
}

// Varint decoding
uint64_t test_read_pack_varint_size(const uint8_t** ptr, int* type) {
    // Use a very large end pointer; tests pass in-bounds data.
    const uint8_t* end = *ptr + 16;
    return read_pack_varint_size(ptr, end, type);
}

uint64_t test_read_pack_offset_delta(const uint8_t** ptr) {
    const uint8_t* end = *ptr + 16;
    return read_pack_offset_delta(ptr, end);
}

// Delta application
char* test_apply_delta(const char* base, size_t base_size,
                       const uint8_t* delta, size_t delta_size,
                       size_t* result_size) {
    return apply_delta(base, base_size, delta, delta_size, result_size);
}

// ============================================================================
// Reflog Test Wrappers
// ============================================================================

size_t test_reflog_read(GitRepository* repo, const char* ref_name,
                        ReflogEntry* entries, size_t max_entries) {
    return git_reflog_read(repo, ref_name, entries, max_entries);
}

bool test_reflog_append(GitRepository* repo, const char* ref_name,
                        const char* old_sha, const char* new_sha,
                        const char* name, const char* email,
                        const char* message) {
    return git_reflog_append(repo, ref_name, old_sha, new_sha, name, email, message);
}

bool test_reflog_rewrite(GitRepository* repo, const char* ref_name, size_t remove_index) {
    return git_reflog_rewrite(repo, ref_name, remove_index);
}

// ============================================================================
// Path Containment Test Wrappers
// ============================================================================

bool test_git_is_safe_relative_path(const char* path) {
    return git_is_safe_relative_path(path);
}

bool test_git_make_worktree_path(GitRepository* repo, const char* rel_path,
                                 wchar_t* out_path, size_t out_size) {
    return git_make_worktree_path(repo, rel_path, out_path, out_size);
}

#endif
