// <AUTO-GENERATED TOC> DO NOT EDIT MANUALLY
// Table of Contents
//
// 1. Repository Initialization (for clone) (line 696)
// 2. Clone URL Utilities (line 870)
//
// </AUTO-GENERATED TOC>

#include "app.h"
#include "ui_theme.h"

// Forward declarations for pack file support
static char* read_pack_object_by_sha(GitRepository* repo, const char* sha,
                                      int* out_type, size_t* out_size);

static bool wcs_ends_with(const wchar_t* str, const wchar_t* suffix) {
    size_t slen = wcslen(str);
    size_t sflen = wcslen(suffix);
    if (sflen > slen) return false;
    return wcscmp(str + slen - sflen, suffix) == 0;
}

// packed_refs_lookup_sha / resolve_ref_sha live in git_objects.cpp (shared).

// Remove a single line from a packed-refs file whose ref-token equals full_ref.
// The packed-refs format is: "<40-char sha> <refname>\n" per line, with optional
// "^<sha>" peeled-tag lines and "#" comments. Returns true if a matching line
// was found and the file was rewritten; false otherwise.
//
// CRITICAL: Must load the *entire* file (mmap), never a fixed-size read_file buffer.
// Truncating before rewrite would delete every ref past the buffer boundary.
static bool packed_refs_remove_line(const wchar_t* packed_refs_path, const char* full_ref) {
    if (!packed_refs_path || !full_ref || !file_exists(packed_refs_path)) return false;

    MemoryMap* map = mmap_open(packed_refs_path);
    if (!map || !map->data || map->size == 0) {
        mmap_close(map);
        return false;
    }

    // Copy full contents then unmap so write_file_atomic can replace the file.
    size_t bytes_read = map->size;
    char* content = new (std::nothrow) char[bytes_read + 1];
    if (!content) {
        mmap_close(map);
        return false;
    }
    memcpy(content, map->data, bytes_read);
    content[bytes_read] = '\0';
    mmap_close(map);

    size_t full_ref_len = strlen(full_ref);
    bool rewrote = false;
    char* line_start = content;
    while (*line_start) {
        char* line_end = line_start;
        while (*line_end && *line_end != '\n' && *line_end != '\r') line_end++;
        char* line_eol = line_end;
        while (*line_eol == '\n' || *line_eol == '\r') line_eol++;

        char saved = *line_end;
        *line_end = '\0';
        bool match = false;
        if (line_start[0] != '#' && line_start[0] != '^') {
            char* space = strchr(line_start, ' ');
            if (space) {
                size_t token_len = (size_t)(line_end - (space + 1));
                match = token_len == full_ref_len &&
                        strncmp(space + 1, full_ref, full_ref_len) == 0;
            }
        }
        *line_end = saved;

        if (match) {
            // Drop an immediately following peeled-tag line (^sha) if present.
            char* remove_end = line_eol;
            if (*remove_end == '^') {
                while (*remove_end && *remove_end != '\n' && *remove_end != '\r') remove_end++;
                while (*remove_end == '\n' || *remove_end == '\r') remove_end++;
            }

            size_t removed = (size_t)(remove_end - line_start);
            size_t new_size = bytes_read - removed;
            char* new_content = new (std::nothrow) char[new_size + 1];
            if (new_content) {
                size_t prefix_len = (size_t)(line_start - content);
                memcpy(new_content, content, prefix_len);
                memcpy(new_content + prefix_len, remove_end, bytes_read - (size_t)(remove_end - content));
                new_content[new_size] = '\0';
                rewrote = write_file_atomic(packed_refs_path, new_content, new_size);
                delete[] new_content;
            }
            break;
        }
        line_start = line_eol;
    }

    delete[] content;
    return rewrote;
}

// Check if a directory is a git repository
bool git_is_repository(const wchar_t* path) {
    wchar_t git_dir[Git::MAX_PATH_LEN];
    make_path(git_dir, Git::MAX_PATH_LEN, path, L".git");

    // Check for .git directory
    if (dir_exists(git_dir)) {
        // Verify it has HEAD file
        wchar_t head_path[Git::MAX_PATH_LEN];
        make_path(head_path, Git::MAX_PATH_LEN, git_dir, L"HEAD");
        return file_exists(head_path);
    }

    // Check for .git file (worktree or submodule)
    if (file_exists(git_dir)) {
        return true;
    }

    return false;
}

// Forward declarations
static void git_attributes_cache_free(GitAttributeCache* cache);

// Open a git repository
bool git_repo_open(GitRepository* repo, const wchar_t* path) {
    if (!repo || !path) return false;

    memset(repo, 0, sizeof(GitRepository));

    if (!git_is_repository(path)) {
        return false;
    }

    // Store paths
    int result = WideCharToMultiByte(CP_UTF8, WC_ERR_INVALID_CHARS, path, -1,
                                     repo->path, Git::MAX_PATH_LEN, nullptr, nullptr);
    if (result == 0) {
        return false;  // Invalid UTF-8 conversion
    }

    wchar_t git_dir[Git::MAX_PATH_LEN];
    make_path(git_dir, Git::MAX_PATH_LEN, path, L".git");

    // Handle .git file (worktree/submodule) vs .git directory
    if (file_exists(git_dir)) {
        // .git is a file containing "gitdir: <path>"
        char content[1024];
        if (read_file(git_dir, content, sizeof(content)) > 0) {
            if (strncmp(content, "gitdir: ", 8) == 0) {
                char* gitdir_path = content + 8;
                strip_trailing(gitdir_path);
                if (gitdir_path[0] != '\0') {
                    if (gitdir_path[0] == '/') {
                        // Unix absolute path - translate separators
                        size_t glen = strlen(gitdir_path);
                        if (glen >= Git::MAX_PATH_LEN) {
                            LOG("git_repo_open: gitdir path too long");
                            return false;
                        }
                        for (size_t k = 0; k < glen; k++) {
                            repo->git_dir[k] = (gitdir_path[k] == '/') ? '\\' : gitdir_path[k];
                        }
                        repo->git_dir[glen] = '\0';
                    } else if (gitdir_path[1] == ':') {
                        // Windows absolute path (drive letter)
                        strcpy_s(repo->git_dir, gitdir_path);
                    } else {
                        // Relative path - prepend repo path
                        char abs_path[Git::MAX_PATH_LEN];
                        int snp = snprintf(abs_path, sizeof(abs_path), "%s\\%s", repo->path, gitdir_path);
                        if (snp < 0 || static_cast<size_t>(snp) >= sizeof(abs_path)) {
                            LOG("git_repo_open: gitdir absolute path too long");
                            return false;
                        }
                        strcpy_s(repo->git_dir, abs_path);
                    }
                }
            }
        }
        if (repo->git_dir[0] == '\0') {
            LOG("git_repo_open: .git file missing or has no valid gitdir path");
            return false;
        }
    } else {
        result = WideCharToMultiByte(CP_UTF8, WC_ERR_INVALID_CHARS, git_dir, -1,
                                     repo->git_dir, Git::MAX_PATH_LEN, nullptr, nullptr);
        if (result == 0) {
            return false;  // Invalid UTF-8 conversion
        }
    }

    repo->is_valid = true;

    // Read HEAD
    git_read_head(repo);

    // Load pack files
    git_load_packs(repo);

    // Load configuration
    git_config_load(repo, &repo->config);
    LOG("Config loaded: autocrlf=%d", (int)repo->config.core_autocrlf);

    // Initialize .gitattributes cache
    repo->attr_cache = new GitAttributeCache();
    memset(repo->attr_cache, 0, sizeof(GitAttributeCache));

    return true;
}

// Close repository (cleanup)
void git_repo_close(GitRepository* repo) {
    if (repo) {
        git_unload_packs(repo);
        if (repo->attr_cache) {
            git_attributes_cache_free(repo->attr_cache);
            delete repo->attr_cache;
            repo->attr_cache = nullptr;
        }
        memset(repo, 0, sizeof(GitRepository));
    }
}

// Read HEAD to get current branch/commit
bool git_read_head(GitRepository* repo) {
    if (!repo || !repo->is_valid) return false;

    repo->head_sha[0] = '\0';
    repo->head_ref[0] = '\0';
    repo->head_detached = false;

    wchar_t head_path[Git::MAX_PATH_LEN];
    wchar_t git_dir_wide[Git::MAX_PATH_LEN];
    utf8_to_wide_n(repo->git_dir, git_dir_wide, Git::MAX_PATH_LEN);
    make_path(head_path, Git::MAX_PATH_LEN, git_dir_wide, L"HEAD");

    char head_content[256];
    if (read_file(head_path, head_content, sizeof(head_content)) == 0) {
        return false;
    }

    strip_trailing(head_content);

    // Check if HEAD is a symbolic ref (branch) or direct SHA
    if (strncmp(head_content, "ref: ", 5) == 0) {
        // Symbolic reference - extract branch name
        const char* ref_path = head_content + 5;

        if (strncmp(ref_path, "refs/heads/", 11) == 0) {
            repo->head_detached = false;
            strcpy_s(repo->head_ref, ref_path + 11);
        } else {
            // Ref is not under refs/heads/ (e.g. refs/tags/, MERGE_HEAD, etc.)
            repo->head_detached = true;
            strcpy_s(repo->head_ref, ref_path);
        }

        // Loose ref first, then packed-refs via mmap (no 32KB cap)
        resolve_ref_sha(git_dir_wide, ref_path, repo->head_sha);
        // Empty head_sha is valid for unborn branch (ref points to missing tip)
    } else {
        // Direct SHA (detached HEAD)
        repo->head_detached = true;
        strcpy_s(repo->head_ref, "HEAD");
        strncpy_s(repo->head_sha, head_content, Git::SHA1_HEX_SIZE);
        repo->head_sha[Git::SHA1_HEX_SIZE] = '\0';
    }

    return true;
}

// Helper: Enumerate files in directory recursively
static size_t enumerate_refs_dir(const wchar_t* base_dir, const wchar_t* subdir,
                                  GitRef* refs, size_t max_refs, size_t count,
                                  GitRef::Type type, const char* prefix) {
    wchar_t search_path[Git::MAX_PATH_LEN];
    make_path(search_path, Git::MAX_PATH_LEN, base_dir, subdir);
    wcscat_s(search_path, L"\\*");

    WIN32_FIND_DATAW find_data;
    HANDLE find_handle = FindFirstFileW(search_path, &find_data);

    if (find_handle == INVALID_HANDLE_VALUE) {
        return count;
    }

    do {
        if (wcscmp(find_data.cFileName, L".") == 0 || wcscmp(find_data.cFileName, L"..") == 0) {
            continue;
        }

        wchar_t full_path[Git::MAX_PATH_LEN];
        wchar_t sub_path[Git::MAX_PATH_LEN];
        make_path(sub_path, Git::MAX_PATH_LEN, subdir, find_data.cFileName);
        make_path(full_path, Git::MAX_PATH_LEN, base_dir, sub_path);

        if (find_data.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY) {
            // Recurse into subdirectory
            char new_prefix[Git::MAX_REF_NAME];
            char filename_utf8[256];
            if (WideCharToMultiByte(CP_UTF8, WC_ERR_INVALID_CHARS, find_data.cFileName, -1,
                                   filename_utf8, 256, nullptr, nullptr) == 0) {
                continue;  // Skip ref with invalid filename
            }
            snprintf(new_prefix, sizeof(new_prefix), "%s%s/", prefix, filename_utf8);
            count = enumerate_refs_dir(base_dir, sub_path, refs, max_refs, count, type, new_prefix);
        } else {
            // This is a ref file
            if (count < max_refs) {
                GitRef* ref = &refs[count];
                ref->type = type;

                // Build ref name
                char filename_utf8[256];
                if (WideCharToMultiByte(CP_UTF8, WC_ERR_INVALID_CHARS, find_data.cFileName, -1,
                                       filename_utf8, 256, nullptr, nullptr) == 0) {
                    continue;  // Skip ref with invalid filename
                }
                snprintf(ref->name, Git::MAX_REF_NAME, "%s%s", prefix, filename_utf8);

                // Read SHA from file
                char sha_content[64];
                if (read_file(full_path, sha_content, sizeof(sha_content)) > 0) {
                    strip_trailing(sha_content);
                    // Skip symbolic refs (e.g., "ref: refs/remotes/origin/main")
                    if (strncmp(sha_content, "ref: ", 5) == 0) {
                        continue;
                    }
                    strncpy_s(ref->sha, sha_content, Git::SHA1_HEX_SIZE);
                    ref->sha[Git::SHA1_HEX_SIZE] = '\0';
                    count++;
                }
            }
        }
    } while (FindNextFileW(find_handle, &find_data) && count < max_refs);

    FindClose(find_handle);
    return count;
}

// Check if a ref name already exists in the refs array
static bool ref_exists(const GitRef* refs, size_t count, const char* name, GitRef::Type type) {
    for (size_t i = 0; i < count; i++) {
        if (refs[i].type == type && strcmp(refs[i].name, name) == 0) {
            return true;
        }
    }
    return false;
}

// Parse packed-refs file and add refs not already present as loose refs
// Format:
//   # pack-refs with: peeled fully-peeled sorted   (header comment)
//   <40-char-sha> <refname>                         (ref entry)
//   ^<40-char-sha>                                  (peeled tag, skip)
static size_t parse_packed_refs(const wchar_t* git_dir, GitRef* refs, size_t max_refs, size_t count) {
    wchar_t packed_refs_path[Git::MAX_PATH_LEN];
    make_path(packed_refs_path, Git::MAX_PATH_LEN, git_dir, L"packed-refs");

    MemoryMap* packed_map = mmap_open(packed_refs_path);
    if (!packed_map || !packed_map->data || packed_map->size == 0) {
        mmap_close(packed_map);
        return count; // No packed-refs file or empty
    }

    size_t bytes_read = packed_map->size;
    char* content = new (std::nothrow) char[bytes_read + 1];
    if (!content) {
        mmap_close(packed_map);
        return count;
    }
    memcpy(content, packed_map->data, bytes_read);
    mmap_close(packed_map);
    content[bytes_read] = '\0';

    // Parse line by line
    char* line_start = content;
    while (*line_start && count < max_refs) {
        // Find end of line
        char* line_end = line_start;
        while (*line_end && *line_end != '\n' && *line_end != '\r') {
            line_end++;
        }

        // Null-terminate this line
        char saved = *line_end;
        *line_end = '\0';

        // Skip empty lines, comments (#), and peeled refs (^)
        if (line_start[0] != '\0' && line_start[0] != '#' && line_start[0] != '^') {
            // Parse: "<sha> <refname>"
            // SHA is exactly 40 hex chars, followed by space, then refname
            if (strlen(line_start) > 42 && line_start[40] == ' ') {
                char sha[Git::SHA1_HEX_SIZE + 1];
                strncpy_s(sha, line_start, Git::SHA1_HEX_SIZE);
                sha[Git::SHA1_HEX_SIZE] = '\0';

                const char* refname = line_start + 41;

                // Determine ref type and extract short name
                GitRef::Type type;
                const char* short_name = nullptr;

                if (strncmp(refname, "refs/heads/", 11) == 0) {
                    type = GitRef::Type::Local;
                    short_name = refname + 11;
                } else if (strncmp(refname, "refs/remotes/", 13) == 0) {
                    type = GitRef::Type::Remote;
                    short_name = refname + 13;
                } else if (strncmp(refname, "refs/tags/", 10) == 0) {
                    type = GitRef::Type::Tag;
                    short_name = refname + 10;
                } else {
                    // Unknown ref type, skip
                    *line_end = saved;
                    line_start = line_end;
                    if (*line_start == '\r') line_start++;
                    if (*line_start == '\n') line_start++;
                    continue;
                }

                // Only add if not already present as a loose ref (loose takes precedence)
                if (!ref_exists(refs, count, short_name, type)) {
                    GitRef* ref = &refs[count];
                    ref->type = type;
                    strncpy_s(ref->name, short_name, Git::MAX_REF_NAME - 1);
                    ref->name[Git::MAX_REF_NAME - 1] = '\0';
                    strncpy_s(ref->sha, sha, Git::SHA1_HEX_SIZE);
                    ref->sha[Git::SHA1_HEX_SIZE] = '\0';
                    count++;
                }
            }
        }

        // Restore and move to next line
        *line_end = saved;
        line_start = line_end;
        if (*line_start == '\r') line_start++;
        if (*line_start == '\n') line_start++;
    }

    delete[] content;
    return count;
}

// List all refs (branches, tags, remotes)
size_t git_list_refs(GitRepository* repo, GitRef* refs, size_t max_refs) {
    if (!repo || !repo->is_valid || !refs || max_refs == 0) return 0;

    size_t count = 0;

    wchar_t git_dir_wide[Git::MAX_PATH_LEN];
    utf8_to_wide_n(repo->git_dir, git_dir_wide, Git::MAX_PATH_LEN);

    // Enumerate loose refs first (they take precedence over packed-refs)

    // Enumerate refs/heads (local branches)
    wchar_t refs_heads[Git::MAX_PATH_LEN];
    make_path(refs_heads, Git::MAX_PATH_LEN, git_dir_wide, L"refs\\heads");
    if (dir_exists(refs_heads)) {
        count = enumerate_refs_dir(git_dir_wide, L"refs\\heads", refs, max_refs, count, GitRef::Type::Local, "");
    }

    // Enumerate refs/remotes (remote tracking branches)
    wchar_t refs_remotes[Git::MAX_PATH_LEN];
    make_path(refs_remotes, Git::MAX_PATH_LEN, git_dir_wide, L"refs\\remotes");
    if (dir_exists(refs_remotes)) {
        count = enumerate_refs_dir(git_dir_wide, L"refs\\remotes", refs, max_refs, count, GitRef::Type::Remote, "");
    }

    // Enumerate refs/tags
    wchar_t refs_tags[Git::MAX_PATH_LEN];
    make_path(refs_tags, Git::MAX_PATH_LEN, git_dir_wide, L"refs\\tags");
    if (dir_exists(refs_tags)) {
        count = enumerate_refs_dir(git_dir_wide, L"refs\\tags", refs, max_refs, count, GitRef::Type::Tag, "");
    }

    // Parse packed-refs for any refs not present as loose files
    count = parse_packed_refs(git_dir_wide, refs, max_refs, count);

    return count;
}

// Validate a branch name according to git-check-ref-format rules
// Returns true if valid, false otherwise with error message in error_out
bool git_is_valid_branch_name(const char* name, char* error_out, size_t error_size) {
    if (!name || name[0] == '\0') {
        if (error_out) snprintf(error_out, error_size, "Branch name cannot be empty");
        return false;
    }

    size_t len = strlen(name);

    // Check max length
    if (len >= Git::MAX_REF_NAME) {
        if (error_out) snprintf(error_out, error_size, "Branch name too long (max %d characters)", static_cast<int>(Git::MAX_REF_NAME) - 1);
        return false;
    }

    // Check reserved name
    if (_stricmp(name, "HEAD") == 0) {
        if (error_out) snprintf(error_out, error_size, "'HEAD' is a reserved name");
        return false;
    }

    // Check for leading/trailing slashes
    if (name[0] == '/') {
        if (error_out) snprintf(error_out, error_size, "Branch name cannot start with '/'");
        return false;
    }
    if (name[len - 1] == '/') {
        if (error_out) snprintf(error_out, error_size, "Branch name cannot end with '/'");
        return false;
    }

    // Check for leading/trailing dots
    if (name[0] == '.') {
        if (error_out) snprintf(error_out, error_size, "Branch name cannot start with '.'");
        return false;
    }
    if (name[len - 1] == '.') {
        if (error_out) snprintf(error_out, error_size, "Branch name cannot end with '.'");
        return false;
    }

    // Check for .lock suffix (case-insensitive)
    if (len >= 5 && _stricmp(name + len - 5, ".lock") == 0) {
        if (error_out) snprintf(error_out, error_size, "Branch name cannot end with '.lock'");
        return false;
    }

    // Check for @{ sequence
    for (size_t i = 0; i + 1 < len; i++) {
        if (name[i] == '@' && name[i + 1] == '{') {
            if (error_out) snprintf(error_out, error_size, "Branch name cannot contain '@{'");
            return false;
        }
    }

    // Scan for invalid characters and patterns
    bool prev_was_dot = false;
    bool prev_was_slash = false;

    for (size_t i = 0; i < len; i++) {
        unsigned char ch = static_cast<unsigned char>(name[i]);

        // Reject ASCII control characters and DEL
        if (ch < 0x20 || ch == 0x7F) {
            if (error_out) snprintf(error_out, error_size, "Branch name contains control characters");
            return false;
        }

        // Reject space
        if (ch == ' ') {
            if (error_out) snprintf(error_out, error_size, "Branch name cannot contain spaces");
            return false;
        }

        // Reject special characters: ~ ^ : ? * [ @ backslash
        if (ch == '~' || ch == '^' || ch == ':' || ch == '?' ||
            ch == '*' || ch == '[' || ch == '@' || ch == '\\') {
            if (error_out) snprintf(error_out, error_size, "Branch name contains invalid character '%c'", ch);
            return false;
        }

        // Check for consecutive dots
        if (ch == '.') {
            if (prev_was_dot) {
                if (error_out) snprintf(error_out, error_size, "Branch name cannot contain '..'");
                return false;
            }
            prev_was_dot = true;
        } else {
            prev_was_dot = false;
        }

        // Check for consecutive slashes and component rules
        if (ch == '/') {
            if (prev_was_slash) {
                if (error_out) snprintf(error_out, error_size, "Branch name cannot contain '//'");
                return false;
            }
            // Check if next component starts with dot
            if (i + 1 < len && name[i + 1] == '.') {
                if (error_out) snprintf(error_out, error_size, "Path component cannot start with '.'");
                return false;
            }
            prev_was_slash = true;
        } else {
            prev_was_slash = false;
        }
    }

    // Clear error on success
    if (error_out && error_size > 0) error_out[0] = '\0';
    return true;
}

// Check if a branch already exists (loose ref or packed-refs)
bool git_branch_exists(GitRepository* repo, const char* branch_name) {
    if (!repo || !repo->is_valid || !branch_name) return false;

    wchar_t git_dir_wide[Git::MAX_PATH_LEN];
    utf8_to_wide_n(repo->git_dir, git_dir_wide, Git::MAX_PATH_LEN);

    // Check loose ref: .git/refs/heads/<branch_name>
    wchar_t ref_path[Git::MAX_PATH_LEN];
    make_path(ref_path, Git::MAX_PATH_LEN, git_dir_wide, L"refs\\heads");

    wchar_t branch_wide[Git::MAX_REF_NAME];
    utf8_to_wide_n(branch_name, branch_wide, Git::MAX_REF_NAME);

    // Convert forward slashes to backslashes for Windows path
    for (wchar_t* p = branch_wide; *p; p++) {
        if (*p == L'/') *p = L'\\';
    }

    wchar_t full_path[Git::MAX_PATH_LEN];
    make_path(full_path, Git::MAX_PATH_LEN, ref_path, branch_wide);

    if (file_exists(full_path)) {
        return true;
    }

    // Check packed-refs (full file via mmap — no 256KB truncation)
    char full_ref[Git::MAX_REF_NAME + 16];
    snprintf(full_ref, sizeof(full_ref), "refs/heads/%s", branch_name);
    char sha[Git::SHA1_HEX_SIZE + 1];
    return packed_refs_lookup_sha(git_dir_wide, full_ref, sha);
}

// Create a new branch pointing to a specific commit
// If target_sha is empty, uses current HEAD
// If force is true, overwrites existing branch
bool git_branch_create(GitRepository* repo, const char* branch_name, const char* target_sha,
                       bool force, char* error_out, size_t error_size) {
    if (!repo || !repo->is_valid) {
        if (error_out) snprintf(error_out, error_size, "Invalid repository");
        return false;
    }

    if (!branch_name || branch_name[0] == '\0') {
        if (error_out) snprintf(error_out, error_size, "Branch name cannot be empty");
        return false;
    }

    // Validate branch name
    if (!git_is_valid_branch_name(branch_name, error_out, error_size)) {
        return false;
    }

    // Determine target SHA
    char target[Git::SHA1_HEX_SIZE + 1] = {};

    if (target_sha && target_sha[0] != '\0') {
        // Validate provided SHA exists
        GitCommit check = {};
        if (!git_read_commit(repo, target_sha, &check)) {
            if (error_out) snprintf(error_out, error_size, "Target commit not found: %.7s", target_sha);
            return false;
        }
        strncpy_s(target, target_sha, Git::SHA1_HEX_SIZE);
    } else {
        // Use current HEAD
        if (repo->head_sha[0] == '\0') {
            if (error_out) snprintf(error_out, error_size, "Repository has no commits yet");
            return false;
        }
        strncpy_s(target, repo->head_sha, Git::SHA1_HEX_SIZE);
    }

    // Check for existing branch
    if (!force && git_branch_exists(repo, branch_name)) {
        if (error_out) snprintf(error_out, error_size, "Branch '%s' already exists", branch_name);
        return false;
    }

    // Build full ref path
    char ref_path[Git::MAX_REF_NAME + 16];
    snprintf(ref_path, sizeof(ref_path), "refs/heads/%s", branch_name);

    // Create the ref (git_ref_update handles directory creation and atomic write)
    if (!git_ref_update(repo, ref_path, target)) {
        if (error_out) snprintf(error_out, error_size, "Failed to create branch reference");
        return false;
    }

    LOG("git_branch_create: created '%s' -> %.7s", branch_name, target);

    if (error_out && error_size > 0) error_out[0] = '\0';
    return true;
}

// ============================================================================
// Repository Initialization (for clone)
// ============================================================================

// Initialize a new empty git repository at the specified path
// Creates .git directory structure, HEAD file, and initial config
bool git_repo_init(const wchar_t* path) {
    if (!path || path[0] == L'\0') return false;
    
    // Create the main repository directory if it doesn't exist
    if (!dir_exists(path)) {
        if (!CreateDirectoryW(path, nullptr)) {
            DWORD err = GetLastError();
            if (err != ERROR_ALREADY_EXISTS) {
                LOG("git_repo_init: failed to create directory, error=%lu", err);
                return false;
            }
        }
    }
    
    // Create .git directory
    wchar_t git_dir[Git::MAX_PATH_LEN];
    make_path(git_dir, Git::MAX_PATH_LEN, path, L".git");
    if (!CreateDirectoryW(git_dir, nullptr)) {
        DWORD err = GetLastError();
        if (err != ERROR_ALREADY_EXISTS) {
            LOG("git_repo_init: failed to create .git directory, error=%lu", err);
            return false;
        }
    }
    
    // Create subdirectories
    wchar_t subdir[Git::MAX_PATH_LEN];
    
    // refs/
    make_path(subdir, Git::MAX_PATH_LEN, git_dir, L"refs");
    if (!ensure_directory(subdir)) return false;
    
    // refs/heads/
    make_path(subdir, Git::MAX_PATH_LEN, git_dir, L"refs\\heads");
    if (!ensure_directory(subdir)) return false;
    
    // refs/tags/
    make_path(subdir, Git::MAX_PATH_LEN, git_dir, L"refs\\tags");
    if (!ensure_directory(subdir)) return false;
    
    // refs/remotes/
    make_path(subdir, Git::MAX_PATH_LEN, git_dir, L"refs\\remotes");
    if (!ensure_directory(subdir)) return false;
    
    // objects/
    make_path(subdir, Git::MAX_PATH_LEN, git_dir, L"objects");
    if (!ensure_directory(subdir)) return false;
    
    // objects/pack/
    make_path(subdir, Git::MAX_PATH_LEN, git_dir, L"objects\\pack");
    if (!ensure_directory(subdir)) return false;
    
    // objects/info/
    make_path(subdir, Git::MAX_PATH_LEN, git_dir, L"objects\\info");
    if (!ensure_directory(subdir)) return false;
    
    // Create HEAD file pointing to refs/heads/main
    wchar_t head_path[Git::MAX_PATH_LEN];
    make_path(head_path, Git::MAX_PATH_LEN, git_dir, L"HEAD");
    const char head_content[] = "ref: refs/heads/main\n";
    if (!write_file_atomic(head_path, head_content, strlen(head_content))) {
        LOG("git_repo_init: failed to write HEAD file");
        return false;
    }
    
    // Create initial config file
    wchar_t config_path[Git::MAX_PATH_LEN];
    make_path(config_path, Git::MAX_PATH_LEN, git_dir, L"config");
    const char config_content[] =
        "[core]\n"
        "\trepositoryformatversion = 0\n"
        "\tfilemode = false\n"
        "\tbare = false\n"
        "\tlogallrefupdates = true\n"
        "\tsymlinks = false\n"
        "\tignorecase = true\n";
    if (!write_file_atomic(config_path, config_content, strlen(config_content))) {
        LOG("git_repo_init: failed to write config file");
        return false;
    }
    
    LOG("git_repo_init: initialized repository at %ls", path);
    return true;
}

// Add a remote to an existing repository
// Creates [remote "name"] section in config with url and fetch refspec
bool git_remote_add(GitRepository* repo, const char* name, const char* url) {
    if (!repo || !repo->is_valid) return false;
    if (!name || name[0] == '\0') return false;
    if (!url || url[0] == '\0') return false;
    
    // Read existing config
    wchar_t git_dir_wide[Git::MAX_PATH_LEN];
    utf8_to_wide_n(repo->git_dir, git_dir_wide, Git::MAX_PATH_LEN);
    
    wchar_t config_path[Git::MAX_PATH_LEN];
    make_path(config_path, Git::MAX_PATH_LEN, git_dir_wide, L"config");
    
    // Read existing config content
    constexpr size_t CONFIG_BUF_SIZE = 65536;
    char* existing_config = new (std::nothrow) char[CONFIG_BUF_SIZE];
    if (!existing_config) return false;
    existing_config[0] = '\0';
    size_t existing_len = read_file(config_path, existing_config, CONFIG_BUF_SIZE - 1);
    if (existing_len == CONFIG_BUF_SIZE - 1) {
        LOG("git_remote_add: config file too large (>= %zu bytes)", CONFIG_BUF_SIZE);
        delete[] existing_config;
        return false;
    }
    existing_config[existing_len] = '\0';

    // Build new remote section
    char remote_section[1024];
    snprintf(remote_section, sizeof(remote_section),
        "\n[remote \"%s\"]\n"
        "\turl = %s\n"
        "\tfetch = +refs/heads/*:refs/remotes/%s/*\n",
        name, url, name);

    // Append to config
    constexpr size_t NEW_CONFIG_BUF_SIZE = 131072;
    char* new_config = new (std::nothrow) char[NEW_CONFIG_BUF_SIZE];
    if (!new_config) {
        delete[] existing_config;
        return false;
    }
    int new_len = snprintf(new_config, NEW_CONFIG_BUF_SIZE, "%s%s", existing_config, remote_section);
    delete[] existing_config;

    if (new_len < 0) {
        LOG("git_remote_add: snprintf failed");
        delete[] new_config;
        return false;
    }
    if (static_cast<size_t>(new_len) >= NEW_CONFIG_BUF_SIZE) {
        LOG("git_remote_add: config too large (would-be %d bytes)", new_len);
        delete[] new_config;
        return false;
    }

    if (!write_file_atomic(config_path, new_config, (size_t)new_len)) {
        LOG("git_remote_add: failed to write config");
        delete[] new_config;
        return false;
    }
    delete[] new_config;
    
    // Create refs/remotes/<name>/ directory
    wchar_t remote_refs_dir[Git::MAX_PATH_LEN];
    make_path(remote_refs_dir, Git::MAX_PATH_LEN, git_dir_wide, L"refs\\remotes");
    
    wchar_t name_wide[256];
    utf8_to_wide_n(name, name_wide, 256);
    
    wchar_t remote_dir[Git::MAX_PATH_LEN];
    make_path(remote_dir, Git::MAX_PATH_LEN, remote_refs_dir, name_wide);
    
    if (!ensure_directory(remote_dir)) {
        LOG("git_remote_add: failed to create refs/remotes/%s directory", name);
        return false;
    }
    
    // Do not log the remote URL — it may embed user:pass credentials (FIND-065).
    LOG("git_remote_add: added remote '%s'", name);
    return true;
}

// ============================================================================
// Clone URL Utilities
// ============================================================================

// Validate a clone URL (HTTPS only for MVP)
bool git_clone_validate_url(const char* url) {
    if (!url || url[0] == '\0') return false;
    
    // Must start with http:// or https://
    bool is_http = (strncmp(url, "http://", 7) == 0);
    bool is_https = (strncmp(url, "https://", 8) == 0);
    
    if (!is_http && !is_https) return false;
    
    // Must have at least host/path after protocol
    const char* after_proto = url + (is_https ? 8 : 7);
    if (strlen(after_proto) < 3) return false;  // At least "a/b"
    
    // Must contain a path separator after host
    if (strchr(after_proto, '/') == nullptr) return false;
    
    return true;
}

// Extract repository name from URL
// "https://github.com/user/repo.git" -> "repo"
// "https://github.com/user/repo" -> "repo"
// "https://github.com/user/repo/" -> "repo"
bool git_clone_extract_repo_name(const char* url, char* out_name, size_t max_len) {
    if (!url || url[0] == '\0' || !out_name || max_len == 0) return false;
    
    // Find the protocol separator
    const char* after_proto = strstr(url, "://");
    if (!after_proto) return false;
    after_proto += 3;  // Skip "://"
    
    // Find the first slash after the host (path start)
    const char* path_start = strchr(after_proto, '/');
    if (!path_start) return false;
    path_start++;  // Skip the slash
    
    // Must have at least a path component (user/repo)
    if (*path_start == '\0') return false;
    
    // Find the last path component
    size_t url_len = strlen(url);
    
    // Skip trailing slashes
    size_t end = url_len;
    while (end > 0 && url[end - 1] == '/') {
        end--;
    }
    
    if (end == 0) return false;
    
    // Find the last slash before the end
    size_t start = end;
    while (start > 0 && url[start - 1] != '/') {
        start--;
    }
    
    if (start == end) return false;  // Empty name
    
    // Verify we're past the host portion (start must be after path_start position)
    size_t path_start_pos = (size_t)(path_start - url);
    if (start < path_start_pos) return false;  // Name is the host, not a path component
    
    // Copy the name, stripping .git suffix if present
    size_t name_len = end - start;
    
    // Check for .git suffix
    const char* name_start = url + start;
    if (name_len > 4 && strncmp(name_start + name_len - 4, ".git", 4) == 0) {
        name_len -= 4;
    }

    if (name_len == 0) return false;
    if (name_len >= max_len) name_len = max_len - 1;

    strncpy_s(out_name, max_len, name_start, name_len);
    out_name[name_len] = '\0';

    return true;
}

// Expand URL shorthand to full HTTPS URL
// gh:owner/repo -> https://github.com/owner/repo.git
// owner/repo -> https://github.com/owner/repo.git (GitHub shorthand)
// Returns true if expansion was performed, false if URL unchanged (already valid or not shorthand)
bool git_clone_expand_url_shorthand(const char* input, char* out_url, size_t max_len) {
    if (!input || !out_url || max_len == 0) return false;

    // Already a full URL - no expansion needed
    if (strncmp(input, "http://", 7) == 0 || strncmp(input, "https://", 8) == 0) {
        strncpy_s(out_url, max_len, input, _TRUNCATE);
        return false;
    }

    // gh:owner/repo -> https://github.com/owner/repo.git
    if (strncmp(input, "gh:", 3) == 0) {
        const char* path = input + 3;
        if (strchr(path, '/') != nullptr) {
            snprintf(out_url, max_len, "https://github.com/%s.git", path);
            return true;
        }
        // Invalid gh: shorthand - copy as-is
        strncpy_s(out_url, max_len, input, _TRUNCATE);
        return false;
    }

    // owner/repo -> https://github.com/owner/repo.git
    // Must have exactly one slash and no other special chars
    const char* slash = strchr(input, '/');
    if (slash && strchr(slash + 1, '/') == nullptr &&
        strchr(input, ':') == nullptr &&
        strchr(input, '@') == nullptr &&
        strchr(input, '.') == nullptr) {
        // Looks like owner/repo format (no dots means not a URL)
        snprintf(out_url, max_len, "https://github.com/%s.git", input);
        return true;
    }

    // Not a recognized shorthand - copy as-is
    strncpy_s(out_url, max_len, input, _TRUNCATE);
    return false;
}

// Delete a local branch
// Refuses if it's the currently checked-out branch
// If force=false, also refuses if branch isn't fully merged (not implemented yet - always allows)
bool git_branch_delete(GitRepository* repo, const char* branch_name, bool force,
                       char* error_out, size_t error_size) {
    if (!repo || !repo->is_valid) {
        if (error_out) snprintf(error_out, error_size, "Invalid repository");
        return false;
    }

    if (!branch_name || branch_name[0] == '\0') {
        if (error_out) snprintf(error_out, error_size, "Branch name cannot be empty");
        return false;
    }

    // Check if branch exists
    if (!git_branch_exists(repo, branch_name)) {
        if (error_out) snprintf(error_out, error_size, "Branch '%s' not found", branch_name);
        return false;
    }

    // Check if this is the current branch (refuse to delete)
    if (!repo->head_detached && strcmp(repo->head_ref, branch_name) == 0) {
        if (error_out) snprintf(error_out, error_size, "Cannot delete branch '%s': currently checked out", branch_name);
        return false;
    }

    // Note: For non-force delete, we should check if branch is fully merged
    // This requires walking history to find merge base - skipping for now
    // (always allow delete like 'git branch -D')
    (void)force;

    wchar_t git_dir_wide[Git::MAX_PATH_LEN];
    utf8_to_wide_n(repo->git_dir, git_dir_wide, Git::MAX_PATH_LEN);

    // Try to delete loose ref first
    wchar_t ref_path[Git::MAX_PATH_LEN];
    make_path(ref_path, Git::MAX_PATH_LEN, git_dir_wide, L"refs\\heads");

    wchar_t branch_wide[Git::MAX_REF_NAME];
    utf8_to_wide_n(branch_name, branch_wide, Git::MAX_REF_NAME);

    // Convert forward slashes to backslashes for Windows path
    for (wchar_t* p = branch_wide; *p; p++) {
        if (*p == L'/') *p = L'\\';
    }

    wchar_t full_path[Git::MAX_PATH_LEN];
    make_path(full_path, Git::MAX_PATH_LEN, ref_path, branch_wide);

    bool deleted_loose = false;
    if (file_exists(full_path)) {
        if (!DeleteFileW(full_path)) {
            if (error_out) snprintf(error_out, error_size, "Failed to delete branch file");
            return false;
        }
        deleted_loose = true;

        // Try to remove empty parent directories
        // Walk up the path removing empty directories until we hit refs/heads
        wchar_t dir_path[Git::MAX_PATH_LEN];
        wcscpy_s(dir_path, full_path);
        for (int i = 0; i < 10; i++) { // Max depth
            wchar_t* last_slash = wcsrchr(dir_path, L'\\');
            if (!last_slash) break;
            *last_slash = L'\0';

            // Stop at refs/heads
            if (wcs_ends_with(dir_path, L"refs\\heads")) {
                break;
            }

            // Try to remove directory (will fail if not empty)
            if (!RemoveDirectoryW(dir_path)) {
                break; // Directory not empty or other error
            }
        }
    }

    // Also remove from packed-refs if present
    wchar_t packed_refs_path[Git::MAX_PATH_LEN];
    make_path(packed_refs_path, Git::MAX_PATH_LEN, git_dir_wide, L"packed-refs");

    {
        char full_ref[Git::MAX_REF_NAME + 16];
        snprintf(full_ref, sizeof(full_ref), "refs/heads/%s", branch_name);
        packed_refs_remove_line(packed_refs_path, full_ref);
    }

    LOG("git_branch_delete: deleted '%s'", branch_name);

    if (error_out && error_size > 0) error_out[0] = '\0';
    return true;
}

// Rename a local branch
// Updates HEAD if renaming the current branch
bool git_branch_rename(GitRepository* repo, const char* old_name, const char* new_name,
                       char* error_out, size_t error_size) {
    if (!repo || !repo->is_valid) {
        if (error_out) snprintf(error_out, error_size, "Invalid repository");
        return false;
    }

    if (!old_name || old_name[0] == '\0') {
        if (error_out) snprintf(error_out, error_size, "Old branch name cannot be empty");
        return false;
    }

    if (!new_name || new_name[0] == '\0') {
        if (error_out) snprintf(error_out, error_size, "New branch name cannot be empty");
        return false;
    }

    // Validate new name
    if (!git_is_valid_branch_name(new_name, error_out, error_size)) {
        return false;
    }

    // Check old branch exists
    if (!git_branch_exists(repo, old_name)) {
        if (error_out) snprintf(error_out, error_size, "Branch '%s' not found", old_name);
        return false;
    }

    // Check new branch doesn't exist
    if (git_branch_exists(repo, new_name)) {
        if (error_out) snprintf(error_out, error_size, "Branch '%s' already exists", new_name);
        return false;
    }

    wchar_t git_dir_wide[Git::MAX_PATH_LEN];
    utf8_to_wide_n(repo->git_dir, git_dir_wide, Git::MAX_PATH_LEN);

    // Read SHA from old ref
    wchar_t old_ref_path[Git::MAX_PATH_LEN];
    make_path(old_ref_path, Git::MAX_PATH_LEN, git_dir_wide, L"refs\\heads");

    wchar_t old_branch_wide[Git::MAX_REF_NAME];
    utf8_to_wide_n(old_name, old_branch_wide, Git::MAX_REF_NAME);
    for (wchar_t* p = old_branch_wide; *p; p++) {
        if (*p == L'/') *p = L'\\';
    }

    wchar_t old_full_path[Git::MAX_PATH_LEN];
    make_path(old_full_path, Git::MAX_PATH_LEN, old_ref_path, old_branch_wide);

    char sha[Git::SHA1_HEX_SIZE + 2] = {};
    char full_old_ref[Git::MAX_REF_NAME + 16];
    snprintf(full_old_ref, sizeof(full_old_ref), "refs/heads/%s", old_name);
    if (!resolve_ref_sha(git_dir_wide, full_old_ref, sha)) {
        if (error_out) snprintf(error_out, error_size, "Could not read SHA from branch '%s'", old_name);
        return false;
    }

    // Check if this is the current branch
    bool is_current = !repo->head_detached && strcmp(repo->head_ref, old_name) == 0;

    // Create new ref
    char new_ref_path[Git::MAX_REF_NAME + 16];
    snprintf(new_ref_path, sizeof(new_ref_path), "refs/heads/%s", new_name);

    if (!git_ref_update(repo, new_ref_path, sha)) {
        if (error_out) snprintf(error_out, error_size, "Failed to create new branch reference");
        return false;
    }

    // Delete old ref (reuse git_branch_delete logic but without the current-branch check)
    // We need to delete the old ref file
    if (file_exists(old_full_path)) {
        DeleteFileW(old_full_path);
    }

    // Remove from packed-refs if present
    wchar_t packed_refs_path[Git::MAX_PATH_LEN];
    make_path(packed_refs_path, Git::MAX_PATH_LEN, git_dir_wide, L"packed-refs");

    {
        char full_ref[Git::MAX_REF_NAME + 16];
        snprintf(full_ref, sizeof(full_ref), "refs/heads/%s", old_name);
        packed_refs_remove_line(packed_refs_path, full_ref);
    }

    // Update HEAD if renaming current branch
    if (is_current) {
        wchar_t head_path[Git::MAX_PATH_LEN];
        make_path(head_path, Git::MAX_PATH_LEN, git_dir_wide, L"HEAD");

        char head_content[Git::MAX_REF_NAME + 32];
        snprintf(head_content, sizeof(head_content), "ref: refs/heads/%s\n", new_name);

        if (!write_file_atomic(head_path, head_content, strlen(head_content))) {
            if (error_out) snprintf(error_out, error_size, "Failed to update HEAD");
            return false;
        }

        // Update repo state
        strncpy_s(repo->head_ref, new_name, Git::MAX_REF_NAME - 1);
    }

    LOG("git_branch_rename: renamed '%s' -> '%s'", old_name, new_name);

    if (error_out && error_size > 0) error_out[0] = '\0';
    return true;
}

