// <AUTO-GENERATED TOC> DO NOT EDIT MANUALLY
// Table of Contents
//
// 1. Active Editor for Timer Callbacks (line 35)
// 2. Color Helpers (line 49)
// 3. CodeEditorWidget Construction/Destruction (line 62)
// 4. Document Management (line 96)
// 5. Scroll Control (line 129)
// 6. Widget Interface (line 163)
// 7. Scrollbar Rendering (line 298)
// 8. Keyboard Handling (line 782)
// 9. Scroll Cache Helpers (line 1724)
// 10. Undo Coalescing Helpers (line 1769)
//
// </AUTO-GENERATED TOC>
// code_editor.cpp - CodeEditorWidget implementation
//
// Main container that composes GutterWidget + ContentWidget + scrollbar.

#include "code_editor.h"
#include <Windows.h>
#include <d2d1.h>
#include <dwrite.h>
#include <cmath>
#include <cstring>

// External resources (defined in platform.cpp and ui_widgets_core.cpp)
extern IDWriteFactory* g_dwrite_factory;
extern IDWriteTextFormat* g_text_format_mono;
extern WidgetArena g_widget_arena;
extern HWND g_main_window;

namespace CodeEditor {

// ============================================================================
// Active Editor for Timer Callbacks
// ============================================================================

// Tracks which editor has an active coalesce timer (only one at a time)
static CodeEditorWidget* g_coalesce_timer_owner = nullptr;

// Called from WM_TIMER handler in platform.cpp
void editor_handle_coalesce_timer() {
    if (g_coalesce_timer_owner) {
        g_coalesce_timer_owner->on_coalesce_timer();
    }
}

// ============================================================================
// Color Helpers
// ============================================================================

static D2D1_COLOR_F editor_to_color_f(uint32_t argb) {
    return D2D1::ColorF(
        ((argb >> 16) & 0xFF) / 255.0f,
        ((argb >> 8) & 0xFF) / 255.0f,
        (argb & 0xFF) / 255.0f,
        ((argb >> 24) & 0xFF) / 255.0f
    );
}

// ============================================================================
// CodeEditorWidget Construction/Destruction
// ============================================================================

CodeEditorWidget::CodeEditorWidget() : Widget() {
    debug_name = "CodeEditor::CodeEditorWidget";
    flags |= WidgetFlags::CapturesMouse;  // Capture mouse during scrollbar drag
    flags |= WidgetFlags::Focusable;      // Accept keyboard focus
    flags |= WidgetFlags::SkipTabStop;    // Editor not part of Tab focus order

    // Create child widgets via arena
    gutter_ = g_widget_arena.create<GutterWidget>();
    content_ = g_widget_arena.create<ContentWidget>();

    // Add children to tree
    widget_add_child(this, gutter_);
    widget_add_child(this, content_);

    // Initialize scroll cache
    cache_count_ = 0;
    for (size_t i = 0; i < EditorConfig::SCROLL_CACHE_SIZE; i++) {
        scroll_cache_[i].document = nullptr;
    }
}

CodeEditorWidget::~CodeEditorWidget() {
    // Stop coalesce timer if running and clear owner
    if (g_coalesce_timer_owner == this) {
        stop_coalesce_timer();
        g_coalesce_timer_owner = nullptr;
    }
    // Children are arena-allocated, no delete needed
}

// ============================================================================
// Document Management
// ============================================================================

void CodeEditorWidget::set_document(TextDocument* doc) {
    if (document_ == doc) return;

    // Cache scroll position for current document before switching
    cache_scroll_position();

    document_ = doc;

    // Set document on content widget (this builds LineIndex)
    content_->set_document(doc);

    // Bind gutter to content's LineIndex and scroll position
    if (content_->document()) {
        gutter_->bind(&content_->line_index_, &content_->scroll_y_);
        gutter_->update_width_for_line_count(content_->line_index_.line_count());
    } else {
        gutter_->bind(nullptr, nullptr);
    }

    // Try to restore cached scroll position
    if (!restore_scroll_position()) {
        // No cached position, start at top
        content_->set_scroll_y(0.0f);
        content_->set_scroll_x(0.0f);
    }

    set_dirty();
}

// ============================================================================
// Scroll Control
// ============================================================================

void CodeEditorWidget::scroll_to_line(size_t line) {
    if (!content_ || line == 0) return;

    // Calculate Y position for the line
    float y = (line - 1) * ContentConfig::LINE_HEIGHT;

    // Center the line in the viewport if possible
    float viewport_h = content_->rect.height;
    float target_scroll = y - viewport_h / 2.0f + ContentConfig::LINE_HEIGHT / 2.0f;

    content_->set_scroll_y(target_scroll);
    update_scrollbar_geometry();
    set_dirty();
}

size_t CodeEditorWidget::get_first_visible_line() const {
    if (!content_) return 0;
    return content_->line_index_.first_visible_line(content_->scroll_y_);
}

size_t CodeEditorWidget::get_last_visible_line() const {
    if (!content_) return 0;
    return content_->line_index_.last_visible_line(content_->scroll_y_, content_->rect.height);
}

size_t CodeEditorWidget::get_line_count() const {
    if (!content_) return 0;
    return content_->line_index_.line_count();
}

// ============================================================================
// Widget Interface
// ============================================================================

void CodeEditorWidget::measure(const LayoutConstraints& constraints) {
    // CodeEditorWidget fills available space
    rect.width = constraints.max_width;
    rect.height = constraints.max_height;

    preferred_width = rect.width;
    preferred_height = rect.height;
}

void CodeEditorWidget::layout() {
    if (!gutter_ || !content_) return;

    // Calculate gutter width based on line count
    size_t line_count = content_->line_index_.line_count();
    gutter_->update_width_for_line_count(line_count);
    float gutter_width = gutter_->get_width();

    // Reserve space for both scrollbars (following DiffViewerWidget pattern)
    // H-scrollbar space is always reserved; when not needed, we draw empty track
    // This avoids chicken-and-egg problem where max_content_width_ isn't known
    // until after layout runs
    float scrollbar_width = EditorConfig::SCROLLBAR_WIDTH;
    float viewport_width = rect.width - gutter_width - scrollbar_width;
    float content_area_width = fmaxf(0.0f, viewport_width);
    float content_height = rect.height - scrollbar_width;  // Always reserve h-scrollbar space

    // Position gutter
    gutter_->rect.x = rect.x;
    gutter_->rect.y = rect.y;
    gutter_->rect.width = gutter_width;
    gutter_->rect.height = content_height;
    gutter_->layout();

    // Position content
    content_->rect.x = rect.x + gutter_width;
    content_->rect.y = rect.y;
    content_->rect.width = content_area_width;
    content_->rect.height = content_height;
    content_->layout();

    // Update scrollbar geometry (both vertical and horizontal)
    update_scrollbar_geometry();
    update_h_scrollbar_geometry();
}

void CodeEditorWidget::render(RenderContext& ctx) {
    // Clip to widget bounds
    D2D1_RECT_F clip_rect = {rect.x, rect.y, rect.x + rect.width, rect.y + rect.height};
    ctx.push_clip(clip_rect);

    // Render gutter
    if (gutter_) {
        gutter_->render(ctx);
    }

    // Render content (this may lazily create line layouts and update max_content_width_)
    if (content_) {
        content_->render(ctx);
    }

    // Update scrollbar geometry before rendering (ensures geometry reflects any
    // max_content_width_ changes from lazy layout creation during content render)
    update_scrollbar_geometry();
    update_h_scrollbar_geometry();

    // Render vertical scrollbar
    render_scrollbar(ctx);

    // Render horizontal scrollbar (if content wider than viewport)
    render_h_scrollbar(ctx);

    ctx.pop_clip();
}

bool CodeEditorWidget::on_mouse_wheel(float x, float y, float delta) {
    (void)x;
    (void)y;

    if (!content_) return false;

    // Check if Shift is held for horizontal scroll
    bool shift_held = (GetKeyState(VK_SHIFT) & 0x8000) != 0;

    if (shift_held) {
        // Horizontal scroll - same speed as vertical (3 "columns" worth)
        constexpr float H_SCROLL_SPEED = 40.0f * 3.0f;  // Match vertical feel
        float old_scroll = content_->scroll_x_;
        content_->set_scroll_x(content_->scroll_x_ - delta * H_SCROLL_SPEED);

        if (content_->scroll_x_ != old_scroll) {
            update_h_scrollbar_geometry();
            set_dirty();
        }
    } else {
        // Vertical scroll - 3 lines per wheel notch
        float scroll_amount = delta * ContentConfig::LINE_HEIGHT * 3.0f;
        float old_scroll = content_->scroll_y_;
        content_->set_scroll_y(content_->scroll_y_ - scroll_amount);

        // Update scrollbar if scroll position changed
        // Note: vertical scrolling may change visible lines, which updates max_content_width_,
        // so we need to update both scrollbar geometries
        if (content_->scroll_y_ != old_scroll) {
            update_scrollbar_geometry();
            update_h_scrollbar_geometry();
            set_dirty();
        }
    }

    return true;  // Always consume wheel events over the editor
}

bool CodeEditorWidget::on_mouse_hwheel(float x, float y, float delta) {
    (void)x;
    (void)y;

    if (!content_) return false;

    // Horizontal scroll - 3 "columns" worth per wheel notch
    constexpr float H_SCROLL_SPEED = 40.0f * 3.0f;
    float old_scroll = content_->scroll_x_;
    content_->set_scroll_x(content_->scroll_x_ + delta * H_SCROLL_SPEED);

    if (content_->scroll_x_ != old_scroll) {
        update_h_scrollbar_geometry();
        set_dirty();
    }

    return true;  // Always consume horizontal wheel events over the editor
}

// ============================================================================
// Scrollbar Rendering
// ============================================================================

void CodeEditorWidget::update_scrollbar_geometry() {
    if (!content_) return;

    float viewport_height = content_->rect.height;
    float content_height = content_->content_height();

    // H-scrollbar space is always reserved (following DiffViewerWidget pattern)
    float v_scrollbar_bottom = rect.y + rect.height - EditorConfig::SCROLLBAR_WIDTH;

    // Track area (between up/down buttons)
    track_top_ = rect.y + EditorConfig::SCROLLBAR_BUTTON_SIZE;
    track_bottom_ = v_scrollbar_bottom - EditorConfig::SCROLLBAR_BUTTON_SIZE;
    float track_height = track_bottom_ - track_top_;

    if (track_height <= 0.0f) {
        thumb_top_ = thumb_bottom_ = track_top_;
        return;
    }

    // Thumb size proportional to visible content
    float visible_ratio = viewport_height / fmaxf(content_height, 1.0f);
    float thumb_height = fmaxf(track_height * fminf(visible_ratio, 1.0f),
                               EditorConfig::SCROLLBAR_MIN_THUMB);

    // Thumb position based on scroll
    float max_scroll = fmaxf(0.0f, content_height - viewport_height);
    float scroll_ratio = max_scroll > 0 ? content_->scroll_y_ / max_scroll : 0.0f;
    scroll_ratio = fminf(1.0f, fmaxf(0.0f, scroll_ratio));  // Clamp to [0, 1]
    float available_track = track_height - thumb_height;

    thumb_top_ = track_top_ + scroll_ratio * available_track;
    thumb_bottom_ = thumb_top_ + thumb_height;
}

bool CodeEditorWidget::needs_h_scrollbar() const {
    if (!content_ || !gutter_) return false;
    float viewport_width = rect.width - gutter_->get_width() - EditorConfig::SCROLLBAR_WIDTH;
    return content_->max_content_width_ > viewport_width;
}

void CodeEditorWidget::update_h_scrollbar_geometry() {
    if (!content_ || !gutter_) return;

    // Calculate viewport width (content area minus v-scrollbar)
    float gutter_width = gutter_->get_width();
    float viewport_width = rect.width - gutter_width - EditorConfig::SCROLLBAR_WIDTH;

    // Check if h-scrollbar is needed
    float content_width = content_->max_content_width_;
    if (content_width <= viewport_width) {
        // Reset geometry when not needed
        h_thumb_left_ = h_thumb_right_ = 0.0f;
        h_track_left_ = h_track_right_ = 0.0f;
        return;
    }

    // H-scrollbar spans from gutter to v-scrollbar
    float sb_left = rect.x + gutter_width;
    float sb_right = rect.x + rect.width - EditorConfig::SCROLLBAR_WIDTH;

    // Track area (between left/right buttons)
    h_track_left_ = sb_left + EditorConfig::SCROLLBAR_BUTTON_SIZE;
    h_track_right_ = sb_right - EditorConfig::SCROLLBAR_BUTTON_SIZE;
    float track_width = h_track_right_ - h_track_left_;

    if (track_width <= 0.0f) {
        h_thumb_left_ = h_thumb_right_ = h_track_left_;
        return;
    }

    // Thumb size proportional to visible content
    float visible_ratio = viewport_width / fmaxf(content_width, 1.0f);
    float thumb_width = fmaxf(track_width * fminf(visible_ratio, 1.0f),
                              EditorConfig::SCROLLBAR_MIN_THUMB);

    // Thumb position based on scroll
    float max_scroll_x = fmaxf(0.0f, content_width - viewport_width);
    float scroll_ratio_h = max_scroll_x > 0 ? content_->scroll_x_ / max_scroll_x : 0.0f;
    scroll_ratio_h = fminf(1.0f, fmaxf(0.0f, scroll_ratio_h));  // Clamp to [0, 1]
    float available_track_h = track_width - thumb_width;

    h_thumb_left_ = h_track_left_ + scroll_ratio_h * available_track_h;
    h_thumb_right_ = h_thumb_left_ + thumb_width;
}

void CodeEditorWidget::h_scroll_by_column(int direction) {
    if (!content_) return;
    constexpr float COLUMN_SCROLL = 40.0f;  // Pixels per column
    content_->set_scroll_x(content_->scroll_x_ + direction * COLUMN_SCROLL);
    update_h_scrollbar_geometry();
    set_dirty();
}

void CodeEditorWidget::h_scroll_by_page(int direction) {
    if (!content_) return;
    float page_size = content_->rect.width * 0.9f;  // 90% of viewport
    content_->set_scroll_x(content_->scroll_x_ + direction * page_size);
    update_h_scrollbar_geometry();
    set_dirty();
}

void CodeEditorWidget::render_scrollbar(RenderContext& ctx) {
    float sb_x = rect.x + rect.width - EditorConfig::SCROLLBAR_WIDTH;

    // H-scrollbar space is always reserved (following DiffViewerWidget pattern)
    float sb_bottom = rect.y + rect.height - EditorConfig::SCROLLBAR_WIDTH;

    // Track background
    D2D1_RECT_F track_rect = {sb_x, rect.y, rect.x + rect.width, sb_bottom};
    ctx.brush->SetColor(editor_to_color_f(EditorConfig::SCROLLBAR_TRACK_COLOR));
    ctx.target->FillRectangle(track_rect, ctx.brush);

    // Up button
    D2D1_RECT_F up_rect = {sb_x, rect.y, rect.x + rect.width,
                           rect.y + EditorConfig::SCROLLBAR_BUTTON_SIZE};
    if (scrollbar_hover_ == ScrollbarHover::UpButton) {
        ctx.brush->SetColor(editor_to_color_f(EditorConfig::SCROLLBAR_BUTTON_HOVER));
        ctx.target->FillRectangle(up_rect, ctx.brush);
    }
    draw_scrollbar_arrow(ctx, sb_x + EditorConfig::SCROLLBAR_WIDTH / 2.0f,
                         rect.y + EditorConfig::SCROLLBAR_BUTTON_SIZE / 2.0f, true);

    // Down button
    D2D1_RECT_F down_rect = {sb_x, sb_bottom - EditorConfig::SCROLLBAR_BUTTON_SIZE,
                             rect.x + rect.width, sb_bottom};
    if (scrollbar_hover_ == ScrollbarHover::DownButton) {
        ctx.brush->SetColor(editor_to_color_f(EditorConfig::SCROLLBAR_BUTTON_HOVER));
        ctx.target->FillRectangle(down_rect, ctx.brush);
    }
    draw_scrollbar_arrow(ctx, sb_x + EditorConfig::SCROLLBAR_WIDTH / 2.0f,
                         sb_bottom - EditorConfig::SCROLLBAR_BUTTON_SIZE / 2.0f, false);

    // Thumb (only if we have valid geometry)
    if (thumb_bottom_ > thumb_top_) {
        D2D1_RECT_F thumb_rect = {
            sb_x + EditorConfig::SCROLLBAR_THUMB_MARGIN,
            thumb_top_,
            rect.x + rect.width - EditorConfig::SCROLLBAR_THUMB_MARGIN,
            thumb_bottom_
        };
        uint32_t thumb_color = (scrollbar_hover_ == ScrollbarHover::Thumb || scrollbar_dragging_)
                               ? EditorConfig::SCROLLBAR_THUMB_HOVER
                               : EditorConfig::SCROLLBAR_THUMB_COLOR;
        D2D1_ROUNDED_RECT rounded_thumb = {thumb_rect, 3.0f, 3.0f};
        ctx.brush->SetColor(editor_to_color_f(thumb_color));
        ctx.target->FillRoundedRectangle(rounded_thumb, ctx.brush);
    }
}

void CodeEditorWidget::draw_scrollbar_arrow(RenderContext& ctx, float cx, float cy, bool up) {
    ctx.brush->SetColor(editor_to_color_f(EditorConfig::SCROLLBAR_BUTTON_COLOR));

    float size = 4.0f;
    if (up) {
        // Up arrow: point at top
        ctx.target->DrawLine(D2D1::Point2F(cx, cy - size),
                             D2D1::Point2F(cx - size, cy + size / 2.0f), ctx.brush, 1.0f);
        ctx.target->DrawLine(D2D1::Point2F(cx, cy - size),
                             D2D1::Point2F(cx + size, cy + size / 2.0f), ctx.brush, 1.0f);
    } else {
        // Down arrow: point at bottom
        ctx.target->DrawLine(D2D1::Point2F(cx, cy + size),
                             D2D1::Point2F(cx - size, cy - size / 2.0f), ctx.brush, 1.0f);
        ctx.target->DrawLine(D2D1::Point2F(cx, cy + size),
                             D2D1::Point2F(cx + size, cy - size / 2.0f), ctx.brush, 1.0f);
    }
}

void CodeEditorWidget::render_h_scrollbar(RenderContext& ctx) {
    if (!content_ || !gutter_) return;

    float gutter_width = gutter_->get_width();
    float sb_y = rect.y + rect.height - EditorConfig::SCROLLBAR_WIDTH;
    float sb_left = rect.x + gutter_width;
    float sb_right = rect.x + rect.width - EditorConfig::SCROLLBAR_WIDTH;

    // Always draw track background (following DiffViewerWidget pattern)
    D2D1_RECT_F track_rect = {sb_left, sb_y, sb_right, sb_y + EditorConfig::SCROLLBAR_WIDTH};
    ctx.brush->SetColor(editor_to_color_f(EditorConfig::SCROLLBAR_TRACK_COLOR));
    ctx.target->FillRectangle(track_rect, ctx.brush);

    // Fill the corner where v-scrollbar and h-scrollbar meet
    D2D1_RECT_F corner_rect = {
        sb_right,
        sb_y,
        rect.x + rect.width,
        sb_y + EditorConfig::SCROLLBAR_WIDTH
    };
    ctx.target->FillRectangle(corner_rect, ctx.brush);

    // If no scrolling needed, just show empty track (no buttons or thumb)
    if (!needs_h_scrollbar()) return;

    // Left button
    D2D1_RECT_F left_rect = {sb_left, sb_y,
                              sb_left + EditorConfig::SCROLLBAR_BUTTON_SIZE,
                              sb_y + EditorConfig::SCROLLBAR_WIDTH};
    if (h_scrollbar_hover_ == HScrollbarHover::LeftButton) {
        ctx.brush->SetColor(editor_to_color_f(EditorConfig::SCROLLBAR_BUTTON_HOVER));
        ctx.target->FillRectangle(left_rect, ctx.brush);
    }
    draw_h_scrollbar_arrow(ctx, sb_left + EditorConfig::SCROLLBAR_BUTTON_SIZE / 2.0f,
                           sb_y + EditorConfig::SCROLLBAR_WIDTH / 2.0f, true);  // true = left

    // Right button
    float right_btn_x = sb_right - EditorConfig::SCROLLBAR_BUTTON_SIZE;
    D2D1_RECT_F right_rect = {right_btn_x, sb_y,
                               sb_right,
                               sb_y + EditorConfig::SCROLLBAR_WIDTH};
    if (h_scrollbar_hover_ == HScrollbarHover::RightButton) {
        ctx.brush->SetColor(editor_to_color_f(EditorConfig::SCROLLBAR_BUTTON_HOVER));
        ctx.target->FillRectangle(right_rect, ctx.brush);
    }
    draw_h_scrollbar_arrow(ctx, right_btn_x + EditorConfig::SCROLLBAR_BUTTON_SIZE / 2.0f,
                           sb_y + EditorConfig::SCROLLBAR_WIDTH / 2.0f, false);  // false = right

    // Thumb (only if we have valid geometry)
    if (h_thumb_right_ > h_thumb_left_) {
        D2D1_RECT_F thumb_rect = {
            h_thumb_left_,
            sb_y + EditorConfig::SCROLLBAR_THUMB_MARGIN,
            h_thumb_right_,
            sb_y + EditorConfig::SCROLLBAR_WIDTH - EditorConfig::SCROLLBAR_THUMB_MARGIN
        };
        uint32_t thumb_color = (h_scrollbar_hover_ == HScrollbarHover::Thumb || h_scrollbar_dragging_)
                               ? EditorConfig::SCROLLBAR_THUMB_HOVER
                               : EditorConfig::SCROLLBAR_THUMB_COLOR;
        D2D1_ROUNDED_RECT rounded_thumb = {thumb_rect, 3.0f, 3.0f};
        ctx.brush->SetColor(editor_to_color_f(thumb_color));
        ctx.target->FillRoundedRectangle(rounded_thumb, ctx.brush);
    }
}

void CodeEditorWidget::draw_h_scrollbar_arrow(RenderContext& ctx, float cx, float cy, bool left) {
    ctx.brush->SetColor(editor_to_color_f(EditorConfig::SCROLLBAR_BUTTON_COLOR));

    float size = 4.0f;
    if (left) {
        // Left arrow: point at left
        ctx.target->DrawLine(D2D1::Point2F(cx - size, cy),
                             D2D1::Point2F(cx + size / 2.0f, cy - size), ctx.brush, 1.0f);
        ctx.target->DrawLine(D2D1::Point2F(cx - size, cy),
                             D2D1::Point2F(cx + size / 2.0f, cy + size), ctx.brush, 1.0f);
    } else {
        // Right arrow: point at right
        ctx.target->DrawLine(D2D1::Point2F(cx + size, cy),
                             D2D1::Point2F(cx - size / 2.0f, cy - size), ctx.brush, 1.0f);
        ctx.target->DrawLine(D2D1::Point2F(cx + size, cy),
                             D2D1::Point2F(cx - size / 2.0f, cy + size), ctx.brush, 1.0f);
    }
}

bool CodeEditorWidget::is_over_scrollbar(float abs_x) const {
    float sb_x = rect.x + rect.width - EditorConfig::SCROLLBAR_WIDTH;
    return abs_x >= sb_x && abs_x < rect.x + rect.width;
}

bool CodeEditorWidget::on_mouse_move(float x, float y) {
    // When captured (via EventDispatcher), x,y are ABSOLUTE. Otherwise they're RELATIVE.
    // We're captured if any scrollbar is being dragged.
    bool is_captured = scrollbar_dragging_ || h_scrollbar_dragging_;

    // Handle horizontal scrollbar drag
    if (h_scrollbar_dragging_ && content_) {
        float abs_x = is_captured ? x : (x + rect.x);

        float delta_x = abs_x - h_drag_start_x_;
        float track_width = h_track_right_ - h_track_left_;
        float thumb_width = h_thumb_right_ - h_thumb_left_;
        float available_track = track_width - thumb_width;

        if (available_track > 0.0f) {
            float max_scroll = content_->max_scroll_x();
            if (max_scroll > 0.0f) {
                float scroll_delta = (delta_x / available_track) * max_scroll;
                content_->set_scroll_x(h_drag_start_scroll_ + scroll_delta);
                update_h_scrollbar_geometry();
                set_dirty();
            }
        }
        return true;
    }

    // Handle vertical thumb drag (captured = absolute coords)
    if (scrollbar_dragging_ && content_) {
        // When captured, coords are already absolute
        float abs_y = is_captured ? y : (y + rect.y);

        float delta_y = abs_y - drag_start_y_;
        float track_height = track_bottom_ - track_top_;
        float thumb_height = thumb_bottom_ - thumb_top_;
        float available_track = track_height - thumb_height;

        if (available_track > 0) {
            float scroll_delta = delta_y / available_track * content_->max_scroll_y();
            content_->set_scroll_y(drag_start_scroll_ + scroll_delta);
            update_scrollbar_geometry();
            set_dirty();
        }
        return true;
    }

    // Convert to absolute coordinates for hover detection
    // When captured, coords are already absolute. Otherwise, convert from relative.
    float abs_x = is_captured ? x : (rect.x + x);
    float abs_y = is_captured ? y : (rect.y + y);

    // H-scrollbar area (always reserved, following DiffViewerWidget pattern)
    float sb_y_h = rect.y + rect.height - EditorConfig::SCROLLBAR_WIDTH;
    float sb_left_h = rect.x + (gutter_ ? gutter_->get_width() : 0.0f);
    float sb_right_h = rect.x + rect.width - EditorConfig::SCROLLBAR_WIDTH;

    // Update horizontal scrollbar hover state (only if scrolling is needed)
    HScrollbarHover new_hover_h = HScrollbarHover::None;
    if (needs_h_scrollbar() && abs_y >= sb_y_h && abs_x >= sb_left_h && abs_x < sb_right_h) {
        if (abs_x < sb_left_h + EditorConfig::SCROLLBAR_BUTTON_SIZE) {
            new_hover_h = HScrollbarHover::LeftButton;
        } else if (abs_x > sb_right_h - EditorConfig::SCROLLBAR_BUTTON_SIZE) {
            new_hover_h = HScrollbarHover::RightButton;
        } else if (abs_x >= h_thumb_left_ && abs_x < h_thumb_right_) {
            new_hover_h = HScrollbarHover::Thumb;
        } else {
            new_hover_h = HScrollbarHover::Track;
        }
    }

    if (new_hover_h != h_scrollbar_hover_) {
        h_scrollbar_hover_ = new_hover_h;
        set_dirty();
    }

    // Update vertical scrollbar hover state
    // V-scrollbar ends at h-scrollbar (always reserved)
    ScrollbarHover new_hover = ScrollbarHover::None;
    float v_sb_bottom = rect.y + rect.height - EditorConfig::SCROLLBAR_WIDTH;

    if (is_over_scrollbar(abs_x) && abs_y < v_sb_bottom) {
        if (abs_y < rect.y + EditorConfig::SCROLLBAR_BUTTON_SIZE) {
            new_hover = ScrollbarHover::UpButton;
        } else if (abs_y > v_sb_bottom - EditorConfig::SCROLLBAR_BUTTON_SIZE) {
            new_hover = ScrollbarHover::DownButton;
        } else if (abs_y >= thumb_top_ && abs_y < thumb_bottom_) {
            new_hover = ScrollbarHover::Thumb;
        } else if (abs_y >= track_top_ && abs_y < track_bottom_) {
            new_hover = ScrollbarHover::Track;
        }
    }

    if (new_hover != scrollbar_hover_) {
        scrollbar_hover_ = new_hover;
        set_dirty();
    }

    return false;
}

bool CodeEditorWidget::on_mouse_down(float x, float y, int button) {
    if (button != 0) return false;  // Left button only

    // Convert local coordinates to absolute (scrollbar geometry is in absolute coords)
    float abs_x = x + rect.x;
    float abs_y = y + rect.y;

    if (!content_ || !gutter_) return false;

    // H-scrollbar area (always reserved, following DiffViewerWidget pattern)
    float sb_y_h = rect.y + rect.height - EditorConfig::SCROLLBAR_WIDTH;
    float sb_left_h = rect.x + gutter_->get_width();
    float sb_right_h = rect.x + rect.width - EditorConfig::SCROLLBAR_WIDTH;

    // Check if click is in horizontal scrollbar area
    if (abs_y >= sb_y_h && abs_x >= sb_left_h && abs_x < sb_right_h) {
        // Only process clicks if scrolling is actually needed
        if (needs_h_scrollbar()) {
            // Left button
            if (abs_x < sb_left_h + EditorConfig::SCROLLBAR_BUTTON_SIZE) {
                h_scroll_by_column(-1);
                return true;
            }

            // Right button
            if (abs_x > sb_right_h - EditorConfig::SCROLLBAR_BUTTON_SIZE) {
                h_scroll_by_column(1);
                return true;
            }

            // Thumb drag
            if (abs_x >= h_thumb_left_ && abs_x < h_thumb_right_) {
                h_scrollbar_dragging_ = true;
                h_drag_start_x_ = abs_x;
                h_drag_start_scroll_ = content_->scroll_x_;
                set_dirty();
                return true;
            }

            // Track click - page left/right
            if (abs_x < h_thumb_left_) {
                h_scroll_by_page(-1);
            } else {
                h_scroll_by_page(1);
            }
            return true;
        }
        // Click on empty h-scrollbar track - consume but do nothing
        return true;
    }

    // Check vertical scrollbar
    if (!is_over_scrollbar(abs_x)) return false;

    // V-scrollbar ends at h-scrollbar (always reserved)
    float v_sb_bottom = rect.y + rect.height - EditorConfig::SCROLLBAR_WIDTH;

    // Up button
    if (abs_y < rect.y + EditorConfig::SCROLLBAR_BUTTON_SIZE) {
        float scroll_amount = ContentConfig::LINE_HEIGHT * 3.0f;
        content_->set_scroll_y(content_->scroll_y_ - scroll_amount);
        update_scrollbar_geometry();
        set_dirty();
        return true;
    }

    // Down button
    if (abs_y > v_sb_bottom - EditorConfig::SCROLLBAR_BUTTON_SIZE && abs_y < v_sb_bottom) {
        float scroll_amount = ContentConfig::LINE_HEIGHT * 3.0f;
        content_->set_scroll_y(content_->scroll_y_ + scroll_amount);
        update_scrollbar_geometry();
        set_dirty();
        return true;
    }

    // Thumb drag
    if (abs_y >= thumb_top_ && abs_y < thumb_bottom_) {
        scrollbar_dragging_ = true;
        drag_start_y_ = abs_y;
        drag_start_scroll_ = content_->scroll_y_;
        set_dirty();  // Show drag visual state immediately
        return true;
    }

    // Track click - page scroll
    if (abs_y >= track_top_ && abs_y < thumb_top_) {
        // Click above thumb - page up
        content_->set_scroll_y(content_->scroll_y_ - content_->rect.height);
        update_scrollbar_geometry();
        set_dirty();
        return true;
    } else if (abs_y >= thumb_bottom_ && abs_y < track_bottom_) {
        // Click below thumb - page down
        content_->set_scroll_y(content_->scroll_y_ + content_->rect.height);
        update_scrollbar_geometry();
        set_dirty();
        return true;
    }

    return false;
}

bool CodeEditorWidget::on_mouse_up(float x, float y, int button) {
    (void)x;
    (void)y;
    (void)button;

    // Handle vertical scrollbar drag release
    if (scrollbar_dragging_) {
        scrollbar_dragging_ = false;
        set_dirty();  // Clear drag visual state
        return true;
    }

    // Handle horizontal scrollbar drag release
    if (h_scrollbar_dragging_) {
        h_scrollbar_dragging_ = false;
        set_dirty();  // Clear drag visual state
        return true;
    }

    return false;
}

// ============================================================================
// Keyboard Handling
// ============================================================================

bool CodeEditorWidget::on_key_down(int vk, bool ctrl, bool shift, bool alt) {
    (void)alt;

    if (!content_ || !document_) return false;

    size_t line = content_->cursor_line();
    size_t col = content_->cursor_column();
    size_t line_count = content_->line_index_.line_count();

    // Helper lambda to handle selection extension
    // If shift is held, extends selection; otherwise clears it
    auto handle_selection = [&](size_t new_byte_pos) {
        if (shift) {
            // Extend selection
            if (!content_->has_selection()) {
                // Start selection from current cursor (sets anchor)
                content_->begin_selection_at_cursor();
            }
            content_->extend_selection_to(new_byte_pos);
        } else {
            // Clear selection
            content_->clear_selection();
        }
    };

    switch (vk) {
        case VK_LEFT:
            if (ctrl) {
                // Ctrl+Left: Move to previous word boundary, crossing lines if needed
                size_t cur_pos = content_->cursor_byte_pos();
                size_t new_pos = content_->get_word_boundary_left(cur_pos > 0 ? cur_pos - 1 : 0);

                // If we stopped at start of line and there's a previous line, continue there
                if (new_pos == cur_pos && col == 0 && line > 1) {
                    // Move to end of previous line
                    size_t prev_line_len = content_->get_line_length_in_columns(line - 1);
                    size_t prev_line_end = content_->line_column_to_byte_pos(line - 1, prev_line_len);
                    new_pos = content_->get_word_boundary_left(prev_line_end > 0 ? prev_line_end - 1 : 0);
                } else if (new_pos == cur_pos && cur_pos > 0) {
                    // We didn't move - try going back one more character
                    new_pos = cur_pos - 1;
                }

                handle_selection(new_pos);
                content_->move_cursor_to(new_pos);
            } else {
                // Left arrow: Move one character left
                size_t new_line = line, new_col = col;
                if (col > 0) {
                    new_col = col - 1;
                } else if (line > 1) {
                    // Wrap to end of previous line
                    new_line = line - 1;
                    new_col = content_->get_line_length_in_columns(new_line);
                }
                size_t new_pos = content_->line_column_to_byte_pos(new_line, new_col);
                handle_selection(new_pos);
                content_->move_cursor_to_line_column(new_line, new_col);
            }
            return true;

        case VK_RIGHT:
            if (ctrl) {
                // Ctrl+Right: Move to next word boundary, crossing lines if needed
                size_t cur_pos = content_->cursor_byte_pos();
                size_t doc_len = content_->document()->content()->total_length();
                size_t new_pos = content_->get_word_boundary_right(cur_pos);

                // If we stopped at end of line (at newline) and there's more content, skip to next line
                if (new_pos == cur_pos && new_pos < doc_len) {
                    // We're likely at a newline - skip it and find next word
                    new_pos = content_->get_word_boundary_right(cur_pos + 1);
                } else if (new_pos < doc_len) {
                    // Check if we stopped at a newline
                    char buf[2];
                    content_->document()->content()->get_text(new_pos, buf, 1);
                    if (buf[0] == '\n' && new_pos + 1 < doc_len) {
                        // Skip the newline and continue
                        new_pos = content_->get_word_boundary_right(new_pos + 1);
                    }
                }

                handle_selection(new_pos);
                content_->move_cursor_to(new_pos);
            } else {
                // Right arrow: Move one character right
                size_t new_line = line, new_col = col;
                size_t line_len = content_->get_line_length_in_columns(line);
                if (col < line_len) {
                    new_col = col + 1;
                } else if (line < line_count) {
                    // Wrap to start of next line
                    new_line = line + 1;
                    new_col = 0;
                }
                size_t new_pos = content_->line_column_to_byte_pos(new_line, new_col);
                handle_selection(new_pos);
                content_->move_cursor_to_line_column(new_line, new_col);
            }
            return true;

        case VK_UP:
            if (ctrl && !shift) {
                // Ctrl+Up: Scroll up without moving cursor
                float scroll_y = content_->scroll_y_;
                content_->set_scroll_y(scroll_y - ContentConfig::LINE_HEIGHT);
                update_scrollbar_geometry();
                set_dirty();
            } else {
                // Up arrow: Move to previous line
                if (line > 1) {
                    // Use preferred column to maintain horizontal position
                    size_t target_col = content_->cursor_preferred_column_;
                    size_t prev_len = content_->get_line_length_in_columns(line - 1);
                    if (target_col > prev_len) target_col = prev_len;
                    size_t new_pos = content_->line_column_to_byte_pos(line - 1, target_col);
                    handle_selection(new_pos);
                    content_->move_cursor_to_line_column(line - 1, target_col);
                    // Restore preferred column (move_cursor_to_line_column updates it)
                    content_->cursor_preferred_column_ = col;
                }
            }
            return true;

        case VK_DOWN:
            if (ctrl && !shift) {
                // Ctrl+Down: Scroll down without moving cursor
                float scroll_y = content_->scroll_y_;
                content_->set_scroll_y(scroll_y + ContentConfig::LINE_HEIGHT);
                update_scrollbar_geometry();
                set_dirty();
            } else {
                // Down arrow: Move to next line
                if (line < line_count) {
                    // Use preferred column to maintain horizontal position
                    size_t target_col = content_->cursor_preferred_column_;
                    size_t next_len = content_->get_line_length_in_columns(line + 1);
                    if (target_col > next_len) target_col = next_len;
                    size_t new_pos = content_->line_column_to_byte_pos(line + 1, target_col);
                    handle_selection(new_pos);
                    content_->move_cursor_to_line_column(line + 1, target_col);
                    // Restore preferred column
                    content_->cursor_preferred_column_ = col;
                }
            }
            return true;

        case VK_HOME:
            {
                size_t new_line, new_col;
                if (ctrl) {
                    // Ctrl+Home: Move to document start
                    new_line = 1;
                    new_col = 0;
                } else {
                    // Home: Move to start of line
                    new_line = line;
                    new_col = 0;
                }
                size_t new_pos = content_->line_column_to_byte_pos(new_line, new_col);
                handle_selection(new_pos);
                content_->move_cursor_to_line_column(new_line, new_col);
            }
            return true;

        case VK_END:
            {
                size_t new_line, new_col;
                if (ctrl) {
                    // Ctrl+End: Move to document end
                    new_line = line_count;
                    new_col = content_->get_line_length_in_columns(line_count);
                } else {
                    // End: Move to end of line
                    new_line = line;
                    new_col = content_->get_line_length_in_columns(line);
                }
                size_t new_pos = content_->line_column_to_byte_pos(new_line, new_col);
                handle_selection(new_pos);
                content_->move_cursor_to_line_column(new_line, new_col);
            }
            return true;

        case VK_PRIOR:  // Page Up
            {
                size_t lines_per_page = static_cast<size_t>(content_->rect.height / ContentConfig::LINE_HEIGHT);
                if (lines_per_page < 1) lines_per_page = 1;
                size_t new_line = (line > lines_per_page) ? (line - lines_per_page) : 1;
                size_t new_len = content_->get_line_length_in_columns(new_line);
                size_t new_col = (col > new_len) ? new_len : col;
                size_t new_pos = content_->line_column_to_byte_pos(new_line, new_col);
                handle_selection(new_pos);
                content_->move_cursor_to_line_column(new_line, new_col);
            }
            return true;

        case VK_NEXT:  // Page Down
            {
                size_t lines_per_page = static_cast<size_t>(content_->rect.height / ContentConfig::LINE_HEIGHT);
                if (lines_per_page < 1) lines_per_page = 1;
                size_t new_line = line + lines_per_page;
                if (new_line > line_count) new_line = line_count;
                size_t new_len = content_->get_line_length_in_columns(new_line);
                size_t new_col = (col > new_len) ? new_len : col;
                size_t new_pos = content_->line_column_to_byte_pos(new_line, new_col);
                handle_selection(new_pos);
                content_->move_cursor_to_line_column(new_line, new_col);
            }
            return true;

        case 'A':
            if (ctrl) {
                // Ctrl+A: Select all
                content_->select_all();
                return true;
            }
            break;

        case 'C':
            if (ctrl) {
                // Ctrl+C: Copy selection to clipboard
                if (!content_->has_selection()) return true;  // Nothing to copy

                size_t text_len = 0;
                char* utf8_text = content_->get_selected_text(&text_len);
                if (!utf8_text) return true;

                // Convert UTF-8 to UTF-16 for clipboard
                int wide_len = MultiByteToWideChar(CP_UTF8, 0, utf8_text, (int)text_len, nullptr, 0);
                if (wide_len > 0) {
                    if (OpenClipboard(nullptr)) {
                        EmptyClipboard();
                        // Allocate with null terminator
                        HGLOBAL hg = GlobalAlloc(GMEM_MOVEABLE, (wide_len + 1) * sizeof(wchar_t));
                        if (hg) {
                            wchar_t* dst = (wchar_t*)GlobalLock(hg);
                            if (dst) {
                                MultiByteToWideChar(CP_UTF8, 0, utf8_text, (int)text_len, dst, wide_len);
                                dst[wide_len] = L'\0';
                                GlobalUnlock(hg);
                                // SetClipboardData takes ownership on success; on failure we must free
                                if (!SetClipboardData(CF_UNICODETEXT, hg)) {
                                    GlobalFree(hg);
                                }
                            } else {
                                // GlobalLock failed - free the allocation
                                GlobalFree(hg);
                            }
                        }
                        CloseClipboard();
                    }
                }

                delete[] utf8_text;
                return true;
            }
            break;

        case 'X':
            if (ctrl) {
                // Ctrl+X: Cut (copy then delete)
                if (!content_->has_selection()) return true;  // Nothing to cut

                // Flush any pending undo coalescing
                flush_coalesce();

                // Push undo before modification
                size_t byte_pos = content_->cursor_byte_pos();
                document_->content()->push_undo(byte_pos, content_->selection_anchor(),
                                                content_->selection_active());

                // Copy to clipboard first
                size_t text_len = 0;
                char* utf8_text = content_->get_selected_text(&text_len);
                if (utf8_text) {
                    int wide_len = MultiByteToWideChar(CP_UTF8, 0, utf8_text, (int)text_len, nullptr, 0);
                    if (wide_len > 0) {
                        if (OpenClipboard(nullptr)) {
                            EmptyClipboard();
                            HGLOBAL hg = GlobalAlloc(GMEM_MOVEABLE, (wide_len + 1) * sizeof(wchar_t));
                            if (hg) {
                                wchar_t* dst = (wchar_t*)GlobalLock(hg);
                                if (dst) {
                                    MultiByteToWideChar(CP_UTF8, 0, utf8_text, (int)text_len, dst, wide_len);
                                    dst[wide_len] = L'\0';
                                    GlobalUnlock(hg);
                                    // SetClipboardData takes ownership on success; on failure we must free
                                    if (!SetClipboardData(CF_UNICODETEXT, hg)) {
                                        GlobalFree(hg);
                                    }
                                } else {
                                    // GlobalLock failed - free the allocation
                                    GlobalFree(hg);
                                }
                            }
                            CloseClipboard();
                        }
                    }
                    delete[] utf8_text;
                }

                // Delete the selection
                content_->delete_selection();
                gutter_->update_width_for_line_count(content_->line_index_.line_count());
                update_scrollbar_geometry();
                set_dirty();
                return true;
            }
            break;

        case 'V':
            if (ctrl) {
                // Ctrl+V: Paste from clipboard

                // Flush any pending undo coalescing
                flush_coalesce();

                if (!OpenClipboard(nullptr)) return true;

                HANDLE hData = GetClipboardData(CF_UNICODETEXT);
                if (hData) {
                    wchar_t* src = (wchar_t*)GlobalLock(hData);
                    if (src) {
                        // Convert UTF-16 to UTF-8
                        int utf8_len = WideCharToMultiByte(CP_UTF8, 0, src, -1, nullptr, 0, nullptr, nullptr);
                        if (utf8_len > 1) {  // > 1 because includes null terminator
                            char* utf8_text = new (std::nothrow) char[utf8_len];
                            if (utf8_text) {
                                WideCharToMultiByte(CP_UTF8, 0, src, -1, utf8_text, utf8_len, nullptr, nullptr);
                                size_t paste_len = utf8_len - 1;  // Exclude null terminator

                                // Push undo before modification
                                size_t byte_pos = content_->cursor_byte_pos();
                                document_->content()->push_undo(byte_pos, content_->selection_anchor(),
                                                                content_->selection_active());

                                // Delete selection first if present
                                if (content_->has_selection()) {
                                    byte_pos = content_->delete_selection();
                                }

                                // Two-pass newline counting: first count, then allocate exact size
                                int newlines_added = 0;
                                for (size_t i = 0; i < paste_len; i++) {
                                    if (utf8_text[i] == '\n') newlines_added++;
                                }

                                // Allocate exact size for newline offsets
                                size_t* newline_offsets = nullptr;
                                if (newlines_added > 0) {
                                    newline_offsets = new (std::nothrow) size_t[newlines_added];
                                    if (newline_offsets) {
                                        int idx = 0;
                                        for (size_t i = 0; i < paste_len && idx < newlines_added; i++) {
                                            if (utf8_text[i] == '\n') {
                                                newline_offsets[idx++] = i;
                                            }
                                        }
                                    }
                                }

                                // Insert text
                                size_t cursor_line = content_->cursor_line();
                                document_->content()->insert(byte_pos, utf8_text, paste_len);
                                document_->mark_dirty();

                                // Update line index
                                if (newlines_added > 0 && newline_offsets) {
                                    content_->line_index_.update_after_insert(byte_pos, paste_len,
                                        newline_offsets, newlines_added);
                                } else {
                                    content_->line_index_.update_after_insert(byte_pos, paste_len, nullptr, 0);
                                }

                                delete[] newline_offsets;

                                // Invalidate affected lines
                                if (newlines_added > 0) {
                                    size_t last_visible = content_->line_index_.last_visible_line(
                                        content_->scroll_y_, content_->rect.height);
                                    content_->invalidate_lines(cursor_line, last_visible);
                                    content_->invalidate_line_states_from(cursor_line);
                                    content_->update_visible_lines();
                                    gutter_->update_width_for_line_count(content_->line_index_.line_count());
                                } else {
                                    content_->invalidate_line(cursor_line);
                                    content_->invalidate_line_states_from(cursor_line);
                                }

                                // Move cursor to end of pasted text
                                content_->move_cursor_to(byte_pos + paste_len);
                                update_scrollbar_geometry();
                                set_dirty();

                                delete[] utf8_text;
                            }
                        }
                        GlobalUnlock(hData);
                    }
                }
                CloseClipboard();
                return true;
            }
            break;

        case VK_BACK:  // Backspace
            // Flush any pending undo coalescing
            flush_coalesce();

            if (ctrl) {
                // Ctrl+Backspace: Delete word to the left (including any preceding whitespace)

                // Delete selection first if present
                if (content_->has_selection()) {
                    size_t byte_pos = content_->cursor_byte_pos();
                    document_->content()->push_undo(byte_pos, content_->selection_anchor(),
                                                    content_->selection_active());
                    content_->delete_selection();
                    gutter_->update_width_for_line_count(content_->line_index_.line_count());
                    update_scrollbar_geometry();
                    set_dirty();
                    return true;
                }

                size_t cur_pos = content_->cursor_byte_pos();
                if (cur_pos == 0) return true;  // Nothing to delete

                // Check if character before cursor is whitespace (space/tab)
                char prev_char = 0;
                document_->content()->get_text(cur_pos - 1, &prev_char, 1);

                size_t word_start;
                if (prev_char == ' ' || prev_char == '\t') {
                    // Cursor is after whitespace - skip whitespace and delete previous word too
                    // This makes "Hello |" → Ctrl+Backspace delete "Hello " not just " "
                    size_t whitespace_start = cur_pos;
                    while (whitespace_start > 0) {
                        char c;
                        document_->content()->get_text(whitespace_start - 1, &c, 1);
                        if (c != ' ' && c != '\t') break;
                        whitespace_start--;
                    }

                    if (whitespace_start == 0) {
                        // All whitespace from document start - delete it all
                        word_start = 0;
                    } else {
                        // Find word boundary to the left from the char before whitespace
                        word_start = content_->get_word_boundary_left(whitespace_start - 1);
                    }
                } else {
                    // Find word boundary to the left (similar to Ctrl+Left navigation)
                    word_start = content_->get_word_boundary_left(cur_pos - 1);
                }

                // Handle line boundary: if at start of line, delete to end of previous line
                if (word_start == cur_pos && col == 0 && line > 1) {
                    size_t prev_line_end = content_->get_line_end_byte(line - 1);
                    word_start = prev_line_end;
                } else if (word_start == cur_pos && cur_pos > 0) {
                    // Didn't move - delete at least one character
                    word_start = cur_pos - 1;
                }

                if (word_start >= cur_pos) return true;  // Safety check

                size_t delete_len = cur_pos - word_start;

                // Push undo before edit
                document_->content()->push_undo(cur_pos, content_->selection_anchor(),
                                                content_->selection_active());

                // Count newlines in range being deleted
                int newlines_removed = 0;
                char* check_buf = new (std::nothrow) char[delete_len + 1];
                if (check_buf) {
                    size_t got = document_->content()->get_text(word_start, check_buf, delete_len);
                    for (size_t i = 0; i < got; i++) {
                        if (check_buf[i] == '\n') newlines_removed++;
                    }
                    delete[] check_buf;
                }

                // Delete from word_start to cur_pos
                document_->content()->delete_range(word_start, delete_len);
                document_->mark_dirty();

                // Update line index
                content_->line_index_.update_after_delete(word_start, delete_len, newlines_removed);

                // Invalidate affected lines
                if (newlines_removed > 0) {
                    size_t last_visible = content_->line_index_.last_visible_line(
                        content_->scroll_y_, content_->rect.height);
                    size_t invalidate_from = line > newlines_removed ? line - newlines_removed : 1;
                    content_->invalidate_lines(invalidate_from, last_visible);
                    content_->invalidate_line_states_from(invalidate_from);
                    content_->update_visible_lines();
                    gutter_->update_width_for_line_count(content_->line_index_.line_count());
                } else {
                    content_->invalidate_line(line);
                    content_->invalidate_line_states_from(line);
                }

                // Move cursor to deletion start
                content_->move_cursor_to(word_start);
                update_scrollbar_geometry();
                set_dirty();
                return true;
            } else {
                // Regular backspace: delete single character
                size_t byte_pos = content_->cursor_byte_pos();
                if (byte_pos == 0) return true;  // Nothing to delete

                // Push undo before edit (with cursor position and selection for restoration)
                document_->content()->push_undo(byte_pos, content_->selection_anchor(), content_->selection_active());

                // Find UTF-8 character boundary
                size_t delete_start = byte_pos;
                size_t delete_len = 1;

                // Read the character before cursor to determine its byte length
                if (col > 0) {
                    // Simple case: delete one UTF-16 unit (which may be 1-4 UTF-8 bytes)
                    size_t prev_byte_pos = content_->line_column_to_byte_pos(line, col - 1);
                    delete_start = prev_byte_pos;
                    delete_len = byte_pos - prev_byte_pos;
                } else if (line > 1) {
                    // Deleting newline at start of line - join with previous line
                    size_t prev_line_end = content_->get_line_end_byte(line - 1);
                    delete_start = prev_line_end;
                    delete_len = byte_pos - prev_line_end;
                }

                // Count newlines being deleted
                char deleted_text[16];
                size_t read_len = (delete_len < sizeof(deleted_text)) ? delete_len : sizeof(deleted_text) - 1;
                size_t got = document_->content()->get_text(delete_start, deleted_text, read_len);
                int newlines_removed = 0;
                for (size_t i = 0; i < got; i++) {
                    if (deleted_text[i] == '\n') newlines_removed++;
                }

                // Delete the character
                document_->content()->delete_range(delete_start, delete_len);
                document_->mark_dirty();

                // Update line index
                content_->line_index_.update_after_delete(delete_start, delete_len, newlines_removed);

                // Invalidate affected line slots (targeted for performance)
                if (newlines_removed > 0) {
                    // Lines shifted up - invalidate from cursor line to last visible
                    size_t last_visible = content_->line_index_.last_visible_line(
                        content_->scroll_y_, content_->rect.height);
                    size_t invalidate_from = line > 1 ? line - 1 : 1;
                    content_->invalidate_lines(invalidate_from, last_visible);
                    content_->invalidate_line_states_from(invalidate_from);
                    content_->update_visible_lines();  // May need new slots for shifted lines
                    gutter_->update_width_for_line_count(content_->line_index_.line_count());
                } else {
                    // Single character deleted - only current line affected
                    content_->invalidate_line(line);
                    content_->invalidate_line_states_from(line);
                }

                // Move cursor back
                content_->move_cursor_to(delete_start);
            }
            return true;

        case VK_DELETE:
            // Flush any pending undo coalescing
            flush_coalesce();

            if (ctrl) {
                // Ctrl+Delete: Delete word to the right (including any following whitespace)

                // Delete selection first if present
                if (content_->has_selection()) {
                    size_t byte_pos = content_->cursor_byte_pos();
                    document_->content()->push_undo(byte_pos, content_->selection_anchor(),
                                                    content_->selection_active());
                    content_->delete_selection();
                    gutter_->update_width_for_line_count(content_->line_index_.line_count());
                    update_scrollbar_geometry();
                    set_dirty();
                    return true;
                }

                size_t cur_pos = content_->cursor_byte_pos();
                size_t doc_len = document_->content()->total_length();
                if (cur_pos >= doc_len) return true;  // Nothing to delete

                // Check if character at cursor is whitespace (space/tab)
                char cur_char = 0;
                document_->content()->get_text(cur_pos, &cur_char, 1);

                size_t word_end;
                if (cur_char == ' ' || cur_char == '\t') {
                    // Cursor is on whitespace - skip whitespace and delete following word too
                    // This makes "| world" → Ctrl+Delete delete " world" not just " "
                    size_t whitespace_end = cur_pos;
                    while (whitespace_end < doc_len) {
                        char c;
                        document_->content()->get_text(whitespace_end, &c, 1);
                        if (c != ' ' && c != '\t') break;
                        whitespace_end++;
                    }

                    if (whitespace_end >= doc_len) {
                        // All whitespace to document end - delete it all
                        word_end = doc_len;
                    } else {
                        // Find word boundary to the right from the char after whitespace
                        word_end = content_->get_word_boundary_right(whitespace_end);
                    }
                } else {
                    // Find word boundary to the right (similar to Ctrl+Right navigation)
                    word_end = content_->get_word_boundary_right(cur_pos);

                    // Also include any trailing whitespace (spaces/tabs, not newlines)
                    while (word_end < doc_len) {
                        char c;
                        document_->content()->get_text(word_end, &c, 1);
                        if (c != ' ' && c != '\t') break;
                        word_end++;
                    }
                }

                // Handle newline skipping: if stopped at current position, skip the newline
                if (word_end == cur_pos && cur_pos < doc_len) {
                    word_end = content_->get_word_boundary_right(cur_pos + 1);
                }

                if (word_end <= cur_pos) return true;  // Safety check

                size_t delete_len = word_end - cur_pos;

                // Push undo before edit
                document_->content()->push_undo(cur_pos, content_->selection_anchor(),
                                                content_->selection_active());

                // Count newlines in range being deleted
                int newlines_removed = 0;
                char* check_buf = new (std::nothrow) char[delete_len + 1];
                if (check_buf) {
                    size_t got = document_->content()->get_text(cur_pos, check_buf, delete_len);
                    for (size_t i = 0; i < got; i++) {
                        if (check_buf[i] == '\n') newlines_removed++;
                    }
                    delete[] check_buf;
                }

                // Delete from cur_pos to word_end
                document_->content()->delete_range(cur_pos, delete_len);
                document_->mark_dirty();

                // Update line index
                content_->line_index_.update_after_delete(cur_pos, delete_len, newlines_removed);

                // Invalidate affected lines
                if (newlines_removed > 0) {
                    size_t last_visible = content_->line_index_.last_visible_line(
                        content_->scroll_y_, content_->rect.height);
                    content_->invalidate_lines(line, last_visible);
                    content_->invalidate_line_states_from(line);
                    content_->update_visible_lines();
                    gutter_->update_width_for_line_count(content_->line_index_.line_count());
                } else {
                    content_->invalidate_line(line);
                    content_->invalidate_line_states_from(line);
                }

                // Cursor stays at cur_pos but recalculate
                content_->move_cursor_to(cur_pos);
                update_scrollbar_geometry();
                set_dirty();
                return true;
            } else {
                // Regular delete: delete single character
                size_t byte_pos = content_->cursor_byte_pos();
                size_t doc_len = document_->content()->total_length();
                if (byte_pos >= doc_len) return true;  // Nothing to delete

                // Push undo before edit (with cursor position and selection for restoration)
                document_->content()->push_undo(byte_pos, content_->selection_anchor(), content_->selection_active());

                // Find what we're deleting
                size_t delete_len = 1;
                size_t line_len = content_->get_line_length_in_columns(line);

                if (col < line_len) {
                    // Delete character at cursor
                    size_t next_byte_pos = content_->line_column_to_byte_pos(line, col + 1);
                    delete_len = next_byte_pos - byte_pos;
                } else if (line < line_count) {
                    // At end of line - delete newline, join with next line
                    size_t next_line_start = content_->get_line_start_byte(line + 1);
                    delete_len = next_line_start - byte_pos;
                }

                // Count newlines being deleted
                char deleted_text[16];
                size_t read_len = (delete_len < sizeof(deleted_text)) ? delete_len : sizeof(deleted_text) - 1;
                size_t got = document_->content()->get_text(byte_pos, deleted_text, read_len);
                int newlines_removed = 0;
                for (size_t i = 0; i < got; i++) {
                    if (deleted_text[i] == '\n') newlines_removed++;
                }

                // Delete
                document_->content()->delete_range(byte_pos, delete_len);
                document_->mark_dirty();

                // Update line index
                content_->line_index_.update_after_delete(byte_pos, delete_len, newlines_removed);

                // Invalidate affected line slots (targeted for performance)
                if (newlines_removed > 0) {
                    // Deleting newline - lines merge/shift up
                    size_t last_visible = content_->line_index_.last_visible_line(
                        content_->scroll_y_, content_->rect.height);
                    content_->invalidate_lines(line, last_visible);
                    content_->invalidate_line_states_from(line);
                    content_->update_visible_lines();
                    gutter_->update_width_for_line_count(content_->line_index_.line_count());
                } else {
                    // Single character deleted - only current line affected
                    content_->invalidate_line(line);
                    content_->invalidate_line_states_from(line);
                }

                // Cursor stays in place but recalculate position
                content_->move_cursor_to(byte_pos);
            }
            return true;

        case 'Z':
            if (ctrl) {
                // Ctrl+Z: Undo

                // Flush any pending undo coalescing first
                flush_coalesce();

                if (document_->content()->can_undo()) {
                    // Pass current cursor and selection for redo restoration
                    size_t restored_sel_start = 0, restored_sel_end = 0;
                    size_t restored_pos = document_->content()->undo(
                        content_->cursor_byte_pos(),
                        content_->selection_anchor(), content_->selection_active(),
                        &restored_sel_start, &restored_sel_end);
                    content_->line_index_.build(document_->content());
                    content_->unbind_all_lines();
                    content_->update_visible_lines();
                    gutter_->update_width_for_line_count(content_->line_index_.line_count());
                    content_->move_cursor_to(restored_pos);  // Restore saved cursor
                    // Only set selection if there was one; otherwise clear to preserve cursor
                    if (restored_sel_start != restored_sel_end) {
                        content_->set_selection(restored_sel_start, restored_sel_end);
                    } else {
                        content_->clear_selection();
                    }
                    set_dirty();
                }
                return true;
            }
            break;

        case 'Y':
            if (ctrl) {
                // Ctrl+Y: Redo

                // Flush any pending undo coalescing first
                flush_coalesce();

                if (document_->content()->can_redo()) {
                    size_t restored_sel_start = 0, restored_sel_end = 0;
                    size_t restored_pos = document_->content()->redo(&restored_sel_start, &restored_sel_end);
                    content_->line_index_.build(document_->content());
                    content_->unbind_all_lines();
                    content_->update_visible_lines();
                    gutter_->update_width_for_line_count(content_->line_index_.line_count());
                    content_->move_cursor_to(restored_pos);  // Restore saved cursor
                    // Only set selection if there was one; otherwise clear to preserve cursor
                    if (restored_sel_start != restored_sel_end) {
                        content_->set_selection(restored_sel_start, restored_sel_end);
                    } else {
                        content_->clear_selection();
                    }
                    set_dirty();
                }
                return true;
            }
            break;
    }

    return false;
}

bool CodeEditorWidget::on_char(wchar_t c) {
    if (!content_ || !document_) return false;

    // Filter control characters (except newline, tab)
    if (c < 32 && c != L'\r' && c != L'\n' && c != L'\t') return false;

    // Handle UTF-16 surrogate pairs for non-BMP characters (emojis, etc.)
    // Windows WM_CHAR delivers non-BMP chars as two messages: high then low surrogate
    wchar_t utf16[3] = { c, 0, 0 };
    int utf16_len = 1;

    if (c >= 0xD800 && c <= 0xDBFF) {
        // High surrogate - buffer it and wait for low surrogate
        pending_high_surrogate_ = c;
        return true;
    }

    if (c >= 0xDC00 && c <= 0xDFFF) {
        // Low surrogate - combine with buffered high surrogate
        if (pending_high_surrogate_) {
            utf16[0] = pending_high_surrogate_;
            utf16[1] = c;
            utf16_len = 2;
            pending_high_surrogate_ = 0;
        } else {
            // Orphan low surrogate - ignore
            return false;
        }
    } else {
        // Regular character - clear any stale pending surrogate
        pending_high_surrogate_ = 0;
    }

    // Convert UTF-16 to UTF-8 (WC_ERR_INVALID_CHARS rejects invalid sequences)
    char utf8_buf[8];
    int utf8_len = WideCharToMultiByte(CP_UTF8, WC_ERR_INVALID_CHARS,
                                        utf16, utf16_len,
                                        utf8_buf, sizeof(utf8_buf),
                                        nullptr, nullptr);
    if (utf8_len <= 0) return false;

    // Handle newline: convert CR to LF, or use document's line ending
    int newlines_added = 0;
    bool is_newline = (c == L'\r' || c == L'\n');
    if (is_newline) {
        utf8_buf[0] = '\n';
        utf8_len = 1;
        newlines_added = 1;
    }

    // Handle tab: convert to spaces (4 spaces for now)
    if (c == L'\t') {
        utf8_buf[0] = ' ';
        utf8_buf[1] = ' ';
        utf8_buf[2] = ' ';
        utf8_buf[3] = ' ';
        utf8_len = 4;
    }

    size_t byte_pos = content_->cursor_byte_pos();

    // Undo coalescing: group sequential character inserts
    // - Don't coalesce if there's a selection (we're replacing text)
    // - Don't coalesce newlines (they break the sequence logically)
    // - Don't coalesce if cursor isn't at expected position (user moved cursor)
    bool can_coalesce = coalesce_pending_ &&
                        !content_->has_selection() &&
                        !is_newline &&
                        byte_pos == coalesce_expected_pos_;

    if (!can_coalesce) {
        // Cannot coalesce - flush any pending and start new group
        flush_coalesce();

        // Start new coalesce group - push undo NOW (before any edits)
        // This saves the document state BEFORE this edit sequence
        document_->content()->push_undo(byte_pos, content_->selection_anchor(),
                                        content_->selection_active());
        coalesce_pending_ = true;
        coalesce_expected_pos_ = byte_pos;  // Will be updated after insert
    }

    // Delete selection if any (selection means we're replacing, not coalescing)
    if (content_->has_selection()) {
        byte_pos = content_->delete_selection();
    }

    // Insert the character
    size_t cursor_line = content_->cursor_line();
    document_->content()->insert(byte_pos, utf8_buf, static_cast<size_t>(utf8_len));
    document_->mark_dirty();

    // Update expected position for next coalesce
    coalesce_expected_pos_ = byte_pos + static_cast<size_t>(utf8_len);

    // Restart the coalesce timer (unless it's a newline which breaks coalescing)
    if (is_newline) {
        // Newlines always flush coalescing
        flush_coalesce();
    } else {
        start_coalesce_timer();
    }

    // Update line index
    if (newlines_added > 0) {
        size_t newline_offsets[1] = { 0 };  // Relative offset of newline within inserted text
        content_->line_index_.update_after_insert(byte_pos, static_cast<size_t>(utf8_len),
                                                   newline_offsets, newlines_added);
    } else {
        content_->line_index_.update_after_insert(byte_pos, static_cast<size_t>(utf8_len),
                                                   nullptr, 0);
    }

    // Invalidate affected line slots (targeted for performance)
    if (newlines_added > 0) {
        // Newline inserted - lines shift down
        size_t last_visible = content_->line_index_.last_visible_line(
            content_->scroll_y_, content_->rect.height);
        content_->invalidate_lines(cursor_line, last_visible);
        content_->invalidate_line_states_from(cursor_line);
        content_->update_visible_lines();  // May need new slots for shifted lines
        gutter_->update_width_for_line_count(content_->line_index_.line_count());
    } else {
        // Single character inserted - only current line affected
        content_->invalidate_line(cursor_line);
        content_->invalidate_line_states_from(cursor_line);
    }

    // Move cursor past inserted text
    content_->move_cursor_to(byte_pos + static_cast<size_t>(utf8_len));

    return true;
}

bool CodeEditorWidget::on_focus() {
    if (content_) {
        content_->reset_cursor_blink();
        content_->set_dirty();
    }
    return true;
}

bool CodeEditorWidget::on_blur() {
    // Flush pending undo coalescing when losing focus
    flush_coalesce();

    if (content_) {
        content_->set_dirty();
    }
    return true;
}

// ============================================================================
// Scroll Cache Helpers
// ============================================================================

void CodeEditorWidget::cache_scroll_position() {
    if (!document_ || !content_) return;

    // Look for existing entry for this document
    for (size_t i = 0; i < cache_count_; i++) {
        if (scroll_cache_[i].document == document_) {
            scroll_cache_[i].scroll_x = content_->scroll_x_;
            scroll_cache_[i].scroll_y = content_->scroll_y_;
            return;
        }
    }

    // Add new entry
    if (cache_count_ < EditorConfig::SCROLL_CACHE_SIZE) {
        scroll_cache_[cache_count_].document = document_;
        scroll_cache_[cache_count_].scroll_x = content_->scroll_x_;
        scroll_cache_[cache_count_].scroll_y = content_->scroll_y_;
        cache_count_++;
    } else {
        // LRU eviction: shift everything down, add at end
        memmove(&scroll_cache_[0], &scroll_cache_[1],
                (EditorConfig::SCROLL_CACHE_SIZE - 1) * sizeof(ScrollCacheEntry));
        scroll_cache_[EditorConfig::SCROLL_CACHE_SIZE - 1].document = document_;
        scroll_cache_[EditorConfig::SCROLL_CACHE_SIZE - 1].scroll_x = content_->scroll_x_;
        scroll_cache_[EditorConfig::SCROLL_CACHE_SIZE - 1].scroll_y = content_->scroll_y_;
    }
}

bool CodeEditorWidget::restore_scroll_position() {
    if (!document_ || !content_) return false;

    for (size_t i = 0; i < cache_count_; i++) {
        if (scroll_cache_[i].document == document_) {
            content_->set_scroll_x(scroll_cache_[i].scroll_x);
            content_->set_scroll_y(scroll_cache_[i].scroll_y);
            return true;
        }
    }
    return false;
}

// ============================================================================
// Undo Coalescing Helpers
// ============================================================================

void CodeEditorWidget::flush_coalesce() {
    if (!coalesce_pending_) return;

    // Undo was already pushed when coalesce group started, just clear state
    coalesce_pending_ = false;
    stop_coalesce_timer();
}

void CodeEditorWidget::start_coalesce_timer() {
    if (g_main_window) {
        g_coalesce_timer_owner = this;  // Track which editor owns the timer
        SetTimer(g_main_window, EDITOR_COALESCE_TIMER_ID, EDITOR_COALESCE_MS, nullptr);
    }
}

void CodeEditorWidget::stop_coalesce_timer() {
    if (g_main_window) {
        KillTimer(g_main_window, EDITOR_COALESCE_TIMER_ID);
    }
    if (g_coalesce_timer_owner == this) {
        g_coalesce_timer_owner = nullptr;
    }
}

void CodeEditorWidget::on_coalesce_timer() {
    // Timer expired - push the pending undo snapshot
    flush_coalesce();
}

} // namespace CodeEditor
