// <AUTO-GENERATED TOC> DO NOT EDIT MANUALLY
// Table of Contents
//
// 1. Color Helpers (line 39)
// 2. Cursor Configuration (matching TextInput pattern from ui_theme.h) (line 52)
// 3. ContentWidget Construction/Destruction (line 65)
// 4. Document Management (line 99)
// 5. Scroll Control (line 124)
// 6. Cursor Control (line 172)
// 7. Widget Interface (line 276)
// 8. Cursor Rendering (line 575)
// 9. Cursor Helpers (line 607)
// 10. Internal Methods (line 856)
// 11. Selection Helpers (line 1081)
//
// </AUTO-GENERATED TOC>
// content_widget.cpp - ContentWidget implementation

#include "content_widget.h"
#include "ui_theme.h"  // For SyntaxColors
#include <Windows.h>
#include <d2d1.h>
#include <dwrite.h>
#include <new>  // std::nothrow
#include <cmath>

// External resources (defined in platform.cpp, accessed via unity build)
// Declared in global namespace since that's where platform.cpp defines them
extern IDWriteFactory* g_dwrite_factory;
extern IDWriteTextFormat* g_text_format_mono;
extern EventDispatcher g_event_dispatcher;

// Forward declare Easing functions (defined in ui_widgets_core.cpp)
namespace Easing {
    float ease_out_quad(float t);
}

// Note: syntax_tokenize_line is declared in app.h (already included via content_widget.h)

namespace CodeEditor {

// ============================================================================
// Color Helpers
// ============================================================================

static D2D1_COLOR_F to_color_f(uint32_t argb) {
    return D2D1::ColorF(
        ((argb >> 16) & 0xFF) / 255.0f,
        ((argb >> 8) & 0xFF) / 255.0f,
        (argb & 0xFF) / 255.0f,
        ((argb >> 24) & 0xFF) / 255.0f
    );
}

// ============================================================================
// Cursor Configuration (matching TextInput pattern from ui_theme.h)
// ============================================================================

namespace CursorConfig {
    constexpr float BLINK_PERIOD_MS = 1000.0f;    // Full blink cycle
    constexpr float FADE_MS = 150.0f;             // Fade in/out duration
    constexpr float MOVE_MS = 40.0f;              // Cursor position animation
    constexpr float PAUSE_MS = 500.0f;            // Pause before blink resumes
    constexpr uint32_t CURSOR_COLOR = 0xFFE0E0E0; // Light gray cursor
    constexpr float CURSOR_WIDTH = 2.0f;          // Cursor line width
}

// ============================================================================
// ContentWidget Construction/Destruction
// ============================================================================

// Helper to check if the editor (parent) has focus
static bool editor_has_focus(Widget* parent) {
    return parent && (parent->flags & WidgetFlags::Focused);
}

ContentWidget::ContentWidget() : Widget() {
    debug_name = "CodeEditor::ContentWidget";
    // Note: NOT focusable - parent CodeEditorWidget owns focus
    // Use editor_has_focus(parent) to check focus state for cursor rendering
    line_index_.set_line_height(ContentConfig::LINE_HEIGHT);

    // Heap-allocate line slots (128 slots × ~8KB each = ~1MB - too large for arena's 64KB blocks)
    line_slots_ = new (std::nothrow) LineSlot[ContentConfig::MAX_LINE_SLOTS];
    if (!line_slots_) return;  // Allocation failed

    // Initialize all slots as unbound
    for (size_t i = 0; i < ContentConfig::MAX_LINE_SLOTS; i++) {
        line_slots_[i].line_number = 0;
        line_slots_[i].layout = nullptr;
        line_slots_[i].text[0] = L'\0';
        line_slots_[i].cache_valid = false;
    }
}

ContentWidget::~ContentWidget() {
    unbind_all_lines();
    delete[] line_slots_;
    line_slots_ = nullptr;
    delete[] line_lexer_states_;
    line_lexer_states_ = nullptr;
    line_lexer_states_capacity_ = 0;
    line_lexer_states_count_ = 0;
}

// ============================================================================
// Document Management
// ============================================================================

void ContentWidget::set_document(TextDocument* doc) {
    if (document_ == doc) return;

    // Unbind all current lines
    unbind_all_lines();

    document_ = doc;
    scroll_y_ = 0.0f;
    scroll_x_ = 0.0f;
    max_content_width_ = 0.0f;

    // Free old state array
    delete[] line_lexer_states_;
    line_lexer_states_ = nullptr;
    line_lexer_states_capacity_ = 0;
    line_lexer_states_count_ = 0;

    if (document_) {
        // Build line index
        line_index_.build(document_->content());

        // Allocate and compute line states for O(1) block comment lookup
        size_t line_count = line_index_.line_count();
        if (line_count > 0) {
            line_lexer_states_ = new (std::nothrow) bool[line_count];
            if (line_lexer_states_) {
                line_lexer_states_capacity_ = line_count;
                compute_line_lexer_states();
            }
        }
    } else {
        line_index_.clear();
    }

    set_dirty();
}

// ============================================================================
// Scroll Control
// ============================================================================

void ContentWidget::set_scroll_y(float y) {
    float max_y = max_scroll_y();
    if (y < 0.0f) y = 0.0f;
    if (y > max_y) y = max_y;

    if (scroll_y_ != y) {
        scroll_y_ = y;
        update_visible_lines();
        set_dirty();
    }
}

void ContentWidget::set_scroll_x(float x) {
    float max_x = max_scroll_x();
    if (x < 0.0f) x = 0.0f;
    if (x > max_x) x = max_x;

    if (scroll_x_ != x) {
        scroll_x_ = x;
        set_dirty();
    }
}

float ContentWidget::max_scroll_y() const {
    float content_h = content_height();
    float viewport_h = rect.height;
    if (content_h <= viewport_h) return 0.0f;
    return content_h - viewport_h;
}

float ContentWidget::max_scroll_x() const {
    float viewport_w = rect.width - ContentConfig::PADDING_LEFT - ContentConfig::PADDING_RIGHT;
    if (max_content_width_ <= viewport_w) return 0.0f;
    return max_content_width_ - viewport_w;
}

float ContentWidget::content_height() const {
    return line_index_.total_content_height();
}

float ContentWidget::content_width() const {
    return max_content_width_;
}

// ============================================================================
// Cursor Control
// ============================================================================

void ContentWidget::move_cursor_to(size_t byte_pos) {
    if (!document_) return;

    // Clamp to document bounds
    size_t max_pos = document_->content()->total_length();
    if (byte_pos > max_pos) byte_pos = max_pos;

    cursor_byte_pos_ = byte_pos;

    // Recalculate line/column
    byte_pos_to_line_column(byte_pos, cursor_line_, cursor_column_);

    // Update preferred column (for vertical navigation)
    cursor_preferred_column_ = cursor_column_;

    // Update cursor target X position
    cursor_target_x_ = get_cursor_x_for_column(cursor_line_, cursor_column_);

    // Set current position immediately (animation will smooth subsequent moves)
    cursor_current_x_ = cursor_target_x_;
    cursor_x_initialized_ = true;

    // Reset blink and ensure cursor is visible
    reset_cursor_blink();
    ensure_cursor_visible();
    set_dirty();
}

void ContentWidget::move_cursor_to_line_column(size_t line, size_t col) {
    if (!document_ || line == 0) return;

    // Clamp line to valid range
    size_t line_count = line_index_.line_count();
    if (line_count == 0) {
        cursor_line_ = 1;
        cursor_column_ = 0;
        cursor_byte_pos_ = 0;
        reset_cursor_blink();
        return;
    }

    if (line > line_count) line = line_count;

    // Clamp column to line length
    size_t line_len = get_line_length_in_columns(line);
    if (col > line_len) col = line_len;

    cursor_line_ = line;
    cursor_column_ = col;
    cursor_byte_pos_ = line_column_to_byte_pos(line, col);

    // Update preferred column (for vertical navigation)
    cursor_preferred_column_ = col;

    // Update cursor target X position
    cursor_target_x_ = get_cursor_x_for_column(cursor_line_, cursor_column_);

    // Set current position immediately (animation will smooth subsequent moves)
    cursor_current_x_ = cursor_target_x_;
    cursor_x_initialized_ = true;

    // Reset blink and ensure cursor is visible
    reset_cursor_blink();
    ensure_cursor_visible();
    set_dirty();
}

void ContentWidget::ensure_cursor_visible() {
    // Vertical scrolling: ensure cursor line is visible
    float cursor_y = (cursor_line_ - 1) * ContentConfig::LINE_HEIGHT;
    float viewport_top = scroll_y_;
    float viewport_bottom = scroll_y_ + rect.height;

    if (cursor_y < viewport_top) {
        // Cursor is above viewport - scroll up
        set_scroll_y(cursor_y);
    } else if (cursor_y + ContentConfig::LINE_HEIGHT > viewport_bottom) {
        // Cursor is below viewport - scroll down
        set_scroll_y(cursor_y + ContentConfig::LINE_HEIGHT - rect.height);
    }

    // Horizontal scrolling: ensure cursor column is visible
    float cursor_x = cursor_target_x_;
    float visible_left = scroll_x_;
    float visible_right = scroll_x_ + rect.width - ContentConfig::PADDING_LEFT - ContentConfig::PADDING_RIGHT;
    constexpr float margin = 20.0f;  // Keep cursor this far from edges

    if (cursor_x < visible_left + margin) {
        set_scroll_x(fmaxf(0.0f, cursor_x - margin));
    } else if (cursor_x > visible_right - margin) {
        set_scroll_x(cursor_x - (rect.width - ContentConfig::PADDING_LEFT - ContentConfig::PADDING_RIGHT) + margin);
    }
}

void ContentWidget::reset_cursor_blink() {
    cursor_blink_timer_ = 0.0f;
    cursor_blink_pause_timer_ = CursorConfig::PAUSE_MS / 1000.0f;
    cursor_opacity_ = 1.0f;
}

// ============================================================================
// Widget Interface
// ============================================================================

void ContentWidget::measure(const LayoutConstraints& constraints) {
    // ContentWidget fills available space
    rect.width = constraints.max_width;
    rect.height = constraints.max_height;

    preferred_width = rect.width;
    preferred_height = rect.height;
}

void ContentWidget::layout() {
    // Update visible lines when layout changes
    update_visible_lines();
}

void ContentWidget::render(RenderContext& ctx) {
    if (!line_slots_ || !document_ || line_index_.line_count() == 0) {
        // Render empty background
        D2D1_RECT_F bg_rect = {rect.x, rect.y, rect.x + rect.width, rect.y + rect.height};
        ctx.brush->SetColor(to_color_f(Theme::BG_PRIMARY));
        ctx.target->FillRectangle(bg_rect, ctx.brush);
        return;
    }

    // Clip to widget bounds
    D2D1_RECT_F clip_rect = {rect.x, rect.y, rect.x + rect.width, rect.y + rect.height};
    ctx.push_clip(clip_rect);

    // Background
    ctx.brush->SetColor(to_color_f(Theme::BG_PRIMARY));
    ctx.target->FillRectangle(clip_rect, ctx.brush);

    // Render selection highlight (behind text)
    render_selection(ctx);

    // Text color
    ctx.brush->SetColor(to_color_f(Theme::TEXT_PRIMARY));

    // Render each bound line
    for (size_t i = 0; i < ContentConfig::MAX_LINE_SLOTS; i++) {
        LineSlot& slot = line_slots_[i];
        if (slot.line_number == 0) continue;

        const LineEntry* entry = line_index_.get_line(slot.line_number);
        if (!entry) continue;

        // Calculate Y position (0-indexed line position from top)
        float y = rect.y + (entry->line_number - 1) * ContentConfig::LINE_HEIGHT - scroll_y_;

        // Skip if outside viewport
        if (y + ContentConfig::LINE_HEIGHT < rect.y || y > rect.y + rect.height) continue;

        // Ensure layout exists
        if (!slot.layout || !slot.cache_valid) {
            create_line_layout(slot);
        }

        if (slot.layout) {
            float text_x = rect.x + ContentConfig::PADDING_LEFT - scroll_x_;
            D2D1_POINT_2F text_pos = { text_x, y };

            // Draw base text
            ctx.brush->SetColor(to_color_f(Theme::TEXT_PRIMARY));
            ctx.target->DrawTextLayout(text_pos, slot.layout, ctx.brush);

            // Overlay syntax highlighting
            if (slot.syntax_span_count > 0) {
                // Limit clips per line to prevent pathological performance on lines
                // with excessive tokens (e.g., minified code)
                constexpr UINT32 MAX_SPAN_CLIPS = 32;
                UINT32 clips_drawn = 0;

                for (size_t s = 0; s < slot.syntax_span_count && clips_drawn < MAX_SPAN_CLIPS; s++) {
                    SyntaxSpan* span = &slot.syntax_spans[s];
                    if (span->token == SyntaxToken::Default) continue;

                    uint32_t span_color = SyntaxColors::get_token_color(static_cast<uint8_t>(span->token));

                    // Get metrics for this span
                    DWRITE_HIT_TEST_METRICS metrics[8];
                    UINT32 metric_count = 0;
                    HRESULT hr = slot.layout->HitTestTextRange(
                        span->start, span->length,
                        text_x, y,
                        metrics, 8, &metric_count
                    );

                    if (SUCCEEDED(hr) && metric_count > 0) {
                        ctx.brush->SetColor(to_color_f(span_color));

                        // Draw clipped text for each region
                        for (UINT32 m = 0; m < metric_count && clips_drawn < MAX_SPAN_CLIPS; m++) {
                            // Skip zero-width regions
                            if (metrics[m].width <= 0.001f) continue;

                            D2D1_RECT_F span_clip = D2D1::RectF(
                                metrics[m].left,
                                metrics[m].top,
                                metrics[m].left + metrics[m].width,
                                metrics[m].top + metrics[m].height
                            );

                            ctx.target->PushAxisAlignedClip(span_clip, D2D1_ANTIALIAS_MODE_PER_PRIMITIVE);
                            ctx.target->DrawTextLayout(text_pos, slot.layout, ctx.brush);
                            ctx.target->PopAxisAlignedClip();
                            clips_drawn++;
                        }
                    }
                }
            }
        }
    }

    // Render cursor on top of text and selection
    render_cursor(ctx);

    ctx.pop_clip();
}

void ContentWidget::on_viewport_changed(float vp_top, float vp_bottom) {
    (void)vp_top;
    (void)vp_bottom;
    update_visible_lines();
}

bool ContentWidget::on_mouse_wheel(float x, float y, float delta) {
    (void)x;
    (void)y;
    (void)delta;

    // Don't handle here - let parent CodeEditorWidget handle scrolling
    // so it can also update the scrollbar geometry
    return false;
}

void ContentWidget::tick(float dt) {
    Widget::tick(dt);  // Base class hover animations
    bool needs_redraw = false;

    // === Cursor Position Animation ===
    bool cursor_is_moving = fabsf(cursor_current_x_ - cursor_target_x_) > 0.5f;
    if (cursor_is_moving) {
        float speed = 1000.0f / CursorConfig::MOVE_MS;
        float delta = cursor_target_x_ - cursor_current_x_;
        cursor_current_x_ += delta * fminf(1.0f, speed * dt);
        needs_redraw = true;
    } else {
        cursor_current_x_ = cursor_target_x_;
    }

    // === Cursor Blink Animation ===
    // Only blink when editor is focused, not moving, and pause timer has expired
    if (editor_has_focus(parent)) {
        // Decrement pause timer
        if (cursor_blink_pause_timer_ > 0.0f) {
            cursor_blink_pause_timer_ -= dt;
            // Keep cursor fully visible during pause
            cursor_opacity_ = 1.0f;
            needs_redraw = true;
        } else if (cursor_is_moving) {
            // Cursor is animating - keep fully visible, don't run blink timer
            cursor_opacity_ = 1.0f;
            cursor_blink_timer_ = 0.0f;
            needs_redraw = true;
        } else {
            // Normal blink animation
            cursor_blink_timer_ += dt;
            float period = CursorConfig::BLINK_PERIOD_MS / 1000.0f;
            float fade_time = CursorConfig::FADE_MS / 1000.0f;
            float phase = fmodf(cursor_blink_timer_, period);
            float half_period = period / 2.0f;

            float new_opacity;
            if (phase < fade_time) {
                // Fading out
                new_opacity = 1.0f - Easing::ease_out_quad(phase / fade_time);
            } else if (phase < half_period) {
                // Fully invisible
                new_opacity = 0.0f;
            } else if (phase < half_period + fade_time) {
                // Fading in
                new_opacity = Easing::ease_out_quad((phase - half_period) / fade_time);
            } else {
                // Fully visible
                new_opacity = 1.0f;
            }

            if (fabsf(new_opacity - cursor_opacity_) > 0.01f) {
                cursor_opacity_ = new_opacity;
                needs_redraw = true;
            }
        }
    }

    if (needs_redraw) {
        set_dirty();
    }
}

bool ContentWidget::on_focus() {
    reset_cursor_blink();
    set_dirty();
    return true;
}

bool ContentWidget::on_blur() {
    set_dirty();
    return true;
}

bool ContentWidget::on_key_down(int vk, bool ctrl, bool shift, bool alt) {
    // Delegate to parent CodeEditorWidget
    if (parent) {
        return parent->on_key_down(vk, ctrl, shift, alt);
    }
    return false;
}

bool ContentWidget::on_char(wchar_t c) {
    // Delegate to parent CodeEditorWidget
    if (parent) {
        return parent->on_char(c);
    }
    return false;
}

bool ContentWidget::on_mouse_down(float x, float y, int button) {
    if (button != 0) return false;  // Left click only

    if (!document_ || line_index_.line_count() == 0) return false;

    // Request focus on parent CodeEditorWidget (ContentWidget is not focusable)
    // This ensures the cursor renders and keyboard events are received
    if (parent) {
        g_event_dispatcher.set_focus(parent);
    }

    // Get clicked byte position
    size_t clicked_byte_pos = get_byte_pos_at(x, y);

    // Multi-click detection (double-click word select, triple-click line select)
    uint64_t now = GetTickCount64();
    float click_dist_x = fabsf(x - last_click_x_);
    float click_dist_y = fabsf(y - last_click_y_);
    float click_dist = sqrtf(click_dist_x * click_dist_x + click_dist_y * click_dist_y);

    if ((now - last_click_time_) < SelectionConfig::DOUBLE_CLICK_MS &&
        click_dist < SelectionConfig::DOUBLE_CLICK_DIST) {
        click_count_ = (click_count_ % 3) + 1;  // Cycle 1->2->3->1
    } else {
        click_count_ = 1;
    }
    last_click_time_ = now;
    last_click_x_ = x;
    last_click_y_ = y;

    // Handle shift+click (extend selection)
    bool shift_held = (GetKeyState(VK_SHIFT) & 0x8000) != 0;
    if (shift_held && click_count_ == 1) {
        // Extend selection from anchor to click
        if (selection_start_ == selection_end_) {
            // No existing selection - use current cursor as anchor
            selection_start_ = cursor_byte_pos_;
        }
        selection_end_ = clicked_byte_pos;
        move_cursor_to(clicked_byte_pos);
        // Don't start drag for shift+click
        return true;
    }

    // Handle click count
    if (click_count_ == 1) {
        // Single click: position cursor, clear selection, start drag
        move_cursor_to(clicked_byte_pos);
        selection_start_ = clicked_byte_pos;
        selection_end_ = clicked_byte_pos;
        drag_anchor_pos_ = clicked_byte_pos;
        is_dragging_ = true;
    } else if (click_count_ == 2) {
        // Double-click: select word
        select_word_at(clicked_byte_pos);
        drag_anchor_pos_ = selection_start_;
        is_dragging_ = true;  // Allow word-level drag
    } else if (click_count_ == 3) {
        // Triple-click: select entire line
        size_t line, col;
        byte_pos_to_line_column(clicked_byte_pos, line, col);
        select_line(line);
        is_dragging_ = false;  // No drag for triple-click
    }

    return true;  // Consume the click
}

bool ContentWidget::on_mouse_move(float x, float y) {
    if (!is_dragging_) return false;
    if (!document_) return false;

    // Get byte position at current mouse location
    size_t pos = get_byte_pos_at(x, y);

    if (click_count_ == 2) {
        // Word-level drag: extend selection by words
        size_t word_start = get_word_boundary_left(pos);
        size_t word_end = get_word_boundary_right(pos);

        if (pos < drag_anchor_pos_) {
            // Dragging left of anchor
            selection_start_ = word_start;
            selection_end_ = get_word_boundary_right(drag_anchor_pos_);
        } else {
            // Dragging right of anchor
            selection_start_ = get_word_boundary_left(drag_anchor_pos_);
            selection_end_ = word_end;
        }
        cursor_byte_pos_ = (pos < drag_anchor_pos_) ? selection_start_ : selection_end_;
    } else {
        // Character-level drag
        selection_start_ = drag_anchor_pos_;
        selection_end_ = pos;
        cursor_byte_pos_ = pos;
    }

    // Update cursor visual position
    byte_pos_to_line_column(cursor_byte_pos_, cursor_line_, cursor_column_);
    cursor_target_x_ = get_cursor_x_for_column(cursor_line_, cursor_column_);
    cursor_current_x_ = cursor_target_x_;  // Snap during drag (no animation)
    reset_cursor_blink();
    ensure_cursor_visible();
    set_dirty();

    return true;
}

bool ContentWidget::on_mouse_up(float x, float y, int button) {
    (void)x;
    (void)y;
    if (button == 0) {
        is_dragging_ = false;
    }
    return false;  // Don't consume - let parent also handle if needed
}

// ============================================================================
// Cursor Rendering
// ============================================================================

void ContentWidget::render_cursor(RenderContext& ctx) {
    // Only render cursor if editor is focused and cursor is visible
    if (!editor_has_focus(parent) || cursor_opacity_ < 0.01f) return;
    if (!document_) return;

    // Check if cursor line is visible
    size_t first_visible = line_index_.first_visible_line(scroll_y_);
    size_t last_visible = line_index_.last_visible_line(scroll_y_, rect.height);
    if (cursor_line_ < first_visible || cursor_line_ > last_visible) return;

    // Calculate cursor screen position
    float cursor_y = rect.y + (cursor_line_ - 1) * ContentConfig::LINE_HEIGHT - scroll_y_;
    float cursor_x = rect.x + ContentConfig::PADDING_LEFT + cursor_current_x_ - scroll_x_;

    // Draw cursor line with opacity
    D2D1_COLOR_F cursor_color = to_color_f(CursorConfig::CURSOR_COLOR);
    cursor_color.a *= cursor_opacity_;
    ctx.brush->SetColor(cursor_color);

    D2D1_RECT_F cursor_rect = {
        cursor_x,
        cursor_y,
        cursor_x + CursorConfig::CURSOR_WIDTH,
        cursor_y + ContentConfig::LINE_HEIGHT
    };
    ctx.target->FillRectangle(cursor_rect, ctx.brush);
}

// ============================================================================
// Cursor Helpers
// ============================================================================

float ContentWidget::get_cursor_x_for_column(size_t line, size_t col) {
    if (!document_ || line == 0 || col == 0) return 0.0f;

    // Get the text layout for this line
    size_t slot_idx = find_slot_for_line(line);
    if (slot_idx >= ContentConfig::MAX_LINE_SLOTS) {
        // Line not currently bound - need to calculate from scratch
        // For now, estimate based on average character width
        return static_cast<float>(col) * 8.0f;  // Rough estimate
    }

    LineSlot& slot = line_slots_[slot_idx];
    if (!slot.layout) {
        create_line_layout(slot);
    }

    if (slot.layout && col > 0) {
        // Use DirectWrite to get exact position
        FLOAT x, y;
        DWRITE_HIT_TEST_METRICS metrics;
        HRESULT hr = slot.layout->HitTestTextPosition(
            static_cast<UINT32>(col - 1),  // 0-indexed position before cursor
            TRUE,                           // trailing edge
            &x, &y, &metrics);
        if (SUCCEEDED(hr)) {
            return x;
        }
    }

    return 0.0f;
}

void ContentWidget::byte_pos_to_line_column(size_t byte_pos, size_t& out_line, size_t& out_col) {
    if (!document_) {
        out_line = 1;
        out_col = 0;
        return;
    }

    // Use LineIndex to find line containing byte position
    out_line = line_index_.byte_to_line(byte_pos);
    if (out_line == 0) out_line = 1;

    // Calculate column within line
    size_t line_start = get_line_start_byte(out_line);
    size_t offset_in_line = byte_pos - line_start;

    if (offset_in_line == 0) {
        out_col = 0;
        return;
    }

    // Process in chunks to handle long lines without fixed-size limit
    constexpr size_t CHUNK_SIZE = 512;
    char chunk[CHUNK_SIZE];
    size_t utf16_count = 0;
    size_t remaining = offset_in_line;
    size_t pos = line_start;

    while (remaining > 0) {
        size_t to_read = (remaining < CHUNK_SIZE) ? remaining : CHUNK_SIZE;
        size_t read = document_->content()->get_text(pos, chunk, to_read);
        if (read == 0) break;

        // Count UTF-16 code units by walking UTF-8 bytes
        size_t bytes_consumed = 0;
        for (size_t i = 0; i < read; ) {
            unsigned char c = static_cast<unsigned char>(chunk[i]);
            size_t char_bytes;
            if ((c & 0x80) == 0) { char_bytes = 1; utf16_count += 1; }
            else if ((c & 0xE0) == 0xC0) { char_bytes = 2; utf16_count += 1; }
            else if ((c & 0xF0) == 0xE0) { char_bytes = 3; utf16_count += 1; }
            else if ((c & 0xF8) == 0xF0) { char_bytes = 4; utf16_count += 2; }  // Surrogate pair
            else { char_bytes = 1; }  // Invalid byte, skip

            // Check for incomplete multi-byte sequence at chunk boundary
            if (i + char_bytes > read) break;

            i += char_bytes;
            bytes_consumed = i;
        }
        pos += bytes_consumed;
        remaining -= bytes_consumed;

        // If we consumed nothing, we have an invalid/stuck state - advance one byte
        if (bytes_consumed == 0 && read > 0) {
            pos++;
            remaining--;
        }
    }
    out_col = utf16_count;
}

size_t ContentWidget::line_column_to_byte_pos(size_t line, size_t col) {
    if (!document_ || line == 0) return 0;

    size_t line_start = get_line_start_byte(line);
    if (col == 0) return line_start;

    size_t line_end = get_line_end_byte(line);
    size_t line_len = line_end - line_start;
    if (line_len == 0) return line_start;

    // Process in chunks to handle long lines without fixed-size limit
    constexpr size_t CHUNK_SIZE = 512;
    char chunk[CHUNK_SIZE];
    size_t byte_offset = 0;
    size_t utf16_count = 0;
    size_t remaining = line_len;
    size_t pos = line_start;

    while (remaining > 0 && utf16_count < col) {
        size_t to_read = (remaining < CHUNK_SIZE) ? remaining : CHUNK_SIZE;
        size_t read = document_->content()->get_text(pos, chunk, to_read);
        if (read == 0) break;

        // Walk through UTF-8 bytes counting UTF-16 code units until we reach target column
        size_t bytes_consumed = 0;
        for (size_t i = 0; i < read && utf16_count < col; ) {
            unsigned char c = static_cast<unsigned char>(chunk[i]);
            size_t char_bytes;
            size_t utf16_units;

            if ((c & 0x80) == 0) { char_bytes = 1; utf16_units = 1; }
            else if ((c & 0xE0) == 0xC0) { char_bytes = 2; utf16_units = 1; }
            else if ((c & 0xF0) == 0xE0) { char_bytes = 3; utf16_units = 1; }
            else if ((c & 0xF8) == 0xF0) { char_bytes = 4; utf16_units = 2; }  // Surrogate pair
            else { char_bytes = 1; utf16_units = 0; }  // Invalid byte

            // Check for incomplete multi-byte sequence at chunk boundary
            if (i + char_bytes > read) break;

            i += char_bytes;
            bytes_consumed = i;
            byte_offset += char_bytes;
            utf16_count += utf16_units;
        }
        pos += bytes_consumed;
        remaining -= bytes_consumed;

        // If we consumed nothing, we have an invalid/stuck state - advance one byte
        if (bytes_consumed == 0 && read > 0) {
            pos++;
            remaining--;
        }
    }

    return line_start + byte_offset;
}

size_t ContentWidget::get_line_length_in_columns(size_t line) {
    if (!document_ || line == 0) return 0;

    size_t line_start = get_line_start_byte(line);
    size_t line_end = get_line_end_byte(line);
    size_t line_len = line_end - line_start;

    if (line_len == 0) return 0;

    // Process in chunks to handle long lines without fixed-size limit
    constexpr size_t CHUNK_SIZE = 512;
    char chunk[CHUNK_SIZE];
    size_t utf16_count = 0;
    size_t remaining = line_len;
    size_t pos = line_start;

    while (remaining > 0) {
        size_t to_read = (remaining < CHUNK_SIZE) ? remaining : CHUNK_SIZE;
        size_t read = document_->content()->get_text(pos, chunk, to_read);
        if (read == 0) break;

        // Count UTF-16 code units by walking UTF-8 bytes
        size_t bytes_consumed = 0;
        for (size_t i = 0; i < read; ) {
            unsigned char c = static_cast<unsigned char>(chunk[i]);
            size_t char_bytes;
            if ((c & 0x80) == 0) { char_bytes = 1; utf16_count += 1; }
            else if ((c & 0xE0) == 0xC0) { char_bytes = 2; utf16_count += 1; }
            else if ((c & 0xF0) == 0xE0) { char_bytes = 3; utf16_count += 1; }
            else if ((c & 0xF8) == 0xF0) { char_bytes = 4; utf16_count += 2; }  // Surrogate pair
            else { char_bytes = 1; }  // Invalid byte, skip

            // Check for incomplete multi-byte sequence at chunk boundary
            if (i + char_bytes > read) break;

            i += char_bytes;
            bytes_consumed = i;
        }
        pos += bytes_consumed;
        remaining -= bytes_consumed;

        // If we consumed nothing, we have an invalid/stuck state - advance one byte
        if (bytes_consumed == 0 && read > 0) {
            pos++;
            remaining--;
        }
    }
    return utf16_count;
}

size_t ContentWidget::get_line_start_byte(size_t line) {
    const LineEntry* entry = line_index_.get_line(line);
    return entry ? entry->byte_offset : 0;
}

size_t ContentWidget::get_line_end_byte(size_t line) {
    if (!document_) return 0;

    // Get start of next line (or document end)
    size_t next_line_start;
    if (line < line_index_.line_count()) {
        const LineEntry* next = line_index_.get_line(line + 1);
        next_line_start = next ? next->byte_offset : document_->content()->total_length();
    } else {
        next_line_start = document_->content()->total_length();
    }

    // Line end is before newline character(s)
    size_t line_start = get_line_start_byte(line);
    if (next_line_start <= line_start) return line_start;

    size_t line_end = next_line_start;

    // Check for newline characters and exclude them
    if (line_end > line_start) {
        char buf[2] = {0, 0};
        // Check last char before next line start
        document_->content()->get_text(line_end - 1, buf, 1);
        if (buf[0] == '\n') {
            line_end--;
            // Check for CRLF
            if (line_end > line_start) {
                document_->content()->get_text(line_end - 1, buf, 1);
                if (buf[0] == '\r') {
                    line_end--;
                }
            }
        } else if (buf[0] == '\r') {
            line_end--;
        }
    }

    return line_end;
}

// ============================================================================
// Internal Methods
// ============================================================================

void ContentWidget::bind_line(size_t slot_index, size_t line_number) {
    if (!line_slots_) return;
    if (slot_index >= ContentConfig::MAX_LINE_SLOTS) return;
    if (!document_ || line_number == 0 || line_number > line_index_.line_count()) return;

    LineSlot& slot = line_slots_[slot_index];

    // Release old layout if any
    if (slot.layout) {
        slot.layout->Release();
        slot.layout = nullptr;
    }

    slot.line_number = line_number;
    slot.cache_valid = false;

    // Get line text from document
    const LineEntry* entry = line_index_.get_line(line_number);
    if (!entry) return;

    // Calculate line length
    size_t line_end;
    if (line_number < line_index_.line_count()) {
        const LineEntry* next = line_index_.get_line(line_number + 1);
        line_end = next ? next->byte_offset : document_->content()->total_length();
    } else {
        line_end = document_->content()->total_length();
    }

    size_t line_len = line_end - entry->byte_offset;

    // Read line content
    char utf8_buf[ContentConfig::LINE_TEXT_BUFFER];
    size_t to_read = (line_len < sizeof(utf8_buf) - 1) ? line_len : sizeof(utf8_buf) - 1;
    size_t read = document_->content()->get_text(entry->byte_offset, utf8_buf, to_read);
    utf8_buf[read] = '\0';

    // Strip trailing newlines
    while (read > 0 && (utf8_buf[read - 1] == '\n' || utf8_buf[read - 1] == '\r')) {
        utf8_buf[--read] = '\0';
    }

    // Convert to UTF-16
    int wide_len = MultiByteToWideChar(CP_UTF8, 0, utf8_buf, -1, slot.text, ContentConfig::LINE_TEXT_BUFFER);
    if (wide_len <= 0) {
        slot.text[0] = L'\0';
    }

    // Tokenize for syntax highlighting
    tokenize_line(&slot, line_number);
}

void ContentWidget::compute_line_lexer_states() {
    if (!document_ || !line_lexer_states_) return;

    FileType ft = document_->file_type();
    // Only C-style languages have block comments
    bool has_block_comments = (ft == FileType::Cpp || ft == FileType::Header ||
                               ft == FileType::CSharp || ft == FileType::Xaml);

    size_t line_count = line_index_.line_count();
    line_lexer_states_count_ = (line_count < line_lexer_states_capacity_) ? line_count : line_lexer_states_capacity_;

    bool in_block_comment = false;

    for (size_t ln = 1; ln <= line_lexer_states_count_; ln++) {
        // Store state for this line (whether it starts inside a block comment)
        line_lexer_states_[ln - 1] = in_block_comment;

        if (!has_block_comments) continue;

        // Get line content to update state for next line
        const LineEntry* entry = line_index_.get_line(ln);
        if (!entry) continue;

        size_t line_end;
        if (ln < line_count) {
            const LineEntry* next = line_index_.get_line(ln + 1);
            line_end = next ? next->byte_offset : document_->content()->total_length();
        } else {
            line_end = document_->content()->total_length();
        }

        size_t line_len = line_end - entry->byte_offset;
        char buf[ContentConfig::LINE_TEXT_BUFFER];
        size_t to_read = (line_len < sizeof(buf) - 1) ? line_len : sizeof(buf) - 1;
        size_t read = document_->content()->get_text(entry->byte_offset, buf, to_read);
        buf[read] = '\0';

        // Scan for block comment start/end to update state for next line
        const char* p = buf;
        while (*p) {
            if (!in_block_comment && p[0] == '/' && p[1] == '*') {
                in_block_comment = true;
                p += 2;
            } else if (in_block_comment && p[0] == '*' && p[1] == '/') {
                in_block_comment = false;
                p += 2;
            } else {
                p++;
            }
        }
    }
}

void ContentWidget::invalidate_line_states_from(size_t line_number) {
    if (!line_lexer_states_ || line_number == 0) return;

    // Check if line count has changed and resize array if needed
    size_t current_line_count = line_index_.line_count();
    if (current_line_count != line_lexer_states_count_) {
        // Line count changed - need to resize the array
        bool* new_array = new (std::nothrow) bool[current_line_count];
        if (!new_array) return;

        delete[] line_lexer_states_;
        line_lexer_states_ = new_array;
        line_lexer_states_capacity_ = current_line_count;

        // Recompute all states from scratch
        compute_line_lexer_states();
        return;
    }

    if (line_number > line_lexer_states_count_) return;

    // Recompute from line_number to end
    FileType ft = document_->file_type();
    bool has_block_comments = (ft == FileType::Cpp || ft == FileType::Header ||
                               ft == FileType::CSharp || ft == FileType::Xaml);

    // Get the state at the start of the invalidated line
    bool in_block_comment = (line_number > 1) ? line_lexer_states_[line_number - 2] : false;

    for (size_t ln = line_number; ln <= line_lexer_states_count_; ln++) {
        bool old_state = line_lexer_states_[ln - 1];
        line_lexer_states_[ln - 1] = in_block_comment;

        // If state changed, we need to re-tokenize this line
        if (old_state != in_block_comment) {
            invalidate_line_syntax(ln);
        }

        if (!has_block_comments) continue;

        // Get line content to update state for next line
        const LineEntry* entry = line_index_.get_line(ln);
        if (!entry) continue;

        size_t line_end;
        if (ln < line_index_.line_count()) {
            const LineEntry* next = line_index_.get_line(ln + 1);
            line_end = next ? next->byte_offset : document_->content()->total_length();
        } else {
            line_end = document_->content()->total_length();
        }

        size_t line_len = line_end - entry->byte_offset;
        char buf[ContentConfig::LINE_TEXT_BUFFER];
        size_t to_read = (line_len < sizeof(buf) - 1) ? line_len : sizeof(buf) - 1;
        size_t read = document_->content()->get_text(entry->byte_offset, buf, to_read);
        buf[read] = '\0';

        const char* p = buf;
        while (*p) {
            if (!in_block_comment && p[0] == '/' && p[1] == '*') {
                in_block_comment = true;
                p += 2;
            } else if (in_block_comment && p[0] == '*' && p[1] == '/') {
                in_block_comment = false;
                p += 2;
            } else {
                p++;
            }
        }
    }
}

void ContentWidget::tokenize_line(LineSlot* slot, size_t line_number) {
    if (!slot || !document_) return;

    // Clear existing spans
    slot->syntax_span_count = 0;

    // Check if we have a file type to tokenize
    FileType ft = document_->file_type();
    if (ft == FileType::Unknown) return;

    // Get line text (reuse the already-converted UTF-8 from bind_line)
    const LineEntry* entry = line_index_.get_line(line_number);
    if (!entry) return;

    // Calculate line length
    size_t line_end;
    if (line_number < line_index_.line_count()) {
        const LineEntry* next = line_index_.get_line(line_number + 1);
        line_end = next ? next->byte_offset : document_->content()->total_length();
    } else {
        line_end = document_->content()->total_length();
    }

    size_t line_len = line_end - entry->byte_offset;

    // Read line content (need fresh copy for tokenization)
    char utf8_buf[ContentConfig::LINE_TEXT_BUFFER];
    size_t to_read = (line_len < sizeof(utf8_buf) - 1) ? line_len : sizeof(utf8_buf) - 1;
    size_t read = document_->content()->get_text(entry->byte_offset, utf8_buf, to_read);
    utf8_buf[read] = '\0';

    // Strip trailing newlines for tokenization
    while (read > 0 && (utf8_buf[read - 1] == '\n' || utf8_buf[read - 1] == '\r')) {
        utf8_buf[--read] = '\0';
    }

    // O(1) lookup of block comment state from pre-computed array
    bool state = false;
    if (line_number > 1 && line_lexer_states_ && line_number <= line_lexer_states_count_ + 1) {
        state = line_lexer_states_[line_number - 2];
    }

    // Now tokenize this line with the computed state
    slot->in_block_comment = state;
    slot->syntax_span_count = syntax_tokenize_line(
        utf8_buf,
        ft,
        slot->syntax_spans,
        Syntax::MAX_SPANS_PER_LINE,
        &slot->in_block_comment
    );
}

void ContentWidget::invalidate_line_syntax(size_t line_number) {
    if (!line_slots_ || line_number == 0) return;

    size_t slot_idx = find_slot_for_line(line_number);
    if (slot_idx < ContentConfig::MAX_LINE_SLOTS) {
        LineSlot& slot = line_slots_[slot_idx];
        slot.syntax_span_count = 0;  // Force re-tokenization
        // Re-tokenize immediately if the slot is bound
        if (slot.line_number == line_number) {
            tokenize_line(&slot, line_number);
        }
    }
}

void ContentWidget::unbind_line(size_t slot_index) {
    if (!line_slots_) return;
    if (slot_index >= ContentConfig::MAX_LINE_SLOTS) return;

    LineSlot& slot = line_slots_[slot_index];
    if (slot.layout) {
        slot.layout->Release();
        slot.layout = nullptr;
    }
    slot.line_number = 0;
    slot.text[0] = L'\0';
    slot.cache_valid = false;
    slot.actual_width = 0.0f;
    slot.syntax_span_count = 0;
    slot.in_block_comment = false;
}

void ContentWidget::unbind_all_lines() {
    if (!line_slots_) return;
    for (size_t i = 0; i < ContentConfig::MAX_LINE_SLOTS; i++) {
        unbind_line(i);
    }
    max_content_width_ = 0.0f;
}

void ContentWidget::recalculate_max_content_width() {
    if (!line_slots_) return;

    max_content_width_ = 0.0f;
    for (size_t i = 0; i < ContentConfig::MAX_LINE_SLOTS; i++) {
        if (line_slots_[i].line_number != 0) {
            // Ensure layout exists to get accurate width
            if (!line_slots_[i].layout || !line_slots_[i].cache_valid) {
                create_line_layout(line_slots_[i]);
            }
            if (line_slots_[i].actual_width > max_content_width_) {
                max_content_width_ = line_slots_[i].actual_width;
            }
        }
    }
}

void ContentWidget::invalidate_line(size_t line_number) {
    if (!line_slots_ || line_number == 0) return;

    size_t slot_idx = find_slot_for_line(line_number);
    if (slot_idx < ContentConfig::MAX_LINE_SLOTS) {
        // Found the slot - release layout and mark for rebuild
        LineSlot& slot = line_slots_[slot_idx];
        if (slot.layout) {
            slot.layout->Release();
            slot.layout = nullptr;
        }
        slot.cache_valid = false;
        // Rebind the line to refresh text content
        bind_line(slot_idx, line_number);
    }
    set_dirty();
}

void ContentWidget::invalidate_lines(size_t from_line, size_t to_line) {
    if (!line_slots_ || from_line == 0 || to_line < from_line) return;

    for (size_t ln = from_line; ln <= to_line; ln++) {
        size_t slot_idx = find_slot_for_line(ln);
        if (slot_idx < ContentConfig::MAX_LINE_SLOTS) {
            LineSlot& slot = line_slots_[slot_idx];
            if (slot.layout) {
                slot.layout->Release();
                slot.layout = nullptr;
            }
            slot.cache_valid = false;
            bind_line(slot_idx, ln);
        }
    }
    set_dirty();
}

void ContentWidget::update_visible_lines() {
    if (!line_slots_ || !document_ || line_index_.line_count() == 0) return;

    size_t first = line_index_.first_visible_line(scroll_y_);
    size_t last = line_index_.last_visible_line(scroll_y_, rect.height);

    // Clamp to valid range
    if (first < 1) first = 1;
    if (last > line_index_.line_count()) last = line_index_.line_count();

    // Unbind lines no longer visible
    for (size_t i = 0; i < ContentConfig::MAX_LINE_SLOTS; i++) {
        size_t ln = line_slots_[i].line_number;
        if (ln != 0 && (ln < first || ln > last)) {
            unbind_line(i);
        }
    }

    // Bind newly visible lines
    for (size_t ln = first; ln <= last; ln++) {
        // Check if already bound
        size_t existing = find_slot_for_line(ln);
        if (existing < ContentConfig::MAX_LINE_SLOTS) continue;

        // Find free slot
        size_t free_slot = find_free_slot();
        if (free_slot < ContentConfig::MAX_LINE_SLOTS) {
            bind_line(free_slot, ln);
        }
    }

    // Recalculate max content width from all bound slots
    recalculate_max_content_width();
}

void ContentWidget::create_line_layout(LineSlot& slot) {
    if (!g_dwrite_factory || !g_text_format_mono) return;

    // Release old layout
    if (slot.layout) {
        slot.layout->Release();
        slot.layout = nullptr;
    }

    UINT32 text_len = static_cast<UINT32>(wcslen(slot.text));
    if (text_len == 0) {
        slot.cache_valid = true;
        slot.actual_width = 0.0f;
        return;
    }

    // Create layout with large max width (we handle horizontal scroll ourselves)
    HRESULT hr = g_dwrite_factory->CreateTextLayout(
        slot.text,
        text_len,
        g_text_format_mono,
        10000.0f,  // Large max width
        ContentConfig::LINE_HEIGHT,
        &slot.layout
    );

    if (SUCCEEDED(hr) && slot.layout) {
        // Get actual rendered width
        DWRITE_TEXT_METRICS metrics;
        slot.layout->GetMetrics(&metrics);
        slot.actual_width = metrics.widthIncludingTrailingWhitespace;

        // Track max width for horizontal scroll
        if (slot.actual_width > max_content_width_) {
            max_content_width_ = slot.actual_width;
        }

        slot.cache_valid = true;
    }
}

size_t ContentWidget::find_free_slot() const {
    if (!line_slots_) return ContentConfig::MAX_LINE_SLOTS;
    for (size_t i = 0; i < ContentConfig::MAX_LINE_SLOTS; i++) {
        if (line_slots_[i].line_number == 0) {
            return i;
        }
    }
    return ContentConfig::MAX_LINE_SLOTS;  // No free slot
}

size_t ContentWidget::find_slot_for_line(size_t line_number) const {
    if (!line_slots_) return ContentConfig::MAX_LINE_SLOTS;
    for (size_t i = 0; i < ContentConfig::MAX_LINE_SLOTS; i++) {
        if (line_slots_[i].line_number == line_number) {
            return i;
        }
    }
    return ContentConfig::MAX_LINE_SLOTS;  // Not found
}

// ============================================================================
// Selection Helpers
// ============================================================================

void ContentWidget::render_selection(RenderContext& ctx) {
    // Only render when editor is focused and selection exists
    if (!editor_has_focus(parent)) return;
    if (selection_start_ == selection_end_) return;  // No selection
    if (!document_) return;

    // Get selection bounds in line/column (ensure start <= end)
    size_t sel_start = (selection_start_ < selection_end_) ? selection_start_ : selection_end_;
    size_t sel_end = (selection_start_ < selection_end_) ? selection_end_ : selection_start_;

    size_t start_line, start_col, end_line, end_col;
    byte_pos_to_line_column(sel_start, start_line, start_col);
    byte_pos_to_line_column(sel_end, end_line, end_col);

    // Only render visible lines
    size_t first_visible = line_index_.first_visible_line(scroll_y_);
    size_t last_visible = line_index_.last_visible_line(scroll_y_, rect.height);

    // Clamp to visible range
    size_t render_start_line = (start_line > first_visible) ? start_line : first_visible;
    size_t render_end_line = (end_line < last_visible) ? end_line : last_visible;

    // Set selection color
    ctx.brush->SetColor(to_color_f(SelectionConfig::SELECTION_COLOR));

    for (size_t line = render_start_line; line <= render_end_line; line++) {
        float line_y = rect.y + (line - 1) * ContentConfig::LINE_HEIGHT - scroll_y_;
        float sel_left, sel_right;

        if (line == start_line && line == end_line) {
            // Single-line selection
            sel_left = rect.x + ContentConfig::PADDING_LEFT + get_cursor_x_for_column(line, start_col) - scroll_x_;
            sel_right = rect.x + ContentConfig::PADDING_LEFT + get_cursor_x_for_column(line, end_col) - scroll_x_;
        } else if (line == start_line) {
            // First line of multi-line selection
            sel_left = rect.x + ContentConfig::PADDING_LEFT + get_cursor_x_for_column(line, start_col) - scroll_x_;
            sel_right = rect.x + rect.width;  // To end of visible area
        } else if (line == end_line) {
            // Last line of multi-line selection
            sel_left = rect.x + ContentConfig::PADDING_LEFT - scroll_x_;
            sel_right = rect.x + ContentConfig::PADDING_LEFT + get_cursor_x_for_column(line, end_col) - scroll_x_;
        } else {
            // Middle line - full width
            sel_left = rect.x + ContentConfig::PADDING_LEFT - scroll_x_;
            sel_right = rect.x + rect.width;
        }

        // Clamp to visible area
        sel_left = (sel_left > rect.x) ? sel_left : rect.x;
        sel_right = (sel_right < rect.x + rect.width) ? sel_right : rect.x + rect.width;

        if (sel_right > sel_left) {
            D2D1_RECT_F sel_rect = {
                sel_left,
                line_y,
                sel_right,
                line_y + ContentConfig::LINE_HEIGHT
            };
            ctx.target->FillRectangle(sel_rect, ctx.brush);
        }
    }
}

size_t ContentWidget::get_byte_pos_at(float x, float y) {
    if (!document_ || line_index_.line_count() == 0) return 0;

    // Convert Y to line number (compute as int to handle negative y safely)
    int first_visible = static_cast<int>(line_index_.first_visible_line(scroll_y_));
    int rel_line = static_cast<int>(floorf(y / ContentConfig::LINE_HEIGHT));
    int line_int = first_visible + rel_line;

    // Clamp to valid line range [1, line_count]
    int max_line = static_cast<int>(line_index_.line_count());
    if (line_int < 1) line_int = 1;
    if (line_int > max_line) line_int = max_line;
    size_t clicked_line = static_cast<size_t>(line_int);

    // Convert X to column using DirectWrite hit-testing
    float local_x = x + scroll_x_ - ContentConfig::PADDING_LEFT;

    // Get the text layout for this line
    size_t slot_idx = find_slot_for_line(clicked_line);
    IDWriteTextLayout* layout = nullptr;

    if (slot_idx < ContentConfig::MAX_LINE_SLOTS && line_slots_[slot_idx].layout) {
        layout = line_slots_[slot_idx].layout;
    }

    size_t col = 0;
    if (layout && local_x >= 0) {
        BOOL is_trailing = FALSE;
        BOOL is_inside = FALSE;
        DWRITE_HIT_TEST_METRICS metrics;
        HRESULT hr = layout->HitTestPoint(local_x, ContentConfig::LINE_HEIGHT / 2.0f,
                                           &is_trailing, &is_inside, &metrics);
        if (SUCCEEDED(hr)) {
            col = metrics.textPosition;
            if (is_trailing) col++;
        }
    }

    return line_column_to_byte_pos(clicked_line, col);
}

bool ContentWidget::is_word_char(char c) {
    // Word characters: alphanumeric and underscore (for identifiers)
    unsigned char uc = static_cast<unsigned char>(c);
    return (uc >= 'a' && uc <= 'z') ||
           (uc >= 'A' && uc <= 'Z') ||
           (uc >= '0' && uc <= '9') ||
           (uc == '_');
}

size_t ContentWidget::get_word_boundary_left(size_t byte_pos) {
    if (!document_ || byte_pos == 0) return 0;

    // Read backwards, moving by complete UTF-8 codepoints
    size_t pos = byte_pos;
    char buf[8];

    // Helper lambda to find start of UTF-8 character containing or before pos
    auto find_char_start = [&](size_t p) -> size_t {
        if (p == 0) return 0;
        // Look back up to 4 bytes to find a valid UTF-8 leading byte
        for (size_t back = 1; back <= 4 && back <= p; back++) {
            document_->content()->get_text(p - back, buf, 1);
            unsigned char c = static_cast<unsigned char>(buf[0]);
            // Check if this is a leading byte (not a continuation byte 10xxxxxx)
            if ((c & 0xC0) != 0x80) {
                return p - back;
            }
        }
        return p > 0 ? p - 1 : 0;  // Fallback for invalid UTF-8
    };

    // Helper lambda to get UTF-8 character length from leading byte
    auto utf8_char_len = [](unsigned char c) -> size_t {
        if ((c & 0x80) == 0) return 1;       // ASCII
        if ((c & 0xE0) == 0xC0) return 2;    // 2-byte
        if ((c & 0xF0) == 0xE0) return 3;    // 3-byte
        if ((c & 0xF8) == 0xF0) return 4;    // 4-byte
        return 1;  // Invalid, treat as 1
    };

    // Find start of character before byte_pos
    size_t char_start = find_char_start(pos);
    if (char_start >= pos) return 0;  // At document start

    // Read the character to determine its type (ASCII word char, ASCII non-word, or non-ASCII)
    document_->content()->get_text(char_start, buf, 4);
    unsigned char first_byte = static_cast<unsigned char>(buf[0]);
    (void)utf8_char_len;  // Unused but kept for consistency with get_word_boundary_right

    // Determine category: word chars (ASCII alphanumeric/_), non-word ASCII, or non-ASCII
    bool is_ascii = (first_byte & 0x80) == 0;
    bool looking_for_word = is_ascii && is_word_char(buf[0]);
    bool looking_for_non_ascii = !is_ascii;

    pos = char_start;  // Move to start of this character

    // Keep going back while characters match the same category
    while (pos > 0) {
        char_start = find_char_start(pos);
        document_->content()->get_text(char_start, buf, 4);
        first_byte = static_cast<unsigned char>(buf[0]);

        // Stop at newline
        if (buf[0] == '\n') break;

        is_ascii = (first_byte & 0x80) == 0;
        bool is_word = is_ascii && is_word_char(buf[0]);
        bool is_non_ascii = !is_ascii;

        // Check if category changed
        if (looking_for_non_ascii != is_non_ascii) break;
        if (!looking_for_non_ascii && (looking_for_word != is_word)) break;

        pos = char_start;
    }

    return pos;
}

size_t ContentWidget::get_word_boundary_right(size_t byte_pos) {
    if (!document_) return byte_pos;

    size_t doc_len = document_->content()->total_length();
    if (byte_pos >= doc_len) return doc_len;

    char buf[8];
    size_t pos = byte_pos;

    // Helper lambda to get UTF-8 character length from leading byte
    auto utf8_char_len = [](unsigned char c) -> size_t {
        if ((c & 0x80) == 0) return 1;       // ASCII
        if ((c & 0xE0) == 0xC0) return 2;    // 2-byte
        if ((c & 0xF0) == 0xE0) return 3;    // 3-byte
        if ((c & 0xF8) == 0xF0) return 4;    // 4-byte
        return 1;  // Invalid, treat as 1
    };

    // Read first character to determine its category
    document_->content()->get_text(pos, buf, 4);
    unsigned char first_byte = static_cast<unsigned char>(buf[0]);
    size_t char_len = utf8_char_len(first_byte);

    // Determine category: word chars (ASCII alphanumeric/_), non-word ASCII, or non-ASCII
    bool is_ascii = (first_byte & 0x80) == 0;
    bool looking_for_word = is_ascii && is_word_char(buf[0]);
    bool looking_for_non_ascii = !is_ascii;

    // Keep going forward while characters match the same category
    while (pos < doc_len) {
        document_->content()->get_text(pos, buf, 4);
        first_byte = static_cast<unsigned char>(buf[0]);
        char_len = utf8_char_len(first_byte);

        // Stop at newline
        if (buf[0] == '\n') break;

        is_ascii = (first_byte & 0x80) == 0;
        bool is_word = is_ascii && is_word_char(buf[0]);
        bool is_non_ascii = !is_ascii;

        // Check if category changed
        if (looking_for_non_ascii != is_non_ascii) break;
        if (!looking_for_non_ascii && (looking_for_word != is_word)) break;

        // Move to next UTF-8 codepoint
        pos += char_len;
    }

    return pos;
}

void ContentWidget::clear_selection() {
    selection_start_ = cursor_byte_pos_;
    selection_end_ = cursor_byte_pos_;
    set_dirty();
}

void ContentWidget::get_selection(size_t* start_byte, size_t* end_byte) const {
    // Return ordered selection (start <= end)
    if (selection_start_ <= selection_end_) {
        if (start_byte) *start_byte = selection_start_;
        if (end_byte) *end_byte = selection_end_;
    } else {
        if (start_byte) *start_byte = selection_end_;
        if (end_byte) *end_byte = selection_start_;
    }
}

void ContentWidget::set_selection(size_t start_byte, size_t end_byte) {
    selection_start_ = start_byte;
    selection_end_ = end_byte;

    // Move cursor to selection end (as documented in header comment)
    cursor_byte_pos_ = end_byte;
    byte_pos_to_line_column(cursor_byte_pos_, cursor_line_, cursor_column_);
    cursor_preferred_column_ = cursor_column_;
    cursor_target_x_ = get_cursor_x_for_column(cursor_line_, cursor_column_);
    cursor_current_x_ = cursor_target_x_;  // Snap immediately
    reset_cursor_blink();
    ensure_cursor_visible();
    set_dirty();
}

void ContentWidget::begin_selection_at_cursor() {
    selection_start_ = cursor_byte_pos_;
    // selection_end_ stays where it is until extend_selection_to is called
}

void ContentWidget::extend_selection_to(size_t byte_pos) {
    selection_end_ = byte_pos;
    set_dirty();
}

void ContentWidget::select_line(size_t line_num) {
    if (!document_ || line_num == 0 || line_num > line_index_.line_count()) return;

    size_t line_start = get_line_start_byte(line_num);
    size_t line_end = get_line_end_byte(line_num);

    // Include the newline if it exists (selecting whole line)
    if (line_num < line_index_.line_count()) {
        line_end = get_line_start_byte(line_num + 1);
    }

    selection_start_ = line_start;
    selection_end_ = line_end;
    cursor_byte_pos_ = line_end;

    // Update cursor position state
    byte_pos_to_line_column(cursor_byte_pos_, cursor_line_, cursor_column_);
    cursor_preferred_column_ = cursor_column_;
    cursor_target_x_ = get_cursor_x_for_column(cursor_line_, cursor_column_);
    reset_cursor_blink();
    set_dirty();
}

void ContentWidget::select_word_at(size_t byte_pos) {
    if (!document_) return;

    size_t doc_len = document_->content()->total_length();
    if (doc_len == 0) return;

    // Clamp position
    if (byte_pos >= doc_len) byte_pos = doc_len > 0 ? doc_len - 1 : 0;

    // Find word boundaries
    selection_start_ = get_word_boundary_left(byte_pos);
    selection_end_ = get_word_boundary_right(byte_pos);
    cursor_byte_pos_ = selection_end_;

    // Update cursor position state
    byte_pos_to_line_column(cursor_byte_pos_, cursor_line_, cursor_column_);
    cursor_preferred_column_ = cursor_column_;
    cursor_target_x_ = get_cursor_x_for_column(cursor_line_, cursor_column_);
    reset_cursor_blink();
    set_dirty();
}

void ContentWidget::select_all() {
    if (!document_) return;

    selection_start_ = 0;
    selection_end_ = document_->content()->total_length();
    cursor_byte_pos_ = selection_end_;

    // Update cursor position state
    byte_pos_to_line_column(cursor_byte_pos_, cursor_line_, cursor_column_);
    cursor_preferred_column_ = cursor_column_;
    cursor_target_x_ = get_cursor_x_for_column(cursor_line_, cursor_column_);
    reset_cursor_blink();
    set_dirty();
}

char* ContentWidget::get_selected_text(size_t* out_len) const {
    if (!document_ || !has_selection()) {
        if (out_len) *out_len = 0;
        return nullptr;
    }

    size_t start_byte, end_byte;
    get_selection(&start_byte, &end_byte);
    size_t len = end_byte - start_byte;

    if (len == 0) {
        if (out_len) *out_len = 0;
        return nullptr;
    }

    // Allocate buffer with null terminator
    char* buf = new (std::nothrow) char[len + 1];
    if (!buf) {
        if (out_len) *out_len = 0;
        return nullptr;
    }

    // Extract text from piece table
    size_t got = document_->content()->get_text(start_byte, buf, len);
    buf[got] = '\0';

    if (out_len) *out_len = got;
    return buf;
}

size_t ContentWidget::delete_selection() {
    if (!document_ || !has_selection()) {
        return cursor_byte_pos_;
    }

    size_t start_byte, end_byte;
    get_selection(&start_byte, &end_byte);
    size_t delete_len = end_byte - start_byte;

    // Capture the line containing start_byte BEFORE deletion for correct invalidation
    size_t start_line = line_index_.byte_to_line(start_byte);
    if (start_line == 0) start_line = 1;

    // Count newlines in deleted range (needed for LineIndex update)
    int newlines_removed = 0;
    constexpr size_t CHUNK_SIZE = 4096;
    char chunk[CHUNK_SIZE];
    size_t remaining = delete_len;
    size_t pos = start_byte;
    while (remaining > 0) {
        size_t to_read = (remaining < CHUNK_SIZE) ? remaining : CHUNK_SIZE;
        size_t got = document_->content()->get_text(pos, chunk, to_read);
        for (size_t i = 0; i < got; i++) {
            if (chunk[i] == '\n') newlines_removed++;
        }
        pos += got;
        remaining -= got;
        if (got == 0) break;  // Safety: avoid infinite loop
    }

    // Delete the range
    document_->content()->delete_range(start_byte, delete_len);
    document_->mark_dirty();

    // Update line index
    line_index_.update_after_delete(start_byte, delete_len, newlines_removed);

    // Clear selection and move cursor to deletion point
    selection_start_ = start_byte;
    selection_end_ = start_byte;
    move_cursor_to(start_byte);

    // Invalidate affected lines (use pre-delete start_line for correct range)
    if (newlines_removed > 0) {
        size_t last_visible = line_index_.last_visible_line(scroll_y_, rect.height);
        invalidate_lines(start_line, last_visible);
        update_visible_lines();
    } else {
        invalidate_line(start_line);
    }

    return start_byte;
}

} // namespace CodeEditor
