// <AUTO-GENERATED TOC> DO NOT EDIT MANUALLY
// Table of Contents
//
// 1. Construction / Destruction (line 20)
// 2. Build & Update Operations (line 34)
// 3. Line Lookups (line 192)
// 4. Viewport Calculations (line 204)
// 5. Reverse Lookup (line 280)
// 6. Content Height (line 312)
//
// </AUTO-GENERATED TOC>
// line_index.cpp - Line index implementation

#include "line_index.h"
#include "piece_table.h"
#include <algorithm>

namespace CodeEditor {

// ============================================================================
// Construction / Destruction
// ============================================================================

LineIndex::LineIndex()
    : total_lines_(0)
    , line_height_(20.0f)  // Default line height
{
}

LineIndex::~LineIndex() {
    // Nothing to clean up - vector handles itself
}

// ============================================================================
// Build & Update Operations
// ============================================================================

void LineIndex::build(const PieceTable* pt) {
    lines_.clear();

    if (!pt) {
        // Empty index for null document
        total_lines_ = 0;
        return;
    }

    // Line 1 always starts at offset 0
    LineEntry first_line = { 0, 1, 0, 0 };
    lines_.push_back(first_line);

    // Scan for newlines
    size_t total = pt->total_length();
    if (total == 0) {
        total_lines_ = 1;
        return;
    }

    // Read in chunks to find newlines
    static constexpr size_t CHUNK_SIZE = 4096;
    char buf[CHUNK_SIZE];
    size_t offset = 0;

    while (offset < total) {
        size_t to_read = total - offset;
        if (to_read > CHUNK_SIZE) {
            to_read = CHUNK_SIZE;
        }

        pt->get_text(offset, buf, to_read);

        for (size_t i = 0; i < to_read; i++) {
            if (buf[i] == '\n') {
                // New line starts after the newline character
                LineEntry entry = {
                    offset + i + 1,
                    static_cast<uint32_t>(lines_.size() + 1),
                    0,
                    0
                };
                lines_.push_back(entry);
            }
        }
        offset += to_read;
    }

    total_lines_ = lines_.size();
}

void LineIndex::clear() {
    lines_.clear();
    total_lines_ = 0;
}

void LineIndex::update_after_insert(size_t byte_pos, size_t bytes_inserted,
                                     const size_t* newline_offsets, int newlines_added) {
    if (lines_.empty()) {
        return;
    }

    // Find the line containing the insertion point
    size_t affected_line_idx = 0;
    for (size_t i = 1; i < lines_.size(); i++) {
        if (lines_[i].byte_offset > byte_pos) {
            break;
        }
        affected_line_idx = i;
    }

    // Update byte offsets for all lines after the insertion point
    for (size_t i = affected_line_idx + 1; i < lines_.size(); i++) {
        lines_[i].byte_offset += bytes_inserted;
    }

    // If newlines were added, insert new line entries
    if (newlines_added > 0 && newline_offsets != nullptr) {
        for (int n = 0; n < newlines_added; n++) {
            // Line starts AFTER the newline character
            // newline_offsets[n] is relative to byte_pos
            size_t new_line_offset = byte_pos + newline_offsets[n] + 1;
            LineEntry new_entry = {
                new_line_offset,
                static_cast<uint32_t>(affected_line_idx + 2 + n),
                0,
                0
            };
            lines_.insert(lines_.begin() + affected_line_idx + 1 + n, new_entry);
        }

        // Renumber all lines after insertion
        for (size_t i = 0; i < lines_.size(); i++) {
            lines_[i].line_number = static_cast<uint32_t>(i + 1);
        }

        total_lines_ = lines_.size();
    }
}

void LineIndex::update_after_delete(size_t byte_pos, size_t bytes_deleted, int newlines_removed) {
    if (lines_.empty()) {
        return;
    }

    size_t delete_end = byte_pos + bytes_deleted;

    if (newlines_removed > 0) {
        // Remove lines whose start falls within the deleted range
        // A line is removed if its byte_offset is in [byte_pos, delete_end)
        // and there's a newline being deleted

        auto it = lines_.begin();
        while (it != lines_.end()) {
            // Don't remove line 1 (it always starts at 0)
            if (it->line_number > 1 && it->byte_offset > byte_pos && it->byte_offset <= delete_end) {
                it = lines_.erase(it);
            } else {
                ++it;
            }
        }

        // Renumber lines
        for (size_t i = 0; i < lines_.size(); i++) {
            lines_[i].line_number = static_cast<uint32_t>(i + 1);
        }
    }

    // Update byte offsets for lines after the deletion
    for (auto& entry : lines_) {
        if (entry.byte_offset > byte_pos) {
            if (entry.byte_offset >= delete_end) {
                entry.byte_offset -= bytes_deleted;
            } else {
                // Line starts within deleted range - move to deletion start
                entry.byte_offset = byte_pos;
            }
        }
    }

    total_lines_ = lines_.size();
}

// ============================================================================
// Line Lookups
// ============================================================================

const LineEntry* LineIndex::get_line(size_t line_num) const {
    if (line_num == 0 || line_num > total_lines_) {
        return nullptr;
    }
    // line_num is 1-indexed, vector is 0-indexed
    return &lines_[line_num - 1];
}

// ============================================================================
// Viewport Calculations
// ============================================================================

size_t LineIndex::first_visible_line(float scroll_y) const {
    if (total_lines_ == 0 || line_height_ <= 0.0f) {
        return 1;
    }

    if (scroll_y <= 0.0f) {
        return 1;
    }

    // O(1) calculation: which line's top edge is at scroll_y?
    size_t line_index = static_cast<size_t>(scroll_y / line_height_);

    // Convert to 1-indexed, clamp to valid range
    size_t line_num = line_index + 1;
    if (line_num > total_lines_) {
        line_num = total_lines_;
    }

    return line_num;
}

size_t LineIndex::last_visible_line(float scroll_y, float viewport_height) const {
    if (total_lines_ == 0 || line_height_ <= 0.0f) {
        return 1;
    }

    // Bottom edge of viewport
    float bottom_edge = scroll_y + viewport_height;

    // Line n (1-indexed) has its top at (n-1) * line_height
    // A line is visible if its top is < bottom_edge
    // So: (n-1) * line_height < bottom_edge
    //     n < bottom_edge / line_height + 1
    // Max visible line = floor(bottom_edge / line_height)
    // (unless exactly on boundary, then that line's top IS at the edge)

    size_t line_num = static_cast<size_t>(bottom_edge / line_height_);

    // If exactly on boundary (no fractional part), include that line anyway
    // since in practice we want to show partially visible lines
    float remainder = bottom_edge - (line_num * line_height_);
    if (remainder > 0.001f && line_num < total_lines_) {
        line_num++;  // Include the partially visible line
    }

    // Clamp to valid range
    if (line_num > total_lines_) {
        line_num = total_lines_;
    }
    if (line_num < 1) {
        line_num = 1;
    }

    return line_num;
}

size_t LineIndex::visible_line_count(float viewport_height) const {
    if (line_height_ <= 0.0f) {
        return 0;
    }

    // Add 2 for partial lines at top and bottom
    size_t count = static_cast<size_t>(viewport_height / line_height_) + 2;

    // Don't exceed total lines
    if (count > total_lines_) {
        count = total_lines_;
    }

    return count;
}

// ============================================================================
// Reverse Lookup
// ============================================================================

size_t LineIndex::byte_to_line(size_t byte_offset) const {
    if (total_lines_ == 0) {
        return 1;
    }

    // Binary search for the line containing byte_offset
    // We're looking for the last line whose byte_offset <= byte_offset
    size_t left = 0;
    size_t right = lines_.size();

    while (left < right) {
        size_t mid = left + (right - left) / 2;
        if (lines_[mid].byte_offset <= byte_offset) {
            left = mid + 1;
        } else {
            right = mid;
        }
    }

    // left is now the first line with offset > byte_offset
    // So the line containing byte_offset is at left - 1
    if (left > 0) {
        return lines_[left - 1].line_number;
    }

    return 1;
}

// ============================================================================
// Content Height
// ============================================================================

float LineIndex::total_content_height() const {
    return static_cast<float>(total_lines_) * line_height_;
}

} // namespace CodeEditor
