// <AUTO-GENERATED TOC> DO NOT EDIT MANUALLY
// Table of Contents
//
// 1. Construction / Destruction (line 18)
// 2. Core Operations (line 82)
// 3. Line Operations (line 263)
// 4. Undo/Redo (line 363)
//
// </AUTO-GENERATED TOC>
// piece_table.cpp - Piece table implementation

#include "piece_table.h"
#include <cstring>
#include <algorithm>

namespace CodeEditor {

// ============================================================================
// Construction / Destruction
// ============================================================================

PieceTable::PieceTable()
    : original(nullptr)
    , original_len(0)
    , owns_original(false)
    , total_len(0)
    , undo_pos(0)
{
}

PieceTable::~PieceTable() {
    if (owns_original && original) {
        delete[] original;
    }
}

void PieceTable::init_from_string(const char* utf8_text, size_t len) {
    clear();

    if (len > 0 && utf8_text) {
        // Copy into owned buffer
        original = new char[len];
        memcpy(original, utf8_text, len);
        original_len = len;
        owns_original = true;

        // Create single piece spanning entire original
        pieces.push_back({ PieceSource::Original, 0, len });
        total_len = len;
    }
}

void PieceTable::init_from_buffer(const char* buffer, size_t len, bool take_ownership) {
    clear();

    if (len > 0 && buffer) {
        original = const_cast<char*>(buffer);
        original_len = len;
        owns_original = take_ownership;

        pieces.push_back({ PieceSource::Original, 0, len });
        total_len = len;
    }
}

void PieceTable::clear() {
    if (owns_original && original) {
        delete[] original;
    }
    original = nullptr;
    original_len = 0;
    owns_original = false;

    append_buf.clear();
    pieces.clear();
    total_len = 0;

    undo_stack.clear();
    undo_pos = 0;
}

// ============================================================================
// Core Operations
// ============================================================================

PieceTable::PieceLocation PieceTable::find_piece(size_t pos) const {
    size_t offset = 0;
    for (size_t i = 0; i < pieces.size(); i++) {
        if (pos < offset + pieces[i].length) {
            return { i, pos - offset };
        }
        offset += pieces[i].length;
    }
    // Position is at end of document
    return { pieces.size(), 0 };
}

const char* PieceTable::piece_data(const Piece& p) const {
    if (p.source == PieceSource::Original) {
        return original + p.offset;
    } else {
        return append_buf.data() + p.offset;
    }
}

void PieceTable::recalc_total_length() {
    total_len = 0;
    for (const auto& p : pieces) {
        total_len += p.length;
    }
}

bool PieceTable::insert(size_t pos, const char* text, size_t len) {
    if (pos > total_len || len == 0 || !text) {
        return pos <= total_len; // Allow insert at end, reject only if truly out of bounds
    }

    // Record position in append buffer where new text will go
    size_t append_offset = append_buf.size();

    // Append new text to append buffer
    append_buf.insert(append_buf.end(), text, text + len);

    // Create new piece for inserted text
    Piece new_piece = { PieceSource::Append, append_offset, len };

    if (pieces.empty()) {
        // Empty document, just add the piece
        pieces.push_back(new_piece);
    } else {
        // Find piece containing insertion point
        PieceLocation loc = find_piece(pos);

        if (loc.piece_index >= pieces.size()) {
            // Insert at end
            pieces.push_back(new_piece);
        } else if (loc.offset_in_piece == 0) {
            // Insert at start of piece
            pieces.insert(pieces.begin() + loc.piece_index, new_piece);
        } else {
            // Split piece and insert in middle
            Piece& p = pieces[loc.piece_index];
            Piece before = { p.source, p.offset, loc.offset_in_piece };
            Piece after = { p.source, p.offset + loc.offset_in_piece, p.length - loc.offset_in_piece };

            // Replace current piece with: before, new_piece, after
            pieces[loc.piece_index] = before;
            pieces.insert(pieces.begin() + loc.piece_index + 1, new_piece);
            if (after.length > 0) {
                pieces.insert(pieces.begin() + loc.piece_index + 2, after);
            }
        }
    }

    total_len += len;
    return true;
}

bool PieceTable::delete_range(size_t pos, size_t len) {
    if (pos > total_len || len == 0) {
        return pos <= total_len;
    }

    // Clamp length to available content
    if (pos + len > total_len) {
        len = total_len - pos;
    }

    size_t end_pos = pos + len;

    // Find pieces at start and end of deletion range
    PieceLocation start_loc = find_piece(pos);
    PieceLocation end_loc = find_piece(end_pos);

    if (start_loc.piece_index >= pieces.size()) {
        // Nothing to delete
        return true;
    }

    // Calculate new pieces array
    std::vector<Piece> new_pieces;

    // Copy pieces before deletion range
    for (size_t i = 0; i < start_loc.piece_index; i++) {
        new_pieces.push_back(pieces[i]);
    }

    // Handle partial piece at start of deletion
    if (start_loc.offset_in_piece > 0) {
        Piece& p = pieces[start_loc.piece_index];
        new_pieces.push_back({ p.source, p.offset, start_loc.offset_in_piece });
    }

    // Handle partial piece at end of deletion
    if (end_loc.piece_index < pieces.size() && end_loc.offset_in_piece > 0) {
        Piece& p = pieces[end_loc.piece_index];
        size_t remaining = p.length - end_loc.offset_in_piece;
        if (remaining > 0) {
            new_pieces.push_back({ p.source, p.offset + end_loc.offset_in_piece, remaining });
        }
        // Skip the partially consumed piece
        end_loc.piece_index++;
    }

    // Copy pieces after deletion range
    for (size_t i = end_loc.piece_index; i < pieces.size(); i++) {
        new_pieces.push_back(pieces[i]);
    }

    pieces = std::move(new_pieces);
    total_len -= len;
    return true;
}

size_t PieceTable::get_text(size_t pos, char* buf, size_t buf_len) const {
    if (pos >= total_len || buf_len == 0 || !buf) {
        return 0;
    }

    // Calculate how much we can actually read
    size_t max_to_read = total_len - pos;
    if (buf_len < max_to_read) {
        max_to_read = buf_len;
    }

    size_t bytes_written = 0;
    size_t doc_offset = 0;  // Current position in document

    for (const auto& p : pieces) {
        size_t piece_start = doc_offset;
        size_t piece_end = doc_offset + p.length;

        // Skip pieces entirely before our starting position
        if (piece_end <= pos) {
            doc_offset = piece_end;
            continue;
        }

        // Stop if we've read everything we need
        if (bytes_written >= max_to_read) {
            break;
        }

        // Calculate what part of this piece to copy
        size_t start_in_piece = (pos > piece_start) ? pos - piece_start : 0;
        size_t available_in_piece = p.length - start_in_piece;
        size_t remaining_to_read = max_to_read - bytes_written;
        size_t bytes_to_copy = (available_in_piece < remaining_to_read)
                               ? available_in_piece : remaining_to_read;

        const char* src = piece_data(p) + start_in_piece;
        memcpy(buf + bytes_written, src, bytes_to_copy);
        bytes_written += bytes_to_copy;

        // Move past position we've already copied
        pos = piece_start + start_in_piece + bytes_to_copy;
        doc_offset = piece_end;
    }

    return bytes_written;
}

// ============================================================================
// Line Operations
// ============================================================================

size_t PieceTable::count_lines() const {
    if (total_len == 0) {
        return 1; // Empty document has 1 line
    }

    size_t lines = 1;
    for (const auto& p : pieces) {
        const char* data = piece_data(p);
        for (size_t i = 0; i < p.length; i++) {
            if (data[i] == '\n') {
                lines++;
            }
        }
    }
    return lines;
}

size_t PieceTable::get_line_start(size_t line_num) const {
    if (line_num == 0) {
        return 0;
    }

    size_t current_line = 0;
    size_t byte_offset = 0;

    for (const auto& p : pieces) {
        const char* data = piece_data(p);
        for (size_t i = 0; i < p.length; i++) {
            if (data[i] == '\n') {
                current_line++;
                if (current_line == line_num) {
                    return byte_offset + i + 1;
                }
            }
        }
        byte_offset += p.length;
    }

    return total_len; // Line doesn't exist
}

size_t PieceTable::get_line_length(size_t line_num) const {
    size_t start = get_line_start(line_num);
    if (start >= total_len) {
        return 0;
    }

    // Find next newline or end of document
    size_t current_line = 0;
    size_t byte_offset = 0;
    bool found_line_start = (line_num == 0);

    for (const auto& p : pieces) {
        const char* data = piece_data(p);
        for (size_t i = 0; i < p.length; i++) {
            if (found_line_start) {
                if (data[i] == '\n') {
                    return (byte_offset + i + 1) - start;
                }
            } else if (data[i] == '\n') {
                current_line++;
                if (current_line == line_num) {
                    found_line_start = true;
                }
            }
        }
        byte_offset += p.length;
    }

    return total_len - start;
}

size_t PieceTable::byte_to_line(size_t byte_offset) const {
    if (byte_offset >= total_len) {
        return count_lines() - 1;
    }

    size_t line = 0;
    size_t current_offset = 0;

    for (const auto& p : pieces) {
        const char* data = piece_data(p);
        for (size_t i = 0; i < p.length; i++) {
            if (current_offset >= byte_offset) {
                return line;
            }
            if (data[i] == '\n') {
                line++;
            }
            current_offset++;
        }
    }

    return line;
}

// ============================================================================
// Undo/Redo
// ============================================================================

void PieceTable::push_undo(size_t cursor_pos, size_t selection_start, size_t selection_end) {
    // Truncate any redo history
    if (undo_pos < undo_stack.size()) {
        undo_stack.resize(undo_pos);
    }

    // Enforce max undo levels
    if (undo_stack.size() >= MAX_UNDO_LEVELS) {
        undo_stack.erase(undo_stack.begin());
    }

    // Create snapshot with cursor position and selection
    Snapshot snap;
    snap.pieces = pieces;
    snap.append_buf_size = append_buf.size();
    snap.total_len = total_len;
    snap.cursor_pos = cursor_pos;
    snap.selection_start = selection_start;
    snap.selection_end = selection_end;

    undo_stack.push_back(std::move(snap));
    undo_pos = undo_stack.size();
}

size_t PieceTable::undo(size_t current_cursor_pos, size_t current_sel_start, size_t current_sel_end,
                        size_t* out_selection_start, size_t* out_selection_end) {
    if (undo_pos == 0) {
        return 0;  // Nothing to undo
    }

    // Save current state for redo (if not already saved)
    if (undo_pos == undo_stack.size()) {
        Snapshot current;
        current.pieces = pieces;
        current.append_buf_size = append_buf.size();
        current.total_len = total_len;
        current.cursor_pos = current_cursor_pos;  // Store current cursor for redo
        current.selection_start = current_sel_start;
        current.selection_end = current_sel_end;
        undo_stack.push_back(std::move(current));
    }

    undo_pos--;
    const Snapshot& snap = undo_stack[undo_pos];
    pieces = snap.pieces;
    total_len = snap.total_len;
    // Note: append_buf is not truncated - old data is preserved for redo

    // Return selection state if requested
    if (out_selection_start) *out_selection_start = snap.selection_start;
    if (out_selection_end) *out_selection_end = snap.selection_end;

    return snap.cursor_pos;  // Return stored cursor position
}

size_t PieceTable::redo(size_t* out_selection_start, size_t* out_selection_end) {
    if (undo_pos >= undo_stack.size() - 1) {
        return 0;  // Nothing to redo
    }

    undo_pos++;
    const Snapshot& snap = undo_stack[undo_pos];
    pieces = snap.pieces;
    total_len = snap.total_len;

    // Return selection state if requested
    if (out_selection_start) *out_selection_start = snap.selection_start;
    if (out_selection_end) *out_selection_end = snap.selection_end;

    return snap.cursor_pos;  // Return stored cursor position
}

void PieceTable::clear_undo_history() {
    undo_stack.clear();
    undo_pos = 0;
}

} // namespace CodeEditor
