// <AUTO-GENERATED TOC> DO NOT EDIT MANUALLY
// Table of Contents
//
// 1. dialog_widgets.h - Dialog Widget Type Declarations (line 9)
// 2. Accessor functions for dialog widget instances (line 31)
// 3. Wrapper functions for platform.cpp operations (line 54)
//
// </AUTO-GENERATED TOC>
// ============================================================================
// dialog_widgets.h - Dialog Widget Type Declarations
// ============================================================================
//
// Minimal declarations for dialog widget types. Full struct definitions and
// method implementations are in platform_dialogs.cpp.
// ============================================================================

#ifndef DIALOG_WIDGETS_H
#define DIALOG_WIDGETS_H

// Forward declarations for dialog widget base class
struct DialogWidget;

// Forward declarations for concrete dialog widgets
struct BranchDialogWidget;
struct BranchRenameDialogWidget;
struct AuthDialogWidget;
struct OAuthDialogWidget;
struct StashDialogWidget;
struct CloneDialogWidget;

// ============================================================================
// Accessor functions for dialog widget instances
// ============================================================================
//
// These functions provide access to dialog widget instances from platform.cpp.
// They are defined in platform_dialogs.cpp where the complete type definitions
// and method implementations are available.
// ============================================================================

// Get the active dialog widget instance (returns nullptr if none)
DialogWidget* get_active_dialog_widget();

// Check if any dialog widget is currently active
bool any_dialog_widget_is_active();

// Get specific dialog widget instances (returns nullptr if not created)
BranchDialogWidget* get_branch_dialog_widget();
BranchRenameDialogWidget* get_branch_rename_dialog_widget();
AuthDialogWidget* get_auth_dialog_widget();
OAuthDialogWidget* get_oauth_dialog_widget();
StashDialogWidget* get_stash_dialog_widget();
CloneDialogWidget* get_clone_dialog_widget();

// ============================================================================
// Wrapper functions for platform.cpp operations
// ============================================================================
//
// These functions encapsulate operations that platform.cpp needs to perform
// on dialog widgets, avoiding the need for platform.cpp to directly access
// dialog widget members.
// ============================================================================

// Tick the widget tree for a specific dialog widget type
void tick_branch_dialog_tree(float dt);
void tick_branch_rename_dialog_tree(float dt);
void tick_tag_dialog_tree(float dt);
void tick_auth_dialog_tree(float dt);
void tick_oauth_dialog_tree(float dt);
void tick_stash_dialog_tree(float dt);
void tick_clone_dialog_tree(float dt);
#ifdef GITSMARTER_DEBUG
void tick_debug_test_dialog_tree(float dt);
void tick_code_editor_test_dialog_tree(float dt);
#endif

// Check if a specific dialog widget is active
bool branch_dialog_is_active();
bool branch_rename_dialog_is_active();
bool tag_dialog_is_active();
bool auth_dialog_is_active();
bool oauth_dialog_is_active();
bool stash_dialog_is_active();
bool clone_dialog_is_active();
#ifdef GITSMARTER_DEBUG
bool debug_test_dialog_is_active();
#endif

// Update clone dialog progress (called from timer handler)
void clone_dialog_update_progress();

// Close clone dialog (called from completion handler)
void clone_dialog_close();

#endif // DIALOG_WIDGETS_H
