// <AUTO-GENERATED TOC> DO NOT EDIT MANUALLY
// Table of Contents
//
// 1. External State References (defined in platform.cpp) (line 23)
// 2. Availability Check Functions (line 37)
// 3. Command Execute Functions (Forward Declarations) (line 98)
// 4. Command Registry Definition (line 121)
// 5. Built-in Aliases (line 286)
// 6. Registry API Implementation (line 308)
//
// </AUTO-GENERATED TOC>
// Command Registry - Centralized command registration for the command palette
//
// This module provides a registry of all commands that can be executed via
// the command palette. Commands are defined statically for performance and
// simplicity, with context-aware availability checks.

#include "../include/app.h"
#include "../include/ui_theme.h"
#include <cwchar>
#include <cstring>

// ============================================================================
// External State References (defined in platform.cpp)
// ============================================================================

// Note: We access g_sidebar through accessor functions to avoid structure coupling
// These functions are defined in platform.cpp
extern size_t palette_get_staged_count();
extern size_t palette_get_unstaged_count();
extern size_t palette_get_changed_count();
extern GitRepository g_repo;

// Forward declarations for worker API
extern bool worker_is_busy();

// ============================================================================
// Availability Check Functions
// ============================================================================

// Git operations availability
static bool is_repo_open() {
    return g_repo.is_valid;
}

static bool has_staged_files() {
    return is_repo_open() && palette_get_staged_count() > 0;
}

static bool has_unstaged_files() {
    return is_repo_open() && palette_get_unstaged_count() > 0;
}

static bool has_any_changes() {
    return is_repo_open() && palette_get_changed_count() > 0;
}

static bool is_not_busy() {
    return !worker_is_busy();
}

static bool can_stage_all() {
    return has_unstaged_files() && is_not_busy();
}

static bool can_unstage_all() {
    return has_staged_files() && is_not_busy();
}

static bool can_commit() {
    return has_staged_files() && is_not_busy();
}

static bool can_fetch() {
    return is_repo_open() && is_not_busy();
}

static bool can_push() {
    return is_repo_open() && is_not_busy();
}

static bool can_pull() {
    return is_repo_open() && is_not_busy();
}

static bool can_discard_all() {
    return has_unstaged_files() && is_not_busy();
}

static bool is_head_detached() {
    return is_repo_open() && g_repo.head_detached;
}

static bool can_create_branch_from_head() {
    return is_head_detached() && is_not_busy();
}

// ============================================================================
// Command Execute Functions (Forward Declarations)
// ============================================================================

// These are implemented in platform.cpp or will call existing functions
extern void cmd_stage_all();
extern void cmd_unstage_all();
extern void cmd_fetch();
extern void cmd_push();
extern void cmd_pull();
extern void cmd_commit();
extern void cmd_stash();
extern void cmd_stash_pop();
extern void cmd_create_branch();
extern void cmd_switch_branch();
extern void cmd_discard_all();
extern void cmd_focus_sidebar();
extern void cmd_focus_diff();
extern void cmd_search_commits();

// Create branch from HEAD (delegates to branch dialog)
static void cmd_create_branch_from_head() { cmd_create_branch(); }

// ============================================================================
// Command Registry Definition
// ============================================================================

// All registered commands (static array for performance)
static const PaletteCommand g_commands[] = {
    // Git Operations
    {
        "git.stageAll",
        L"Stage All",
        PaletteCategory::Git,
        "Ctrl+A",
        can_stage_all,
        cmd_stage_all,
        false,
        nullptr
    },
    {
        "git.unstageAll",
        L"Unstage All",
        PaletteCategory::Git,
        "Ctrl+Shift+A",
        can_unstage_all,
        cmd_unstage_all,
        false,
        nullptr
    },
    {
        "git.fetch",
        L"Fetch from Origin",
        PaletteCategory::Git,
        "Ctrl+Shift+F",
        can_fetch,
        cmd_fetch,
        false,
        nullptr
    },
    {
        "git.push",
        L"Push to Origin",
        PaletteCategory::Git,
        "Ctrl+Shift+U",
        can_push,
        cmd_push,
        false,
        nullptr
    },
    {
        "git.pull",
        L"Pull from Origin",
        PaletteCategory::Git,
        "Ctrl+Shift+P",
        can_pull,
        cmd_pull,
        false,
        nullptr
    },
    {
        "git.commit",
        L"Create Commit",
        PaletteCategory::Git,
        "Ctrl+Enter",
        can_commit,
        cmd_commit,
        false,
        nullptr
    },
    {
        "git.stash",
        L"Stash Changes",
        PaletteCategory::Git,
        "Ctrl+Shift+S",
        has_any_changes,
        cmd_stash,
        false,
        nullptr
    },
    {
        "git.stashPop",
        L"Pop Stash",
        PaletteCategory::Git,
        nullptr,
        is_repo_open,  // TODO: check if stashes exist
        cmd_stash_pop,
        false,
        nullptr
    },
    {
        "git.createBranch",
        L"Create Branch",
        PaletteCategory::Git,
        nullptr,
        is_repo_open,
        cmd_create_branch,
        true,
        L"Enter branch name..."
    },
    {
        "git.switchBranch",
        L"Switch Branch",
        PaletteCategory::Git,
        nullptr,
        is_repo_open,
        cmd_switch_branch,
        true,
        L"Search branches..."
    },
    {
        "git.discardAll",
        L"Discard All Changes",
        PaletteCategory::Git,
        nullptr,
        can_discard_all,
        cmd_discard_all,
        false,
        nullptr
    },

    // Git State Commands (context-dependent visibility)
    {
        "git.createBranchFromHead",
        L"Create Branch from HEAD",
        PaletteCategory::Git,
        nullptr,
        can_create_branch_from_head,
        cmd_create_branch_from_head,
        true,
        L"Enter branch name..."
    },

    // Navigation
    {
        "nav.focusSidebar",
        L"Focus Sidebar",
        PaletteCategory::Navigation,
        "F6",
        nullptr,  // Always available
        cmd_focus_sidebar,
        false,
        nullptr
    },
    {
        "nav.focusDiff",
        L"Focus Diff Viewer",
        PaletteCategory::Navigation,
        "Shift+F6",
        nullptr,
        cmd_focus_diff,
        false,
        nullptr
    },
    {
        "nav.searchCommits",
        L"Search Commits",
        PaletteCategory::Navigation,
        "Ctrl+F",
        is_repo_open,
        cmd_search_commits,
        false,
        nullptr
    },
};

static constexpr size_t g_command_count = sizeof(g_commands) / sizeof(g_commands[0]);

// ============================================================================
// Built-in Aliases
// ============================================================================

static const CommandAlias g_aliases[] = {
    { "checkout", "git.switchBranch" },
    { "co", "git.switchBranch" },
    { "add", "git.stageAll" },
    { "reset", "git.unstageAll" },
    { "ci", "git.commit" },
    { "commit", "git.commit" },
    { "pull", "git.pull" },
    { "push", "git.push" },
    { "fetch", "git.fetch" },
    { "branch", "git.createBranch" },
    { "br", "git.createBranch" },
    { "stash", "git.stash" },
    { "pop", "git.stashPop" },
};

static constexpr size_t g_alias_count = sizeof(g_aliases) / sizeof(g_aliases[0]);

// ============================================================================
// Registry API Implementation
// ============================================================================

void command_registry_init() {
    // Static initialization - nothing to do
    LOG("Command registry initialized with %zu commands and %zu aliases",
        g_command_count, g_alias_count);
}

size_t command_registry_count() {
    return g_command_count;
}

const PaletteCommand* command_registry_get(size_t index) {
    if (index >= g_command_count) return nullptr;
    return &g_commands[index];
}

const PaletteCommand* command_registry_find_by_id(const char* id) {
    if (!id) return nullptr;

    for (size_t i = 0; i < g_command_count; i++) {
        if (strcmp(g_commands[i].id, id) == 0) {
            return &g_commands[i];
        }
    }
    return nullptr;
}

const PaletteCommand* command_registry_find_by_alias(const char* alias) {
    if (!alias) return nullptr;

    // First check if it matches a command ID directly
    const PaletteCommand* direct = command_registry_find_by_id(alias);
    if (direct) return direct;

    // Check aliases
    for (size_t i = 0; i < g_alias_count; i++) {
        if (strcmp(g_aliases[i].alias, alias) == 0) {
            return command_registry_find_by_id(g_aliases[i].command_id);
        }
    }

    return nullptr;
}
