// <AUTO-GENERATED TOC> DO NOT EDIT MANUALLY
// Table of Contents
//
// 1. PNG Encoding via WIC (line 21)
// 2. Screenshot Capture Implementation (line 116)
//
// </AUTO-GENERATED TOC>
// IPC Screenshot Capture
// Uses GDI BitBlt to capture window content and WIC to encode as PNG
// Only compiled in debug builds (GITSMARTER_DEBUG)

#ifdef GITSMARTER_DEBUG

#include "../include/ipc.h"
#include "../include/app.h"

// Forward declarations for globals in platform.cpp
extern HWND g_main_window;
extern IWICImagingFactory* g_wic_factory;

// ============================================================================
// PNG Encoding via WIC
// ============================================================================

static bool encode_hbitmap_to_png(HBITMAP hBitmap, int width, int height,
                                   uint8_t** out_buffer, size_t* out_size) {
    if (!g_wic_factory || !hBitmap) return false;

    IWICBitmap* wicBitmap = nullptr;
    IStream* stream = nullptr;
    IWICBitmapEncoder* encoder = nullptr;
    IWICBitmapFrameEncode* frame = nullptr;
    bool success = false;

    // Create WIC bitmap from HBITMAP
    HRESULT hr = g_wic_factory->CreateBitmapFromHBITMAP(
        hBitmap, nullptr, WICBitmapIgnoreAlpha, &wicBitmap);
    if (FAILED(hr)) goto cleanup;

    // Create in-memory stream for output
    hr = CreateStreamOnHGlobal(nullptr, TRUE, &stream);
    if (FAILED(hr)) goto cleanup;

    // Create PNG encoder
    hr = g_wic_factory->CreateEncoder(GUID_ContainerFormatPng, nullptr, &encoder);
    if (FAILED(hr)) goto cleanup;

    hr = encoder->Initialize(stream, WICBitmapEncoderNoCache);
    if (FAILED(hr)) goto cleanup;

    // Create and configure frame
    hr = encoder->CreateNewFrame(&frame, nullptr);
    if (FAILED(hr)) goto cleanup;

    hr = frame->Initialize(nullptr);
    if (FAILED(hr)) goto cleanup;

    hr = frame->SetSize(width, height);
    if (FAILED(hr)) goto cleanup;

    {
        WICPixelFormatGUID format = GUID_WICPixelFormat32bppBGRA;
        hr = frame->SetPixelFormat(&format);
        if (FAILED(hr)) goto cleanup;
    }

    // Write the bitmap data
    hr = frame->WriteSource(wicBitmap, nullptr);
    if (FAILED(hr)) goto cleanup;

    hr = frame->Commit();
    if (FAILED(hr)) goto cleanup;

    hr = encoder->Commit();
    if (FAILED(hr)) goto cleanup;

    // Get stream size and copy to output buffer
    {
        STATSTG stats = {};
        hr = stream->Stat(&stats, STATFLAG_NONAME);
        if (FAILED(hr)) goto cleanup;

        size_t size = (size_t)stats.cbSize.QuadPart;
        if (size > IPC::MAX_SCREENSHOT_SIZE) goto cleanup;

        uint8_t* buffer = new uint8_t[size];

        LARGE_INTEGER zero = {};
        hr = stream->Seek(zero, STREAM_SEEK_SET, nullptr);
        if (FAILED(hr)) {
            delete[] buffer;
            goto cleanup;
        }

        ULONG bytes_read = 0;
        hr = stream->Read(buffer, (ULONG)size, &bytes_read);
        if (FAILED(hr) || bytes_read != size) {
            delete[] buffer;
            goto cleanup;
        }

        *out_buffer = buffer;
        *out_size = size;
        success = true;
    }

cleanup:
    if (frame) frame->Release();
    if (encoder) encoder->Release();
    if (stream) stream->Release();
    if (wicBitmap) wicBitmap->Release();

    return success;
}

// ============================================================================
// Screenshot Capture Implementation
// ============================================================================

bool ipc_capture_screenshot_to_png(uint8_t** out_buffer, size_t* out_size) {
    if (!g_main_window || !out_buffer || !out_size) return false;

    *out_buffer = nullptr;
    *out_size = 0;

    // Get window dimensions
    RECT rc;
    if (!GetClientRect(g_main_window, &rc)) return false;

    int width = rc.right - rc.left;
    int height = rc.bottom - rc.top;
    if (width <= 0 || height <= 0) return false;

    // Create memory DC and bitmap
    HDC hdc = GetDC(g_main_window);
    if (!hdc) return false;

    HDC memDC = CreateCompatibleDC(hdc);
    if (!memDC) {
        ReleaseDC(g_main_window, hdc);
        return false;
    }

    HBITMAP hBitmap = CreateCompatibleBitmap(hdc, width, height);
    if (!hBitmap) {
        DeleteDC(memDC);
        ReleaseDC(g_main_window, hdc);
        return false;
    }

    HBITMAP oldBitmap = (HBITMAP)SelectObject(memDC, hBitmap);

    // Copy window content using BitBlt
    // Note: For Direct2D/DWM content, use PrintWindow instead for more reliable capture
    BOOL blit_ok = BitBlt(memDC, 0, 0, width, height, hdc, 0, 0, SRCCOPY);

    // If BitBlt failed, try PrintWindow as fallback (works better with DWM)
    if (!blit_ok) {
        // Clear the bitmap first
        HBRUSH black = (HBRUSH)GetStockObject(BLACK_BRUSH);
        FillRect(memDC, &rc, black);

        // PrintWindow captures the actual rendered content
        PrintWindow(g_main_window, memDC, PW_CLIENTONLY);
    }

    // Restore old bitmap before encoding
    SelectObject(memDC, oldBitmap);

    // Encode to PNG
    bool success = encode_hbitmap_to_png(hBitmap, width, height, out_buffer, out_size);

    // Cleanup GDI resources
    DeleteObject(hBitmap);
    DeleteDC(memDC);
    ReleaseDC(g_main_window, hdc);

    return success;
}

void ipc_free_screenshot_buffer(uint8_t* buffer) {
    if (buffer) {
        delete[] buffer;
    }
}

#endif // GITSMARTER_DEBUG
