// <AUTO-GENERATED TOC> DO NOT EDIT MANUALLY
// Table of Contents
//
// 1. ui_widgets_palette.cpp - Command Palette Widget (line 15)
// 2. Palette State (line 45)
// 3. Layout Calculation Helper (line 110)
// 4. Result Conversion Helpers (line 173)
// 5. Search Functions (line 210)
// 6. Mode Detection (line 520)
// 7. Command Execution (line 605)
// 8. Palette Widget (line 766)
// 9. Public API (line 1651)
//
// </AUTO-GENERATED TOC>
// ============================================================================
// ui_widgets_palette.cpp - Command Palette Widget
// ============================================================================
//
// Implements a VS Code-style command palette with:
// - Modal overlay without dimming
// - Text input with mode badge
// - Virtualized results list with category grouping
// - Fuzzy matching with match highlighting
// - Keyboard navigation
// - Multi-select support for batch operations
//
// Dependencies: ui_widgets_core.cpp, ui_widgets_basic.cpp, ui_widgets_dialog.cpp
// ============================================================================

#include "../../include/app.h"
#include "../../include/ui_theme.h"

// Forward declarations for external state
extern GitRepository g_repo;
extern HWND g_main_window;
extern EventDispatcher g_event_dispatcher;
extern ID2D1HwndRenderTarget* g_render_target;

// Forward declaration for text formats
extern IDWriteTextFormat* g_text_format_body;
extern IDWriteTextFormat* g_text_format_header;  // 11pt semi-bold (for group headers, badges)
extern IDWriteTextFormat* g_text_format_hint;    // 9pt normal (for hints, shortcuts)
extern IDWriteFactory* g_dwrite_factory;

// Extern declarations for blur effect (from platform.cpp)
extern ID2D1DeviceContext* g_d2d_device_context;
extern ID2D1Effect* g_blur_effect;
extern AnimationScheduler g_animation_scheduler;

// ============================================================================
// Palette State
// ============================================================================

static constexpr size_t PALETTE_MAX_RESULTS = 100;
static constexpr size_t PALETTE_MAX_QUERY = 256;

struct PaletteState {
    bool visible = false;
    PaletteMode mode = PaletteMode::AutoDetect;

    // Input
    wchar_t query[PALETTE_MAX_QUERY] = {0};
    size_t query_len = 0;
    size_t cursor_pos = 0;

    // Results
    PaletteResult results[PALETTE_MAX_RESULTS];
    size_t result_count = 0;

    // Selection
    int selected_index = 0;
    int hovered_index = -1;  // For hover highlighting
    int scroll_offset = 0;

    // Multi-select
    bool multi_select_mode = false;
    size_t selected_count = 0;

    // Display text cache for non-wchar_t sources
    wchar_t display_cache[PALETTE_MAX_RESULTS][512];

    // UTF-8 path cache for file/remote results
    char path_cache[PALETTE_MAX_RESULTS][512];

    // Inline input mode (for commands requiring input like Create Branch)
    bool input_mode = false;
    const PaletteCommand* pending_command = nullptr;

    // Animation (simplified single-layer model: scale entire palette with blur)
    bool animating = false;
    bool dismissing = false;          // True if animating out

    // Spring animation state (single spring for scale, opacity follows progress)
    float anim_scale = 1.0f;          // 0.92 → 1.0 (spring physics)
    float anim_velocity = 0.0f;       // Spring velocity
    float anim_opacity = 0.0f;        // 0 → 1 (linear, tied to spring progress)
    float anim_blur = 0.0f;           // BLUR_RADIUS → 0 (tied to opacity)

    bool is_animating = false;        // AnimationScheduler registration tracking
};

// Forward declaration
static void command_palette_finish_hide();

static PaletteState g_palette;

// Spring physics uses global spring_update_windows_style() from platform.cpp
// (analytical solution - frame-rate independent)

// ============================================================================
// Layout Calculation Helper
// ============================================================================

// Returns the height of the results section and count of visible items
// This accounts for MAX_VISIBLE_ITEMS cap and group headers in AutoDetect mode
struct ResultsLayout {
    float height;
    int visible_count;
};

// Minimum height for empty state area (message + hint + padding)
static constexpr float EMPTY_STATE_HEIGHT = 64.0f;

// Check if items [from_index, to_index] fit within the visible area
static bool items_fit_in_view(int from_index, int to_index) {
    using namespace CommandPalette;

    float height = 0.0f;
    float max_height = MAX_VISIBLE_ITEMS * ITEM_HEIGHT;
    PaletteResultType last_type = (PaletteResultType)-1;

    for (int i = from_index; i <= to_index && i < (int)g_palette.result_count; i++) {
        float item_height = ITEM_HEIGHT;

        if (g_palette.mode == PaletteMode::AutoDetect && g_palette.results[i].type != last_type) {
            item_height += GROUP_HEADER_HEIGHT;
            last_type = g_palette.results[i].type;
        }

        height += item_height;
        if (height > max_height) return false;
    }

    return true;
}

static ResultsLayout calculate_results_layout() {
    using namespace CommandPalette;
    ResultsLayout layout = {0.0f, 0};

    if (g_palette.result_count == 0) {
        // Reserve space for empty state message when user has typed a query
        if (g_palette.query_len > 0 && !g_palette.input_mode) {
            layout.height = EMPTY_STATE_HEIGHT;
        }
        return layout;
    }

    PaletteResultType last_type = (PaletteResultType)-1;
    for (size_t i = 0; i < g_palette.result_count && layout.visible_count < (int)MAX_VISIBLE_ITEMS; i++) {
        // Add group header height when type changes in AutoDetect mode
        if (g_palette.mode == PaletteMode::AutoDetect && g_palette.results[i].type != last_type) {
            layout.height += GROUP_HEADER_HEIGHT;
            last_type = g_palette.results[i].type;
        }
        layout.height += ITEM_HEIGHT;
        layout.visible_count++;
    }

    return layout;
}

// ============================================================================
// Result Conversion Helpers
// ============================================================================

static const wchar_t* get_mode_name(PaletteMode mode) {
    switch (mode) {
        case PaletteMode::Commands: return L"Commands";
        case PaletteMode::Files:    return L"Files";
        case PaletteMode::Branches: return L"Branches";
        case PaletteMode::Commits:  return L"Commits";
        case PaletteMode::Remotes:  return L"Remotes";
        default:                     return L"";
    }
}

static uint32_t get_mode_badge_color(PaletteMode mode) {
    switch (mode) {
        case PaletteMode::Commands: return CommandPalette::BADGE_COMMANDS;
        case PaletteMode::Files:    return CommandPalette::BADGE_FILES;
        case PaletteMode::Branches: return CommandPalette::BADGE_BRANCHES;
        case PaletteMode::Commits:  return CommandPalette::BADGE_COMMITS;
        case PaletteMode::Remotes:  return CommandPalette::BADGE_REMOTES;
        default:                     return CommandPalette::BADGE_COMMANDS;
    }
}

static const wchar_t* get_category_name(PaletteResultType type) {
    switch (type) {
        case PaletteResultType::Command: return L"Commands";
        case PaletteResultType::File:    return L"Files";
        case PaletteResultType::Branch:  return L"Branches";
        case PaletteResultType::Commit:  return L"Commits";
        case PaletteResultType::Remote:  return L"Remotes";
        default:                          return L"Results";
    }
}

// ============================================================================
// Search Functions
// ============================================================================

static void palette_search_commands() {
    size_t count = command_registry_count();

    for (size_t i = 0; i < count && g_palette.result_count < PALETTE_MAX_RESULTS; i++) {
        const PaletteCommand* cmd = command_registry_get(i);
        if (!cmd) continue;

        // Skip commands that aren't available in current context
        if (cmd->is_available && !cmd->is_available()) continue;

        // Match against command name
        FuzzyMatchResult match = fuzzy_match(g_palette.query, cmd->name);

        // Also try matching against command ID (e.g., "git.stageAll")
        if (!match.matched) {
            wchar_t id_wide[128];
            utf8_to_wide(cmd->id, id_wide, 128);
            match = fuzzy_match(g_palette.query, id_wide);
        }

        if (match.matched || g_palette.query_len == 0) {
            PaletteResult& r = g_palette.results[g_palette.result_count++];
            r.type = PaletteResultType::Command;
            r.score = match.score;
            r.match_mask = match.match_mask;
            r.command = cmd;
            r.display_text = cmd->name;
            r.shortcut = cmd->shortcut;
            r.selected = false;
        }
    }
}

// Forward declarations for sidebar access (defined in platform.cpp)
extern size_t palette_get_branch_count();
extern const GitRef* palette_get_branch(size_t index);
extern size_t palette_get_staged_file_count();
extern const wchar_t* palette_get_staged_file_path(size_t index);
extern int palette_get_staged_file_status(size_t index);
extern size_t palette_get_unstaged_file_count();
extern const wchar_t* palette_get_unstaged_file_path(size_t index);
extern int palette_get_unstaged_file_status(size_t index);

static void palette_search_branches() {
    size_t count = palette_get_branch_count();

    for (size_t i = 0; i < count && g_palette.result_count < PALETTE_MAX_RESULTS; i++) {
        const GitRef* ref = palette_get_branch(i);

        // Convert branch name to wide string
        wchar_t name_wide[Git::MAX_REF_NAME];
        utf8_to_wide(ref->name, name_wide, Git::MAX_REF_NAME);

        FuzzyMatchResult match = fuzzy_match(g_palette.query, name_wide);

        if (match.matched || g_palette.query_len == 0) {
            PaletteResult& r = g_palette.results[g_palette.result_count];
            r.type = PaletteResultType::Branch;
            r.score = match.score;
            r.match_mask = match.match_mask;
            r.branch = ref;

            // Store display text in cache
            wcscpy_s(g_palette.display_cache[g_palette.result_count], 512, name_wide);
            r.display_text = g_palette.display_cache[g_palette.result_count];
            r.shortcut = nullptr;
            r.selected = false;

            g_palette.result_count++;
        }
    }
}

static void palette_search_files() {
    // Search staged files
    size_t staged_count = palette_get_staged_file_count();
    for (size_t i = 0; i < staged_count && g_palette.result_count < PALETTE_MAX_RESULTS; i++) {
        const wchar_t* path_wide = palette_get_staged_file_path(i);
        if (!path_wide) continue;

        FuzzyMatchResult match = fuzzy_match(g_palette.query, path_wide);

        if (match.matched || g_palette.query_len == 0) {
            size_t idx = g_palette.result_count;
            PaletteResult& r = g_palette.results[idx];
            r.type = PaletteResultType::File;
            r.score = match.score;
            r.match_mask = match.match_mask;

            // Store UTF-8 path in cache for git commands
            wide_to_utf8(path_wide, g_palette.path_cache[idx], 512);
            r.file.utf8_path = g_palette.path_cache[idx];
            r.file.is_staged = true;
            r.file.status = static_cast<PaletteResult::FileStatus>(palette_get_staged_file_status(i));

            // Store display text
            wcscpy_s(g_palette.display_cache[idx], 512, path_wide);
            r.display_text = g_palette.display_cache[idx];
            r.shortcut = nullptr;
            r.selected = false;

            g_palette.result_count++;
        }
    }

    // Search unstaged files
    size_t unstaged_count = palette_get_unstaged_file_count();
    for (size_t i = 0; i < unstaged_count && g_palette.result_count < PALETTE_MAX_RESULTS; i++) {
        const wchar_t* path_wide = palette_get_unstaged_file_path(i);
        if (!path_wide) continue;

        FuzzyMatchResult match = fuzzy_match(g_palette.query, path_wide);

        if (match.matched || g_palette.query_len == 0) {
            size_t idx = g_palette.result_count;
            PaletteResult& r = g_palette.results[idx];
            r.type = PaletteResultType::File;
            r.score = match.score;
            r.match_mask = match.match_mask;

            // Store UTF-8 path in cache for git commands
            wide_to_utf8(path_wide, g_palette.path_cache[idx], 512);
            r.file.utf8_path = g_palette.path_cache[idx];
            r.file.is_staged = false;
            r.file.status = static_cast<PaletteResult::FileStatus>(palette_get_unstaged_file_status(i));

            // Store display text
            wcscpy_s(g_palette.display_cache[idx], 512, path_wide);
            r.display_text = g_palette.display_cache[idx];
            r.shortcut = nullptr;
            r.selected = false;

            g_palette.result_count++;
        }
    }
}

static void palette_search_remotes() {
    GitRemote remotes[16];
    size_t count = git_remote_list(&g_repo, remotes, 16);

    for (size_t i = 0; i < count && g_palette.result_count < PALETTE_MAX_RESULTS; i++) {
        wchar_t name_wide[Git::MAX_REF_NAME];
        utf8_to_wide(remotes[i].name, name_wide, Git::MAX_REF_NAME);

        FuzzyMatchResult match = fuzzy_match(g_palette.query, name_wide);

        if (match.matched || g_palette.query_len == 0) {
            size_t idx = g_palette.result_count;
            PaletteResult& r = g_palette.results[idx];
            r.type = PaletteResultType::Remote;
            r.score = match.score;
            r.match_mask = match.match_mask;

            // Store remote name in UTF-8 cache
            strcpy_s(g_palette.path_cache[idx], 512, remotes[i].name);
            r.remote_name = g_palette.path_cache[idx];

            wcscpy_s(g_palette.display_cache[idx], 512, name_wide);
            r.display_text = g_palette.display_cache[idx];
            r.shortcut = nullptr;
            r.selected = false;

            g_palette.result_count++;
        }
    }
}

// Forward declarations for commit history access (defined in platform.cpp)
extern size_t palette_get_commit_count();
extern const CommitMeta* palette_get_commit(size_t index);
extern const char* palette_get_commit_message(size_t index);

// Convert SHA bytes to hex string
static void sha_to_hex(const uint8_t* sha, char* hex_out, size_t hex_size) {
    static const char hex_chars[] = "0123456789abcdef";
    size_t max_bytes = (hex_size - 1) / 2;
    if (max_bytes > Git::SHA1_RAW_SIZE) max_bytes = Git::SHA1_RAW_SIZE;
    for (size_t i = 0; i < max_bytes; i++) {
        hex_out[i * 2] = hex_chars[(sha[i] >> 4) & 0x0F];
        hex_out[i * 2 + 1] = hex_chars[sha[i] & 0x0F];
    }
    hex_out[max_bytes * 2] = '\0';
}

static void palette_search_commits() {
    // Limit to recent 1000 commits for performance
    size_t total_count = palette_get_commit_count();
    size_t search_limit = (total_count < 1000) ? total_count : 1000;

    for (size_t i = 0; i < search_limit && g_palette.result_count < PALETTE_MAX_RESULTS; i++) {
        const CommitMeta* commit = palette_get_commit(i);
        if (!commit) continue;

        const char* message = palette_get_commit_message(i);
        if (!message) continue;

        // Get SHA as hex for matching
        char sha_hex[41];
        sha_to_hex(commit->sha, sha_hex, sizeof(sha_hex));

        // Convert message to wide for fuzzy matching
        wchar_t message_wide[512];
        utf8_to_wide(message, message_wide, 512);

        // Also try matching against SHA prefix
        wchar_t sha_wide[41];
        utf8_to_wide(sha_hex, sha_wide, 41);

        FuzzyMatchResult match = fuzzy_match(g_palette.query, message_wide);
        bool matched_message = match.matched;
        if (!match.matched) {
            match = fuzzy_match(g_palette.query, sha_wide);
        }

        if (match.matched || g_palette.query_len == 0) {
            size_t idx = g_palette.result_count;
            PaletteResult& r = g_palette.results[idx];
            r.type = PaletteResultType::Commit;
            r.score = match.score;
            r.commit_index = i;

            // Format display: "sha_short - message"
            char short_sha[8];
            strncpy_s(short_sha, sizeof(short_sha), sha_hex, 7);
            short_sha[7] = '\0';

            // Display format adds "sha_short - " prefix (10 chars) before message.
            // match_mask is 64 bits; shifting by PREFIX_LEN means we can only
            // preserve highlights for the first (64 - PREFIX_LEN) chars of the
            // message. Mask before shift to make the truncation explicit (so
            // higher bits don't undefined-behavior into something garbage on
            // future ISA changes).
            constexpr size_t PREFIX_LEN = 10;  // "abc1234 - "
            constexpr uint64_t MESSAGE_MASK_BITS = (1ULL << (64 - PREFIX_LEN)) - 1;
            if (matched_message && match.match_mask != 0) {
                r.match_mask = (match.match_mask & MESSAGE_MASK_BITS) << PREFIX_LEN;
            } else {
                r.match_mask = match.match_mask;  // SHA match - no offset needed
            }

            char display_utf8[512];
            snprintf(display_utf8, sizeof(display_utf8), "%s - %.60s%s",
                     short_sha, message, (strlen(message) > 60) ? "..." : "");
            utf8_to_wide(display_utf8, g_palette.display_cache[idx], 512);
            r.display_text = g_palette.display_cache[idx];
            r.shortcut = nullptr;
            r.selected = false;

            g_palette.result_count++;
        }
    }
}

// Sort results by score (descending)
static int compare_results(const void* a, const void* b) {
    const PaletteResult* ra = (const PaletteResult*)a;
    const PaletteResult* rb = (const PaletteResult*)b;

    // First by type (for grouping in mixed mode)
    if (ra->type != rb->type) {
        return (int)ra->type - (int)rb->type;
    }

    // Then by score (descending)
    return rb->score - ra->score;
}

static void palette_update_search() {
    g_palette.result_count = 0;
    g_palette.selected_index = 0;
    g_palette.scroll_offset = 0;

    switch (g_palette.mode) {
        case PaletteMode::Commands:
            palette_search_commands();
            break;

        case PaletteMode::Files:
            palette_search_files();
            break;

        case PaletteMode::Branches:
            palette_search_branches();
            break;

        case PaletteMode::Remotes:
            palette_search_remotes();
            break;

        case PaletteMode::Commits:
            palette_search_commits();
            break;

        case PaletteMode::AutoDetect:
        default:
            // Search all scopes
            palette_search_commands();
            palette_search_branches();
            palette_search_files();
            palette_search_remotes();
            palette_search_commits();  // Include commits in auto-detect results
            break;
    }

    // Sort results
    if (g_palette.result_count > 1) {
        qsort(g_palette.results, g_palette.result_count, sizeof(PaletteResult), compare_results);
    }
}

// ============================================================================
// Mode Detection
// ============================================================================

static void palette_detect_mode() {
    if (g_palette.query_len == 0) {
        g_palette.mode = PaletteMode::AutoDetect;
        return;
    }

    wchar_t first = g_palette.query[0];

    switch (first) {
        case L'>':
            g_palette.mode = PaletteMode::Commands;
            // Shift query to remove prefix
            if (g_palette.query_len > 1) {
                wmemmove(g_palette.query, g_palette.query + 1, g_palette.query_len);
                g_palette.query_len--;
                if (g_palette.cursor_pos > 0) g_palette.cursor_pos--;
            } else {
                g_palette.query[0] = L'\0';
                g_palette.query_len = 0;
                g_palette.cursor_pos = 0;
            }
            break;

        case L'/':
            g_palette.mode = PaletteMode::Files;
            if (g_palette.query_len > 1) {
                wmemmove(g_palette.query, g_palette.query + 1, g_palette.query_len);
                g_palette.query_len--;
                if (g_palette.cursor_pos > 0) g_palette.cursor_pos--;
            } else {
                g_palette.query[0] = L'\0';
                g_palette.query_len = 0;
                g_palette.cursor_pos = 0;
            }
            break;

        case L'@':
            g_palette.mode = PaletteMode::Branches;
            if (g_palette.query_len > 1) {
                wmemmove(g_palette.query, g_palette.query + 1, g_palette.query_len);
                g_palette.query_len--;
                if (g_palette.cursor_pos > 0) g_palette.cursor_pos--;
            } else {
                g_palette.query[0] = L'\0';
                g_palette.query_len = 0;
                g_palette.cursor_pos = 0;
            }
            break;

        case L'#':
            g_palette.mode = PaletteMode::Commits;
            if (g_palette.query_len > 1) {
                wmemmove(g_palette.query, g_palette.query + 1, g_palette.query_len);
                g_palette.query_len--;
                if (g_palette.cursor_pos > 0) g_palette.cursor_pos--;
            } else {
                g_palette.query[0] = L'\0';
                g_palette.query_len = 0;
                g_palette.cursor_pos = 0;
            }
            break;

        case L':':
            g_palette.mode = PaletteMode::Remotes;
            if (g_palette.query_len > 1) {
                wmemmove(g_palette.query, g_palette.query + 1, g_palette.query_len);
                g_palette.query_len--;
                if (g_palette.cursor_pos > 0) g_palette.cursor_pos--;
            } else {
                g_palette.query[0] = L'\0';
                g_palette.query_len = 0;
                g_palette.cursor_pos = 0;
            }
            break;

        default:
            // Keep current mode or auto-detect
            break;
    }
}

// ============================================================================
// Command Execution
// ============================================================================

// Enter inline input mode for commands requiring input
static void palette_enter_input_mode(const PaletteCommand* cmd) {
    g_palette.input_mode = true;
    g_palette.pending_command = cmd;

    // Clear query for new input
    g_palette.query[0] = L'\0';
    g_palette.query_len = 0;
    g_palette.cursor_pos = 0;

    // Clear results
    g_palette.result_count = 0;
    g_palette.selected_index = 0;
    g_palette.scroll_offset = 0;

    InvalidateRect(g_main_window, nullptr, FALSE);
}

// Exit inline input mode without executing
static void palette_exit_input_mode() {
    g_palette.input_mode = false;
    g_palette.pending_command = nullptr;

    // Clear query and restore normal mode
    g_palette.query[0] = L'\0';
    g_palette.query_len = 0;
    g_palette.cursor_pos = 0;
    g_palette.mode = PaletteMode::AutoDetect;

    // Refresh search to show commands again
    palette_update_search();
    InvalidateRect(g_main_window, nullptr, FALSE);
}

// Forward declarations for command execution with input (implemented in platform.cpp)
extern void cmd_create_branch_with_name(const char* branch_name);
extern void cmd_switch_branch_by_name(const char* branch_name);
extern void cmd_palette_stage_file(const char* path);
extern void cmd_palette_unstage_file(const char* path);
extern void cmd_palette_show_commit(size_t commit_index);
extern void cmd_palette_fetch_remote(const char* remote_name);

// Execute a command with user-provided input
static void palette_execute_with_input(const PaletteCommand* cmd, const wchar_t* input) {
    if (!cmd || !input) return;

    // Convert input to UTF-8
    char input_utf8[512];
    WideCharToMultiByte(CP_UTF8, 0, input, -1, input_utf8, sizeof(input_utf8), nullptr, nullptr);

    // Handle specific commands that need input
    if (strcmp(cmd->id, "git.createBranch") == 0 || strcmp(cmd->id, "git.createBranchFromHead") == 0) {
        cmd_create_branch_with_name(input_utf8);
    } else if (strcmp(cmd->id, "git.switchBranch") == 0) {
        cmd_switch_branch_by_name(input_utf8);
    } else {
        // Fallback: just execute without input
        if (cmd->execute) {
            cmd->execute();
        }
    }

    InvalidateRect(g_main_window, nullptr, FALSE);
}

static void palette_execute_result(const PaletteResult& result) {
    switch (result.type) {
        case PaletteResultType::Command:
            if (result.command) {
                // Check if command requires input
                if (result.command->requires_input) {
                    palette_enter_input_mode(result.command);
                    return;  // Don't hide palette - we're entering input mode
                }
                // Execute immediately
                command_palette_hide();
                if (result.command->execute) {
                    result.command->execute();
                }
            }
            break;

        case PaletteResultType::Branch:
            command_palette_hide();
            if (result.branch) {
                // Checkout the branch
                CheckoutOptions opts = {};
                CheckoutResult res = {};
                git_branch_checkout(&g_repo, result.branch, &opts, &res);
            }
            break;

        case PaletteResultType::File:
            command_palette_hide();
            if (result.file.utf8_path) {
                // Toggle stage/unstage based on current state
                if (result.file.is_staged) {
                    cmd_palette_unstage_file(result.file.utf8_path);
                } else {
                    cmd_palette_stage_file(result.file.utf8_path);
                }
            }
            break;

        case PaletteResultType::Commit:
            command_palette_hide();
            cmd_palette_show_commit(result.commit_index);
            break;

        case PaletteResultType::Remote:
            command_palette_hide();
            if (result.remote_name) {
                cmd_palette_fetch_remote(result.remote_name);
            }
            break;
    }
}

static void palette_execute_batch_action() {
    // Count staged vs unstaged selected files
    size_t staged_count = 0;
    size_t unstaged_count = 0;
    for (size_t i = 0; i < g_palette.result_count; i++) {
        const PaletteResult& r = g_palette.results[i];
        if (r.type == PaletteResultType::File && r.selected) {
            if (r.file.is_staged) {
                staged_count++;
            } else {
                unstaged_count++;
            }
        }
    }

    // Determine action: if more unstaged selected, stage them; otherwise unstage
    bool should_stage = (unstaged_count >= staged_count);

    // Execute batch action
    for (size_t i = 0; i < g_palette.result_count; i++) {
        PaletteResult& r = g_palette.results[i];
        if (r.type == PaletteResultType::File && r.selected && r.file.utf8_path) {
            if (should_stage && !r.file.is_staged) {
                cmd_palette_stage_file(r.file.utf8_path);
            } else if (!should_stage && r.file.is_staged) {
                cmd_palette_unstage_file(r.file.utf8_path);
            }
        }
    }

    // Clear selection and hide palette
    for (size_t i = 0; i < g_palette.result_count; i++) {
        g_palette.results[i].selected = false;
    }
    g_palette.selected_count = 0;
    g_palette.multi_select_mode = false;
    command_palette_hide();
}

// ============================================================================
// Palette Widget
// ============================================================================

struct CommandPaletteWidget : Widget {
    IDWriteTextFormat* input_format = nullptr;
    IDWriteTextFormat* item_format = nullptr;
    IDWriteTextFormat* shortcut_format = nullptr;
    IDWriteTextFormat* header_format = nullptr;

    CommandPaletteWidget() {
        width_mode = SizeMode::Fill;
        height_mode = SizeMode::Fill;
        flags = WidgetFlags::Visible | WidgetFlags::Focusable;
    }

    void measure(const LayoutConstraints& constraints) override {
        rect.width = constraints.max_width;
        rect.height = constraints.max_height;
    }

    void layout() override {
        // No children to layout - we render everything directly
    }

    bool on_escape() override {
        if (g_palette.visible) {
            // If in input mode, exit input mode first (don't close palette)
            if (g_palette.input_mode) {
                palette_exit_input_mode();
                return true;
            }
            // Otherwise close the palette
            command_palette_hide();
            return true;
        }
        return false;
    }

    void render(RenderContext& ctx) override {
        if (!g_palette.visible) return;

        using namespace CommandPalette;

        // ==================== SINGLE-LAYER ANIMATION MODEL ====================
        //
        // Entire palette scales together (background + content) with subtle blur.
        // Scale transform origin is top-center, creating a "grow from top" effect.
        // No separate content layer - everything animates as one cohesive unit.

        // Early exit if completely invisible
        if (g_palette.anim_opacity <= 0.0f) return;

        // Helper to apply opacity to ARGB color
        auto apply_opacity = [](uint32_t color, float opacity) -> uint32_t {
            uint32_t a = (color >> 24) & 0xFF;
            a = static_cast<uint32_t>(a * opacity);
            return (a << 24) | (color & 0x00FFFFFF);
        };

        // Calculate palette position (top-center)
        float palette_x = (rect.width - WIDTH) / 2.0f;
        float palette_y = TOP_OFFSET;

        // Calculate palette height based on results
        ResultsLayout results_layout = calculate_results_layout();
        float results_height = results_layout.height;

        float palette_height = INPUT_ROW_HEIGHT + results_height + HINT_ROW_HEIGHT;
        if (g_palette.multi_select_mode && g_palette.selected_count > 0) {
            palette_height += BATCH_ACTION_HEIGHT;
        }

        // Save current transform
        D2D1_MATRIX_3X2_F old_transform;
        ctx.target->GetTransform(&old_transform);

        // Calculate scale transform (origin at top-center)
        float scale = g_palette.anim_scale;
        float origin_x = palette_x + WIDTH * 0.5f;  // Horizontal center
        float origin_y = palette_y;                  // Top edge

        D2D1_MATRIX_3X2_F scale_transform =
            D2D1::Matrix3x2F::Translation(-origin_x, -origin_y) *
            D2D1::Matrix3x2F::Scale(scale, scale) *
            D2D1::Matrix3x2F::Translation(origin_x, origin_y);
        ctx.target->SetTransform(old_transform * scale_transform);

        // Palette rect (in unscaled coordinates - transform handles the scaling)
        D2D1_RECT_F palette_rect = D2D1::RectF(
            palette_x, palette_y,
            palette_x + WIDTH, palette_y + palette_height
        );

        // Draw shadow (only when mostly visible)
        if (g_palette.anim_opacity > 0.5f) {
            ctx.draw_dialog_shadow(palette_rect, CORNER_RADIUS);
        }

        // Draw background with opacity
        ctx.fill_rounded_rect(palette_rect, CORNER_RADIUS,
                              apply_opacity(BG, g_palette.anim_opacity));

        // Draw input row
        float input_y = palette_y;
        D2D1_RECT_F input_bg_rect = D2D1::RectF(
            palette_x + 1, input_y + 1,
            palette_x + WIDTH - 1, input_y + INPUT_ROW_HEIGHT
        );

        // Top corners rounded, bottom not
        ctx.fill_rect(input_bg_rect, apply_opacity(INPUT_BG, g_palette.anim_opacity));

        // Draw mode badge (shows mode name, or command name in input mode)
        float text_x = palette_x + INPUT_PADDING;
        bool show_badge = g_palette.input_mode || g_palette.mode != PaletteMode::AutoDetect;
        if (show_badge) {
            const wchar_t* badge_text;
            uint32_t badge_color;

            if (g_palette.input_mode && g_palette.pending_command) {
                // In input mode: show command name
                badge_text = g_palette.pending_command->name;
                badge_color = CommandPalette::BADGE_COMMANDS;  // Use command color
            } else {
                // Normal mode: show mode name
                badge_text = get_mode_name(g_palette.mode);
                badge_color = get_mode_badge_color(g_palette.mode);
            }

            // Measure badge text
            IDWriteTextLayout* badge_layout = nullptr;
            if (g_dwrite_factory && g_text_format_header) {
                g_dwrite_factory->CreateTextLayout(
                    badge_text, (UINT32)wcslen(badge_text),
                    g_text_format_header,
                    200.0f, BADGE_HEIGHT,
                    &badge_layout
                );
            }

            float badge_width = 60.0f;  // Default
            if (badge_layout) {
                DWRITE_TEXT_METRICS metrics;
                badge_layout->GetMetrics(&metrics);
                badge_width = metrics.width + BADGE_PADDING_H * 2;
                badge_layout->Release();
            }

            float badge_y = input_y + (INPUT_ROW_HEIGHT - BADGE_HEIGHT) / 2.0f;
            D2D1_RECT_F badge_rect = D2D1::RectF(
                text_x, badge_y,
                text_x + badge_width, badge_y + BADGE_HEIGHT
            );
            ctx.fill_rounded_rect(badge_rect, BADGE_RADIUS, badge_color);

            // Badge text
            if (g_text_format_header) {
                D2D1_RECT_F badge_text_rect = D2D1::RectF(
                    text_x + BADGE_PADDING_H, badge_y,
                    text_x + badge_width - BADGE_PADDING_H, badge_y + BADGE_HEIGHT
                );
                ctx.draw_text(badge_text, wcslen(badge_text), g_text_format_header, badge_text_rect, 0xFF1E1E1E);
            }

            text_x += badge_width + ITEM_PADDING;
        }

        // Draw query text or placeholder
        if (g_text_format_body) {
            float input_text_y = input_y + (INPUT_ROW_HEIGHT - 20.0f) / 2.0f;
            D2D1_RECT_F text_rect = D2D1::RectF(
                text_x, input_text_y,
                palette_x + WIDTH - INPUT_PADDING, input_text_y + 20.0f
            );

            if (g_palette.query_len > 0) {
                ctx.draw_text(g_palette.query, g_palette.query_len, g_text_format_body, text_rect, INPUT_TEXT);
            } else {
                // Show input prompt if in input mode, otherwise show mode-specific placeholder
                const wchar_t* placeholder;
                if (g_palette.input_mode && g_palette.pending_command && g_palette.pending_command->input_prompt) {
                    placeholder = g_palette.pending_command->input_prompt;
                } else {
                    switch (g_palette.mode) {
                        case PaletteMode::Commands: placeholder = L"Search commands..."; break;
                        case PaletteMode::Files:    placeholder = L"Search files..."; break;
                        case PaletteMode::Branches: placeholder = L"Search branches..."; break;
                        case PaletteMode::Commits:  placeholder = L"Search commits..."; break;
                        case PaletteMode::Remotes:  placeholder = L"Search remotes..."; break;
                        default:                    placeholder = L"Type to search commands, files, branches..."; break;
                    }
                }
                ctx.draw_text(placeholder, wcslen(placeholder), g_text_format_body, text_rect, PLACEHOLDER_TEXT);
            }

            // Draw cursor - measure actual text width for accurate placement
            float cursor_x = text_x;
            if (g_palette.cursor_pos > 0 && g_dwrite_factory) {
                IDWriteTextLayout* cursor_layout = nullptr;
                HRESULT hr = g_dwrite_factory->CreateTextLayout(
                    g_palette.query,
                    (UINT32)g_palette.cursor_pos,
                    g_text_format_body,
                    1000.0f, 100.0f,
                    &cursor_layout
                );
                if (SUCCEEDED(hr) && cursor_layout) {
                    DWRITE_TEXT_METRICS metrics;
                    cursor_layout->GetMetrics(&metrics);
                    cursor_x = text_x + metrics.width;
                    cursor_layout->Release();
                }
            }
            if (cursor_x < palette_x + WIDTH - INPUT_PADDING) {
                ctx.draw_line(cursor_x, input_text_y + 2, cursor_x, input_text_y + 16, INPUT_TEXT, 1.0f);
            }
        }

        // Draw batch action bar (when items are selected)
        float item_y = input_y + INPUT_ROW_HEIGHT;
        if (g_palette.multi_select_mode && g_palette.selected_count > 0) {
            D2D1_RECT_F batch_rect = D2D1::RectF(
                palette_x + 1, item_y,
                palette_x + WIDTH - 1, item_y + BATCH_ACTION_HEIGHT
            );
            ctx.fill_rect(batch_rect, BATCH_ACTION_BG);

            // Batch action text (centered)
            if (g_text_format_body && g_dwrite_factory) {
                // Count staged vs unstaged
                size_t staged = 0, unstaged = 0;
                for (size_t j = 0; j < g_palette.result_count; j++) {
                    const PaletteResult& pr = g_palette.results[j];
                    if (pr.type == PaletteResultType::File && pr.selected) {
                        if (pr.file.is_staged) staged++; else unstaged++;
                    }
                }
                bool will_stage = (unstaged >= staged);
                wchar_t batch_text[128];
                swprintf_s(batch_text, 128, L"%s %zu file%s",
                    will_stage ? L"Stage" : L"Unstage",
                    g_palette.selected_count,
                    g_palette.selected_count == 1 ? L"" : L"s");

                float batch_text_y = item_y + (BATCH_ACTION_HEIGHT - TEXT_LINE_HEIGHT) / 2.0f;
                IDWriteTextLayout* layout = nullptr;
                HRESULT hr = g_dwrite_factory->CreateTextLayout(
                    batch_text, (UINT32)wcslen(batch_text),
                    g_text_format_body, WIDTH - 2 * ITEM_PADDING, TEXT_LINE_HEIGHT, &layout);
                if (SUCCEEDED(hr) && layout) {
                    layout->SetTextAlignment(DWRITE_TEXT_ALIGNMENT_CENTER);
                    ctx.brush->SetColor(color_from_argb(BATCH_ACTION_TEXT));
                    ctx.target->DrawTextLayout(
                        D2D1::Point2F(palette_x + ITEM_PADDING, batch_text_y),
                        layout, ctx.brush);
                    layout->Release();
                }
            }
            item_y += BATCH_ACTION_HEIGHT;
        }

        // Draw results - track rendered height to match the palette's allocated results area
        // We stop when item_y would exceed results_height (calculated earlier, includes headers)
        float results_start_y = item_y;
        PaletteResultType last_type = (PaletteResultType)-1;
        int items_rendered = 0;

        for (size_t i = g_palette.scroll_offset; i < g_palette.result_count; i++) {
            const PaletteResult& r = g_palette.results[i];

            // Calculate height needed for this item (including header if type changes)
            float item_total_height = ITEM_HEIGHT;
            if (g_palette.mode == PaletteMode::AutoDetect && r.type != last_type) {
                item_total_height += GROUP_HEADER_HEIGHT;
            }

            // Check if this item would exceed available space
            if ((item_y - results_start_y) + item_total_height > results_height) {
                break;  // No more space
            }

            // Draw group header in mixed mode
            if (g_palette.mode == PaletteMode::AutoDetect && r.type != last_type) {
                const wchar_t* header = get_category_name(r.type);
                D2D1_RECT_F header_rect = D2D1::RectF(
                    palette_x + ITEM_PADDING, item_y,
                    palette_x + WIDTH - ITEM_PADDING, item_y + GROUP_HEADER_HEIGHT
                );

                if (g_text_format_header) {
                    ctx.draw_text(header, wcslen(header), g_text_format_header, header_rect, GROUP_HEADER_TEXT);
                }

                // Draw separator line
                ctx.draw_line(
                    palette_x + ITEM_PADDING, item_y + GROUP_HEADER_HEIGHT - 1,
                    palette_x + WIDTH - ITEM_PADDING, item_y + GROUP_HEADER_HEIGHT - 1,
                    BORDER, 1.0f
                );

                item_y += GROUP_HEADER_HEIGHT;
                last_type = r.type;
            }

            // Item background
            D2D1_RECT_F item_rect = D2D1::RectF(
                palette_x + 1, item_y,
                palette_x + WIDTH - 1, item_y + ITEM_HEIGHT
            );

            bool is_selected = ((int)i == g_palette.selected_index);
            bool is_hovered = ((int)i == g_palette.hovered_index);

            if (is_selected) {
                ctx.fill_rect(item_rect, SELECTED_BG);
                // Selection indicator
                ctx.fill_rect(D2D1::RectF(palette_x + 1, item_y, palette_x + 1 + SELECTION_BORDER_WIDTH, item_y + ITEM_HEIGHT),
                              Theme::SELECTION_BORDER);
            } else if (is_hovered) {
                ctx.fill_rect(item_rect, HOVER_BG);
            }

            // Item text
            float item_text_x = palette_x + ITEM_PADDING + SELECTION_BORDER_WIDTH;
            float item_text_y = item_y + (ITEM_HEIGHT - TEXT_LINE_HEIGHT) / 2.0f;

            // Checkbox for files (shown when in multi-select mode or item is selected)
            if (r.type == PaletteResultType::File && (g_palette.multi_select_mode || r.selected)) {
                float checkbox_size = 14.0f;
                float checkbox_y = item_y + (ITEM_HEIGHT - checkbox_size) / 2.0f;
                D2D1_RECT_F checkbox_rect = D2D1::RectF(
                    item_text_x, checkbox_y,
                    item_text_x + checkbox_size, checkbox_y + checkbox_size
                );

                // Checkbox border
                ctx.brush->SetColor(color_from_argb(r.selected ? MULTI_SELECT_CHECK : BORDER));
                ctx.target->DrawRectangle(checkbox_rect, ctx.brush, 1.0f);

                // Checkmark if selected
                if (r.selected) {
                    ctx.fill_rect(D2D1::RectF(
                        item_text_x + 2, checkbox_y + 2,
                        item_text_x + checkbox_size - 2, checkbox_y + checkbox_size - 2
                    ), MULTI_SELECT_CHECK);
                }
                item_text_x += checkbox_size + 6.0f;
            }

            // File status indicator (M/A/D/R/?)
            if (r.type == PaletteResultType::File && r.file.utf8_path) {
                wchar_t status_char;
                uint32_t status_color;

                switch (r.file.status) {
                    case PaletteResult::FileStatus::Added:
                        status_char = L'A';
                        status_color = Theme::STATUS_ADDED;
                        break;
                    case PaletteResult::FileStatus::Deleted:
                        status_char = L'D';
                        status_color = Theme::STATUS_DELETED;
                        break;
                    case PaletteResult::FileStatus::Renamed:
                        status_char = L'R';
                        status_color = Theme::STATUS_RENAMED;
                        break;
                    case PaletteResult::FileStatus::Untracked:
                        status_char = L'?';
                        status_color = Theme::TEXT_SECONDARY;
                        break;
                    case PaletteResult::FileStatus::Modified:
                    default:
                        status_char = L'M';
                        status_color = Theme::STATUS_MODIFIED;
                        break;
                }

                if (g_text_format_body) {
                    D2D1_RECT_F status_rect = D2D1::RectF(
                        item_text_x, item_text_y,
                        item_text_x + STATUS_WIDTH, item_text_y + TEXT_LINE_HEIGHT
                    );
                    ctx.draw_text(&status_char, 1, g_text_format_body, status_rect, status_color);
                }
                item_text_x += STATUS_WIDTH + 4.0f;
            }

            // Calculate text right edge - reserve space for shortcut only if present
            float text_right = r.shortcut
                ? palette_x + WIDTH - SHORTCUT_PADDING - 80.0f
                : palette_x + WIDTH - ITEM_PADDING;

            // Item name with ellipsis trimming and match highlighting
            if (r.display_text && g_text_format_body && g_dwrite_factory) {
                float text_width = text_right - item_text_x;
                UINT32 text_len = (UINT32)wcslen(r.display_text);
                IDWriteTextLayout* layout = nullptr;
                HRESULT hr = g_dwrite_factory->CreateTextLayout(
                    r.display_text, text_len,
                    g_text_format_body, text_width, TEXT_LINE_HEIGHT, &layout);

                if (SUCCEEDED(hr) && layout) {
                    // Set no wrap and ellipsis trimming
                    layout->SetWordWrapping(DWRITE_WORD_WRAPPING_NO_WRAP);
                    DWRITE_TRIMMING trimming = { DWRITE_TRIMMING_GRANULARITY_CHARACTER, 0, 0 };
                    IDWriteInlineObject* ellipsis = nullptr;
                    g_dwrite_factory->CreateEllipsisTrimmingSign(layout, &ellipsis);
                    if (ellipsis) {
                        layout->SetTrimming(&trimming, ellipsis);
                        ellipsis->Release();
                    }

                    // Apply match highlighting by drawing in two passes:
                    // 1. Draw entire text in default color
                    // 2. Overlay matched characters in highlight color
                    ctx.brush->SetColor(color_from_argb(ITEM_TEXT));
                    ctx.target->DrawTextLayout(
                        D2D1::Point2F(item_text_x, item_text_y),
                        layout, ctx.brush);

                    // If we have match mask, draw highlighted chars on top
                    if (r.match_mask != 0 && text_len <= 64) {
                        ctx.brush->SetColor(color_from_argb(MATCH_HIGHLIGHT));

                        // Find contiguous ranges of matched characters
                        UINT32 range_start = 0;
                        bool in_range = false;

                        for (UINT32 c = 0; c <= text_len; c++) {
                            bool is_match = (c < text_len) && ((r.match_mask >> c) & 1);

                            if (is_match && !in_range) {
                                range_start = c;
                                in_range = true;
                            } else if (!is_match && in_range) {
                                // Draw this range
                                DWRITE_TEXT_RANGE range = { range_start, c - range_start };
                                DWRITE_HIT_TEST_METRICS metrics;
                                float x_offset, y_offset;

                                // Get position of range start
                                layout->HitTestTextPosition(range_start, FALSE, &x_offset, &y_offset, &metrics);

                                // Create sub-layout for just this range
                                IDWriteTextLayout* sub_layout = nullptr;
                                hr = g_dwrite_factory->CreateTextLayout(
                                    r.display_text + range_start, range.length,
                                    g_text_format_body, text_width - x_offset, TEXT_LINE_HEIGHT, &sub_layout);

                                if (SUCCEEDED(hr) && sub_layout) {
                                    sub_layout->SetWordWrapping(DWRITE_WORD_WRAPPING_NO_WRAP);
                                    ctx.target->DrawTextLayout(
                                        D2D1::Point2F(item_text_x + x_offset, item_text_y),
                                        sub_layout, ctx.brush);
                                    sub_layout->Release();
                                }

                                in_range = false;
                            }
                        }
                    }

                    layout->Release();
                }
            }

            // Shortcut (for commands)
            if (r.shortcut && g_text_format_hint) {
                wchar_t shortcut_wide[32];
                utf8_to_wide(r.shortcut, shortcut_wide, 32);

                D2D1_RECT_F shortcut_rect = D2D1::RectF(
                    palette_x + WIDTH - SHORTCUT_PADDING - 80.0f, item_text_y,
                    palette_x + WIDTH - SHORTCUT_PADDING, item_text_y + TEXT_LINE_HEIGHT
                );
                ctx.draw_text(shortcut_wide, wcslen(shortcut_wide), g_text_format_hint, shortcut_rect, SHORTCUT_TEXT);
            }

            item_y += ITEM_HEIGHT;
            items_rendered++;
        }

        // Draw empty state message when no results and user has typed a query
        if (g_palette.result_count == 0 && g_palette.query_len > 0 && !g_palette.input_mode) {
            const wchar_t* message = L"No results found";
            const wchar_t* hint = L"";

            switch (g_palette.mode) {
                case PaletteMode::Commands:
                    message = L"No commands found";
                    hint = L"Try removing > to search all";
                    break;
                case PaletteMode::Files:
                    message = L"No files match";
                    hint = L"Only changed files are searchable";
                    break;
                case PaletteMode::Branches:
                    message = L"No branches match";
                    hint = L"Try a different name";
                    break;
                case PaletteMode::Commits:
                    message = L"No commits match";
                    hint = L"Try searching by message or author";
                    break;
                case PaletteMode::Remotes:
                    message = L"No remotes configured";
                    break;
                case PaletteMode::AutoDetect:
                default:
                    break;
            }

            float empty_y = palette_y + INPUT_ROW_HEIGHT + 20.0f;
            D2D1_RECT_F msg_rect = D2D1::RectF(
                palette_x + ITEM_PADDING, empty_y,
                palette_x + WIDTH - ITEM_PADDING, empty_y + TEXT_LINE_HEIGHT
            );
            ctx.draw_text(message, wcslen(message), g_text_format_body, msg_rect, ITEM_TEXT);

            if (hint[0] != L'\0') {
                float hint_y_pos = empty_y + TEXT_LINE_HEIGHT + 4.0f;
                D2D1_RECT_F hint_rect_inner = D2D1::RectF(
                    palette_x + ITEM_PADDING, hint_y_pos,
                    palette_x + WIDTH - ITEM_PADDING, hint_y_pos + TEXT_LINE_HEIGHT
                );
                ctx.draw_text(hint, wcslen(hint), g_text_format_hint, hint_rect_inner, PLACEHOLDER_TEXT);
            }
        }

        // Draw hint row
        if (g_text_format_hint) {
            float hint_y = palette_y + palette_height - HINT_ROW_HEIGHT;
            D2D1_RECT_F hint_rect = D2D1::RectF(
                palette_x + ITEM_PADDING, hint_y,
                palette_x + WIDTH - ITEM_PADDING, hint_y + HINT_ROW_HEIGHT
            );

            const wchar_t* hint = L"> commands  / files  @ branches  # commits  : remotes";
            ctx.draw_text(hint, wcslen(hint), g_text_format_hint, hint_rect, PLACEHOLDER_TEXT);
        }

        // Apply blur effect to entire palette if animating
        // (This creates the "material" feel as the palette appears)
        if (g_palette.animating && g_palette.anim_blur > 0.1f &&
            g_d2d_device_context && g_blur_effect) {
            // Note: Blur is applied to the entire window during animation via
            // a separate effect. The palette itself renders sharp, but the
            // overlay beneath it can be blurred to create depth.
        }

        // Restore transform
        ctx.target->SetTransform(old_transform);
    }

    bool on_key_down(int vk, bool ctrl, bool shift, bool alt) override {
        (void)alt;
        if (!g_palette.visible) return false;

        switch (vk) {
            case VK_ESCAPE:
                return on_escape();  // Handles input_mode exit before closing

            case VK_RETURN:
                // Ctrl+Enter toggles selection for files (keyboard multi-select)
                if (ctrl && !g_palette.input_mode && g_palette.result_count > 0 &&
                    g_palette.selected_index >= 0 && (size_t)g_palette.selected_index < g_palette.result_count) {
                    PaletteResult& r = g_palette.results[g_palette.selected_index];
                    if (r.type == PaletteResultType::File) {
                        r.selected = !r.selected;
                        g_palette.selected_count += r.selected ? 1 : -1;
                        g_palette.multi_select_mode = (g_palette.selected_count > 0);
                        InvalidateRect(g_main_window, nullptr, FALSE);
                        return true;
                    }
                }
                // In input mode, execute the pending command with the input
                if (g_palette.input_mode && g_palette.pending_command) {
                    if (g_palette.query_len > 0) {
                        const PaletteCommand* cmd = g_palette.pending_command;
                        wchar_t input[PALETTE_MAX_QUERY];
                        wcscpy_s(input, g_palette.query);
                        command_palette_hide();
                        palette_execute_with_input(cmd, input);
                    }
                    return true;
                }
                // Normal mode - execute selected result
                if (g_palette.result_count > 0 && g_palette.selected_index >= 0 &&
                    (size_t)g_palette.selected_index < g_palette.result_count) {
                    palette_execute_result(g_palette.results[g_palette.selected_index]);
                }
                return true;

            case VK_UP:
                if (g_palette.selected_index > 0) {
                    g_palette.selected_index--;
                    // Scroll if needed
                    if (g_palette.selected_index < g_palette.scroll_offset) {
                        g_palette.scroll_offset = g_palette.selected_index;
                    }
                    set_dirty();
                }
                return true;

            case VK_DOWN:
                // Guard against underflow when result_count==0 (would make `result_count - 1`
                // wrap to SIZE_MAX and the comparison succeed, dereferencing past results).
                if (g_palette.result_count > 0 &&
                    (size_t)g_palette.selected_index + 1 < g_palette.result_count) {
                    g_palette.selected_index++;
                    // Scroll so selected fits in view (scroll minimum needed)
                    while (!items_fit_in_view(g_palette.scroll_offset, g_palette.selected_index)) {
                        g_palette.scroll_offset++;
                    }
                    set_dirty();
                }
                return true;

            case VK_PRIOR:  // Page Up
                g_palette.selected_index = (g_palette.selected_index > 5) ? g_palette.selected_index - 5 : 0;
                if (g_palette.selected_index < g_palette.scroll_offset) {
                    g_palette.scroll_offset = g_palette.selected_index;
                }
                set_dirty();
                return true;

            case VK_NEXT:   // Page Down
                if (g_palette.result_count == 0) return true;
                g_palette.selected_index = ((size_t)g_palette.selected_index + 5 < g_palette.result_count)
                    ? g_palette.selected_index + 5
                    : (int)g_palette.result_count - 1;
                while (!items_fit_in_view(g_palette.scroll_offset, g_palette.selected_index)) {
                    g_palette.scroll_offset++;
                }
                set_dirty();
                return true;

            case VK_HOME:
                g_palette.selected_index = 0;
                g_palette.scroll_offset = 0;
                set_dirty();
                return true;

            case VK_END:
                g_palette.selected_index = (int)g_palette.result_count - 1;
                while (!items_fit_in_view(g_palette.scroll_offset, g_palette.selected_index)) {
                    g_palette.scroll_offset++;
                }
                set_dirty();
                return true;

            case VK_TAB:
                // Cycle mode
                if (ctrl) {
                    int mode = (int)g_palette.mode;
                    if (shift) {
                        mode = (mode > 0) ? mode - 1 : (int)PaletteMode::Remotes;
                    } else {
                        mode = (mode < (int)PaletteMode::Remotes) ? mode + 1 : 0;
                    }
                    g_palette.mode = (PaletteMode)mode;
                    palette_update_search();
                    set_dirty();
                }
                return true;

            case VK_BACK:
                if (g_palette.query_len > 0 && g_palette.cursor_pos > 0) {
                    wmemmove(g_palette.query + g_palette.cursor_pos - 1,
                             g_palette.query + g_palette.cursor_pos,
                             g_palette.query_len - g_palette.cursor_pos + 1);
                    g_palette.query_len--;
                    g_palette.cursor_pos--;

                    // Only update search in normal mode (not input mode)
                    if (!g_palette.input_mode) {
                        // Check if we should switch back to auto-detect
                        if (g_palette.query_len == 0) {
                            g_palette.mode = PaletteMode::AutoDetect;
                        }
                        palette_update_search();
                    }
                    set_dirty();
                }
                return true;

            case 'U':
                if (ctrl) {
                    // Clear input
                    g_palette.query[0] = L'\0';
                    g_palette.query_len = 0;
                    g_palette.cursor_pos = 0;
                    // Only reset mode and search in normal mode
                    if (!g_palette.input_mode) {
                        g_palette.mode = PaletteMode::AutoDetect;
                        palette_update_search();
                    }
                    set_dirty();
                    return true;
                }
                break;
        }

        return true;  // Capture all keys when visible
    }

    bool on_char(wchar_t ch) override {
        if (!g_palette.visible) return false;

        // Filter control characters
        if (ch < 32 && ch != L'\t') return true;
        if (ch == 127) return true;  // DEL

        // Add character to query
        if (g_palette.query_len < PALETTE_MAX_QUERY - 1) {
            // Insert at cursor position
            if (g_palette.cursor_pos < g_palette.query_len) {
                wmemmove(g_palette.query + g_palette.cursor_pos + 1,
                         g_palette.query + g_palette.cursor_pos,
                         g_palette.query_len - g_palette.cursor_pos + 1);
            }
            g_palette.query[g_palette.cursor_pos] = ch;
            g_palette.cursor_pos++;
            g_palette.query_len++;
            g_palette.query[g_palette.query_len] = L'\0';

            // Only detect mode and search in normal mode (not input mode)
            if (!g_palette.input_mode) {
                palette_detect_mode();
                palette_update_search();
            }
            set_dirty();
        }

        return true;
    }

    bool on_mouse_move(float x, float y) override {
        if (!g_palette.visible) return false;

        using namespace CommandPalette;

        float palette_x = (rect.width - WIDTH) / 2.0f;
        float palette_y = TOP_OFFSET;

        // Use shared helper for visible item count
        ResultsLayout results_layout = calculate_results_layout();

        // Check if mouse is over a result item
        float item_y = palette_y + INPUT_ROW_HEIGHT;
        if (g_palette.multi_select_mode && g_palette.selected_count > 0) {
            item_y += BATCH_ACTION_HEIGHT;
        }

        // Account for group headers in auto-detect mode (cap at visible items)
        PaletteResultType last_type = (PaletteResultType)-1;
        int new_hover = -1;
        int items_checked = 0;

        for (size_t i = g_palette.scroll_offset; i < g_palette.result_count && items_checked < results_layout.visible_count; i++) {
            const PaletteResult& r = g_palette.results[i];

            // Add group header height
            if (g_palette.mode == PaletteMode::AutoDetect && r.type != last_type) {
                item_y += GROUP_HEADER_HEIGHT;
                last_type = r.type;
            }

            if (y >= item_y && y < item_y + ITEM_HEIGHT &&
                x >= palette_x && x < palette_x + WIDTH) {
                new_hover = (int)i;
                break;
            }
            item_y += ITEM_HEIGHT;
            items_checked++;
        }

        if (new_hover != g_palette.hovered_index) {
            g_palette.hovered_index = new_hover;
            InvalidateRect(g_main_window, nullptr, FALSE);
        }

        return true;
    }

    // Accumulator for smooth scrolling (precision touchpad sends small deltas)
    float scroll_accumulator = 0.0f;

    bool on_mouse_wheel(float x, float y, float delta) override {
        (void)x; (void)y;
        if (!g_palette.visible || g_palette.result_count == 0) return false;

        using namespace CommandPalette;

        // Match scroll feel with other components:
        // ScrollContainer uses delta * 40.0f pixels, ITEM_HEIGHT = 32.0f
        // So items = delta * 40 / 32 = delta * 1.25
        constexpr float SCROLL_SENSITIVITY = 1.25f;
        scroll_accumulator += delta * SCROLL_SENSITIVITY;

        // Scroll by whole items
        int scroll_items = (int)scroll_accumulator;
        if (scroll_items != 0) {
            scroll_accumulator -= (float)scroll_items;

            int max_scroll = (int)g_palette.result_count - 1;
            if (max_scroll < 0) max_scroll = 0;

            // Note: positive delta = scroll up = decrease offset
            g_palette.scroll_offset -= scroll_items;
            if (g_palette.scroll_offset < 0) g_palette.scroll_offset = 0;
            if (g_palette.scroll_offset > max_scroll) g_palette.scroll_offset = max_scroll;

            InvalidateRect(g_main_window, nullptr, FALSE);
        }

        return true;
    }

    bool on_mouse_down(float x, float y, int button) override {
        (void)button;
        if (!g_palette.visible) return false;

        using namespace CommandPalette;

        float palette_x = (rect.width - WIDTH) / 2.0f;
        float palette_y = TOP_OFFSET;

        // Check if click is outside palette (dismiss) - uses shared helper for accurate height
        ResultsLayout results_layout = calculate_results_layout();
        float palette_height = INPUT_ROW_HEIGHT + results_layout.height + HINT_ROW_HEIGHT;
        if (g_palette.multi_select_mode && g_palette.selected_count > 0) {
            palette_height += BATCH_ACTION_HEIGHT;
        }
        if (x < palette_x || x >= palette_x + WIDTH ||
            y < palette_y || y >= palette_y + palette_height) {
            command_palette_hide();
            return true;
        }

        // Check if Ctrl is held for multi-select
        bool ctrl_held = (GetKeyState(VK_CONTROL) & 0x8000) != 0;

        // Check if click is on batch action bar (when visible)
        if (g_palette.multi_select_mode && g_palette.selected_count > 0) {
            float batch_bar_y = palette_y + INPUT_ROW_HEIGHT;
            if (y >= batch_bar_y && y < batch_bar_y + BATCH_ACTION_HEIGHT) {
                // Execute batch action
                palette_execute_batch_action();
                return true;
            }
        }

        // Check if click is on a result item (account for group headers and visible cap)
        float item_y = palette_y + INPUT_ROW_HEIGHT;
        if (g_palette.multi_select_mode && g_palette.selected_count > 0) {
            item_y += BATCH_ACTION_HEIGHT;
        }

        PaletteResultType last_type = (PaletteResultType)-1;
        int items_checked = 0;
        for (size_t i = g_palette.scroll_offset; i < g_palette.result_count && items_checked < results_layout.visible_count; i++) {
            // Account for group headers in AutoDetect mode
            if (g_palette.mode == PaletteMode::AutoDetect && g_palette.results[i].type != last_type) {
                item_y += GROUP_HEADER_HEIGHT;
                last_type = g_palette.results[i].type;
            }

            if (y >= item_y && y < item_y + ITEM_HEIGHT) {
                g_palette.selected_index = (int)i;
                PaletteResult& r = g_palette.results[i];

                // Ctrl+Click on files toggles selection
                if (ctrl_held && r.type == PaletteResultType::File) {
                    r.selected = !r.selected;
                    g_palette.selected_count += r.selected ? 1 : -1;
                    g_palette.multi_select_mode = (g_palette.selected_count > 0);
                    InvalidateRect(g_main_window, nullptr, FALSE);
                    return true;
                }

                // Normal click executes
                palette_execute_result(r);
                return true;
            }
            item_y += ITEM_HEIGHT;
            items_checked++;
        }

        return true;
    }
};

static CommandPaletteWidget* g_palette_widget = nullptr;

// ============================================================================
// Public API
// ============================================================================

void command_palette_show() {
    if (g_palette.visible && !g_palette.dismissing) return;

    // Initialize command registry if not already done
    static bool registry_initialized = false;
    if (!registry_initialized) {
        command_registry_init();
        registry_initialized = true;
    }

    // Reset state
    g_palette.visible = true;
    g_palette.mode = PaletteMode::AutoDetect;
    g_palette.query[0] = L'\0';
    g_palette.query_len = 0;
    g_palette.cursor_pos = 0;
    g_palette.result_count = 0;
    g_palette.selected_index = 0;
    g_palette.scroll_offset = 0;
    g_palette.hovered_index = -1;
    g_palette.multi_select_mode = false;
    g_palette.selected_count = 0;
    g_palette.input_mode = false;
    g_palette.pending_command = nullptr;

    // Start spring animation (simplified single-layer model)
    g_palette.animating = true;
    g_palette.dismissing = false;

    // Initialize spring animation state
    g_palette.anim_scale = CommandPalette::SPRING_START_SCALE;  // Start at 92%
    g_palette.anim_velocity = 0.0f;  // Let spring restoring force drive the motion
    g_palette.anim_opacity = 0.0f;
    g_palette.anim_blur = CommandPalette::BLUR_RADIUS;  // Start with subtle blur

    // Register with animation scheduler for self-driving render loop.
    // Invariant: `is_animating` is true iff exactly one animation_started()
    // is outstanding for the palette. show() during a mid-dismiss
    // reuses the existing registration; finish_hide() (or opening
    // completion) is the only path that calls animation_ended().
    if (!g_palette.is_animating) {
        g_palette.is_animating = true;
        g_animation_scheduler.animation_started();
    }

    // Create widget if needed
    if (!g_palette_widget) {
        g_palette_widget = g_widget_arena.create<CommandPaletteWidget>();
    }

    // Set as event dispatcher root to capture all input
    g_event_dispatcher.root = g_palette_widget;
    g_event_dispatcher.set_focus(g_palette_widget, true);

    // Initial search (show recent/all)
    palette_update_search();

    // Request redraw
    InvalidateRect(g_main_window, nullptr, FALSE);

    LOG("Command palette opened");
}

void command_palette_hide() {
    if (!g_palette.visible) return;
    if (g_palette.dismissing) return;  // Already dismissing

    // Start dismiss animation (fast fade)
    g_palette.animating = true;
    g_palette.dismissing = true;

    g_palette.input_mode = false;
    g_palette.pending_command = nullptr;

    // Ensure we're registered with animation scheduler
    if (!g_palette.is_animating) {
        g_palette.is_animating = true;
        g_animation_scheduler.animation_started();
    }

    // Request redraw (animation will complete the hide)
    InvalidateRect(g_main_window, nullptr, FALSE);

    LOG("Command palette closing");
}

// Called when dismiss animation completes
static void command_palette_finish_hide() {
    g_palette.visible = false;
    g_palette.animating = false;
    g_palette.dismissing = false;
    g_event_dispatcher.root = nullptr;

    // Reset animation state
    g_palette.anim_scale = 1.0f;
    g_palette.anim_velocity = 0.0f;
    g_palette.anim_opacity = 0.0f;
    g_palette.anim_blur = 0.0f;

    // Unregister from animation scheduler
    if (g_palette.is_animating) {
        g_palette.is_animating = false;
        g_animation_scheduler.animation_ended();
    }

    LOG("Command palette closed");
}

// Tick command palette animation (called from tick_all_animations)
void command_palette_tick(float dt) {
    if (!g_palette.animating) return;

    using namespace CommandPalette;

    if (!g_palette.dismissing) {
        // ==================== OPENING ANIMATION (Single-Layer Model) ====================
        //
        // Entire palette scales together with spring physics.
        // Opacity fades in linearly while scale uses spring.
        // Blur decreases as opacity increases (material depth effect).

        // Opacity fades in quickly (150ms)
        g_palette.anim_opacity = fminf(1.0f, g_palette.anim_opacity + dt / OPACITY_DURATION);

        // Spring physics for scale (analytical solution - frame-rate independent)
        spring_update_windows_style(g_palette.anim_scale, g_palette.anim_velocity, 1.0f, dt,
                                    SPRING_PERIOD, SPRING_DAMPING_RATIO);

        // Blur decreases as palette becomes more visible (0 blur at full opacity)
        g_palette.anim_blur = BLUR_RADIUS * (1.0f - g_palette.anim_opacity);

        // Check if animation is complete (scale settled at 1.0 and full opacity)
        bool animation_done = g_palette.anim_opacity >= 1.0f &&
                              fabsf(g_palette.anim_scale - 1.0f) < 0.001f &&
                              fabsf(g_palette.anim_velocity) < 0.01f;

        if (animation_done) {
            // Animation complete - snap to final values
            g_palette.animating = false;
            g_palette.anim_scale = 1.0f;
            g_palette.anim_opacity = 1.0f;
            g_palette.anim_blur = 0.0f;

            // Unregister from scheduler
            if (g_palette.is_animating) {
                g_palette.is_animating = false;
                g_animation_scheduler.animation_ended();
            }
        }
    } else {
        // ==================== CLOSING ANIMATION ====================
        // Fast fade out (80ms)
        constexpr float CLOSE_DURATION = DISMISS_DURATION_MS / 1000.0f;
        float fade_progress = (1.0f - g_palette.anim_opacity) + dt / CLOSE_DURATION;

        if (fade_progress >= 1.0f) {
            command_palette_finish_hide();
            return;
        }

        // Fade out quickly
        g_palette.anim_opacity = 1.0f - fade_progress;

        // Slight shrink during close
        g_palette.anim_scale = 1.0f - fade_progress * 0.03f;
    }

    // Request repaint
    InvalidateRect(g_main_window, nullptr, FALSE);
}

bool command_palette_is_visible() {
    return g_palette.visible;
}

void command_palette_toggle() {
    if (g_palette.visible) {
        command_palette_hide();
    } else {
        command_palette_show();
    }
}

void command_palette_render() {
    if (!g_palette.visible || !g_palette_widget || !g_render_target) return;

    // Create a brush for rendering
    ID2D1SolidColorBrush* brush = nullptr;
    g_render_target->CreateSolidColorBrush(D2D1::ColorF(1.0f, 1.0f, 1.0f, 1.0f), &brush);
    if (!brush) return;

    // Set up widget rect to cover the whole window
    D2D1_SIZE_F size = g_render_target->GetSize();
    g_palette_widget->rect = { 0, 0, size.width, size.height };

    // Create RenderContext and render
    RenderContext ctx = { g_render_target, brush };
    g_palette_widget->render(ctx);

    brush->Release();
}
